// Code generated by sqlc. DO NOT EDIT.
package sqlc

import (
	"time"

	"github.com/google/uuid"
)

type Vendor struct {
	ID        uuid.UUID
	Name      string
	Email     string
	CreatedAt time.Time
}

type VendorProduct struct {
	ID        uuid.UUID
	VendorID  uuid.UUID
	ProductID uuid.UUID
}

type VendorPayout struct {
	ID        uuid.UUID
	VendorID  uuid.UUID
	AmountYen int32
	PaidAt    time.Time
}

type VendorReview struct {
	ID       uuid.UUID
	VendorID uuid.UUID
	MemberID uuid.UUID
	Rating   int32
	Comment  string
}

type VendorDocument struct {
	ID       uuid.UUID
	VendorID uuid.UUID
	Url      string
	DocType  string
}

type VendorCategory struct {
	ID         uuid.UUID
	VendorID   uuid.UUID
	CategoryID uuid.UUID
}

type VendorCommission struct {
	ID          uuid.UUID
	VendorID    uuid.UUID
	RatePercent int32
}

type VendorBankAccount struct {
	ID            uuid.UUID
	VendorID      uuid.UUID
	AccountNumber string
}

type VendorContract struct {
	ID       uuid.UUID
	VendorID uuid.UUID
	StartsAt time.Time
	EndsAt   time.Time
}

type VendorPerformanceMetric struct {
	ID         uuid.UUID
	VendorID   uuid.UUID
	MetricName string
	Value      int32
	RecordedAt time.Time
}
