// Code generated by sqlc. DO NOT EDIT.
package sqlc

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const createVendor = `-- name: CreateVendor :one
INSERT INTO vendors (id, name, email, created_at)
VALUES ($1, $2, $3, $4)
RETURNING id, name, email, created_at
`

type CreateVendorParams struct {
	ID        uuid.UUID
	Name      string
	Email     string
	CreatedAt time.Time
}

func (q *Queries) CreateVendor(ctx context.Context, arg CreateVendorParams) (Vendor, error) {
	row := q.db.QueryRowContext(ctx, createVendor, arg.ID, arg.Name, arg.Email, arg.CreatedAt)
	var i Vendor
	err := row.Scan(&i.ID, &i.Name, &i.Email, &i.CreatedAt)
	return i, err
}

const getVendor = `-- name: GetVendor :one
SELECT id, name, email, created_at FROM vendors WHERE id = $1
`

func (q *Queries) GetVendor(ctx context.Context, id uuid.UUID) (Vendor, error) {
	row := q.db.QueryRowContext(ctx, getVendor, id)
	var i Vendor
	err := row.Scan(&i.ID, &i.Name, &i.Email, &i.CreatedAt)
	return i, err
}

const listVendors = `-- name: ListVendors :many
SELECT id, name, email, created_at FROM vendors ORDER BY created_at DESC
`

func (q *Queries) ListVendors(ctx context.Context) ([]Vendor, error) {
	rows, err := q.db.QueryContext(ctx, listVendors)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Vendor
	for rows.Next() {
		var i Vendor
		if err := rows.Scan(&i.ID, &i.Name, &i.Email, &i.CreatedAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const deleteVendor = `-- name: DeleteVendor :exec
DELETE FROM vendors WHERE id = $1
`

func (q *Queries) DeleteVendor(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, deleteVendor, id)
	return err
}

const createVendorProduct = `-- name: CreateVendorProduct :one
INSERT INTO vendor_products (id, vendor_id, product_id)
VALUES ($1, $2, $3)
RETURNING id, vendor_id, product_id
`

type CreateVendorProductParams struct {
	ID        uuid.UUID
	VendorID  uuid.UUID
	ProductID uuid.UUID
}

func (q *Queries) CreateVendorProduct(ctx context.Context, arg CreateVendorProductParams) (VendorProduct, error) {
	row := q.db.QueryRowContext(ctx, createVendorProduct, arg.ID, arg.VendorID, arg.ProductID)
	var i VendorProduct
	err := row.Scan(&i.ID, &i.VendorID, &i.ProductID)
	return i, err
}

const getVendorProduct = `-- name: GetVendorProduct :one
SELECT id, vendor_id, product_id FROM vendor_products WHERE id = $1
`

func (q *Queries) GetVendorProduct(ctx context.Context, id uuid.UUID) (VendorProduct, error) {
	row := q.db.QueryRowContext(ctx, getVendorProduct, id)
	var i VendorProduct
	err := row.Scan(&i.ID, &i.VendorID, &i.ProductID)
	return i, err
}

const listVendorProducts = `-- name: ListVendorProducts :many
SELECT id, vendor_id, product_id FROM vendor_products ORDER BY id DESC
`

func (q *Queries) ListVendorProducts(ctx context.Context) ([]VendorProduct, error) {
	rows, err := q.db.QueryContext(ctx, listVendorProducts)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []VendorProduct
	for rows.Next() {
		var i VendorProduct
		if err := rows.Scan(&i.ID, &i.VendorID, &i.ProductID); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listVendorProductsByVendorID = `-- name: ListVendorProductsByVendorID :many
SELECT id, vendor_id, product_id FROM vendor_products WHERE vendor_id = $1 ORDER BY id DESC
`

func (q *Queries) ListVendorProductsByVendorID(ctx context.Context, vendorID uuid.UUID) ([]VendorProduct, error) {
	rows, err := q.db.QueryContext(ctx, listVendorProductsByVendorID, vendorID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []VendorProduct
	for rows.Next() {
		var i VendorProduct
		if err := rows.Scan(&i.ID, &i.VendorID, &i.ProductID); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const deleteVendorProduct = `-- name: DeleteVendorProduct :exec
DELETE FROM vendor_products WHERE id = $1
`

func (q *Queries) DeleteVendorProduct(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, deleteVendorProduct, id)
	return err
}

const createVendorPayout = `-- name: CreateVendorPayout :one
INSERT INTO vendor_payouts (id, vendor_id, amount_yen, paid_at)
VALUES ($1, $2, $3, $4)
RETURNING id, vendor_id, amount_yen, paid_at
`

type CreateVendorPayoutParams struct {
	ID        uuid.UUID
	VendorID  uuid.UUID
	AmountYen int32
	PaidAt    time.Time
}

func (q *Queries) CreateVendorPayout(ctx context.Context, arg CreateVendorPayoutParams) (VendorPayout, error) {
	row := q.db.QueryRowContext(ctx, createVendorPayout, arg.ID, arg.VendorID, arg.AmountYen, arg.PaidAt)
	var i VendorPayout
	err := row.Scan(&i.ID, &i.VendorID, &i.AmountYen, &i.PaidAt)
	return i, err
}

const getVendorPayout = `-- name: GetVendorPayout :one
SELECT id, vendor_id, amount_yen, paid_at FROM vendor_payouts WHERE id = $1
`

func (q *Queries) GetVendorPayout(ctx context.Context, id uuid.UUID) (VendorPayout, error) {
	row := q.db.QueryRowContext(ctx, getVendorPayout, id)
	var i VendorPayout
	err := row.Scan(&i.ID, &i.VendorID, &i.AmountYen, &i.PaidAt)
	return i, err
}

const listVendorPayouts = `-- name: ListVendorPayouts :many
SELECT id, vendor_id, amount_yen, paid_at FROM vendor_payouts ORDER BY paid_at DESC
`

func (q *Queries) ListVendorPayouts(ctx context.Context) ([]VendorPayout, error) {
	rows, err := q.db.QueryContext(ctx, listVendorPayouts)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []VendorPayout
	for rows.Next() {
		var i VendorPayout
		if err := rows.Scan(&i.ID, &i.VendorID, &i.AmountYen, &i.PaidAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listVendorPayoutsByVendorID = `-- name: ListVendorPayoutsByVendorID :many
SELECT id, vendor_id, amount_yen, paid_at FROM vendor_payouts WHERE vendor_id = $1 ORDER BY paid_at DESC
`

func (q *Queries) ListVendorPayoutsByVendorID(ctx context.Context, vendorID uuid.UUID) ([]VendorPayout, error) {
	rows, err := q.db.QueryContext(ctx, listVendorPayoutsByVendorID, vendorID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []VendorPayout
	for rows.Next() {
		var i VendorPayout
		if err := rows.Scan(&i.ID, &i.VendorID, &i.AmountYen, &i.PaidAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const deleteVendorPayout = `-- name: DeleteVendorPayout :exec
DELETE FROM vendor_payouts WHERE id = $1
`

func (q *Queries) DeleteVendorPayout(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, deleteVendorPayout, id)
	return err
}

const createVendorReview = `-- name: CreateVendorReview :one
INSERT INTO vendor_reviews (id, vendor_id, member_id, rating, comment)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, vendor_id, member_id, rating, comment
`

type CreateVendorReviewParams struct {
	ID       uuid.UUID
	VendorID uuid.UUID
	MemberID uuid.UUID
	Rating   int32
	Comment  string
}

func (q *Queries) CreateVendorReview(ctx context.Context, arg CreateVendorReviewParams) (VendorReview, error) {
	row := q.db.QueryRowContext(ctx, createVendorReview, arg.ID, arg.VendorID, arg.MemberID, arg.Rating, arg.Comment)
	var i VendorReview
	err := row.Scan(&i.ID, &i.VendorID, &i.MemberID, &i.Rating, &i.Comment)
	return i, err
}

const getVendorReview = `-- name: GetVendorReview :one
SELECT id, vendor_id, member_id, rating, comment FROM vendor_reviews WHERE id = $1
`

func (q *Queries) GetVendorReview(ctx context.Context, id uuid.UUID) (VendorReview, error) {
	row := q.db.QueryRowContext(ctx, getVendorReview, id)
	var i VendorReview
	err := row.Scan(&i.ID, &i.VendorID, &i.MemberID, &i.Rating, &i.Comment)
	return i, err
}

const listVendorReviews = `-- name: ListVendorReviews :many
SELECT id, vendor_id, member_id, rating, comment FROM vendor_reviews ORDER BY id DESC
`

func (q *Queries) ListVendorReviews(ctx context.Context) ([]VendorReview, error) {
	rows, err := q.db.QueryContext(ctx, listVendorReviews)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []VendorReview
	for rows.Next() {
		var i VendorReview
		if err := rows.Scan(&i.ID, &i.VendorID, &i.MemberID, &i.Rating, &i.Comment); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listVendorReviewsByVendorID = `-- name: ListVendorReviewsByVendorID :many
SELECT id, vendor_id, member_id, rating, comment FROM vendor_reviews WHERE vendor_id = $1 ORDER BY id DESC
`

func (q *Queries) ListVendorReviewsByVendorID(ctx context.Context, vendorID uuid.UUID) ([]VendorReview, error) {
	rows, err := q.db.QueryContext(ctx, listVendorReviewsByVendorID, vendorID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []VendorReview
	for rows.Next() {
		var i VendorReview
		if err := rows.Scan(&i.ID, &i.VendorID, &i.MemberID, &i.Rating, &i.Comment); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const deleteVendorReview = `-- name: DeleteVendorReview :exec
DELETE FROM vendor_reviews WHERE id = $1
`

func (q *Queries) DeleteVendorReview(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, deleteVendorReview, id)
	return err
}

const createVendorDocument = `-- name: CreateVendorDocument :one
INSERT INTO vendor_documents (id, vendor_id, url, doc_type)
VALUES ($1, $2, $3, $4)
RETURNING id, vendor_id, url, doc_type
`

type CreateVendorDocumentParams struct {
	ID       uuid.UUID
	VendorID uuid.UUID
	Url      string
	DocType  string
}

func (q *Queries) CreateVendorDocument(ctx context.Context, arg CreateVendorDocumentParams) (VendorDocument, error) {
	row := q.db.QueryRowContext(ctx, createVendorDocument, arg.ID, arg.VendorID, arg.Url, arg.DocType)
	var i VendorDocument
	err := row.Scan(&i.ID, &i.VendorID, &i.Url, &i.DocType)
	return i, err
}

const getVendorDocument = `-- name: GetVendorDocument :one
SELECT id, vendor_id, url, doc_type FROM vendor_documents WHERE id = $1
`

func (q *Queries) GetVendorDocument(ctx context.Context, id uuid.UUID) (VendorDocument, error) {
	row := q.db.QueryRowContext(ctx, getVendorDocument, id)
	var i VendorDocument
	err := row.Scan(&i.ID, &i.VendorID, &i.Url, &i.DocType)
	return i, err
}

const listVendorDocuments = `-- name: ListVendorDocuments :many
SELECT id, vendor_id, url, doc_type FROM vendor_documents ORDER BY id DESC
`

func (q *Queries) ListVendorDocuments(ctx context.Context) ([]VendorDocument, error) {
	rows, err := q.db.QueryContext(ctx, listVendorDocuments)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []VendorDocument
	for rows.Next() {
		var i VendorDocument
		if err := rows.Scan(&i.ID, &i.VendorID, &i.Url, &i.DocType); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listVendorDocumentsByVendorID = `-- name: ListVendorDocumentsByVendorID :many
SELECT id, vendor_id, url, doc_type FROM vendor_documents WHERE vendor_id = $1 ORDER BY id DESC
`

func (q *Queries) ListVendorDocumentsByVendorID(ctx context.Context, vendorID uuid.UUID) ([]VendorDocument, error) {
	rows, err := q.db.QueryContext(ctx, listVendorDocumentsByVendorID, vendorID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []VendorDocument
	for rows.Next() {
		var i VendorDocument
		if err := rows.Scan(&i.ID, &i.VendorID, &i.Url, &i.DocType); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const deleteVendorDocument = `-- name: DeleteVendorDocument :exec
DELETE FROM vendor_documents WHERE id = $1
`

func (q *Queries) DeleteVendorDocument(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, deleteVendorDocument, id)
	return err
}

const createVendorCategory = `-- name: CreateVendorCategory :one
INSERT INTO vendor_categories (id, vendor_id, category_id)
VALUES ($1, $2, $3)
RETURNING id, vendor_id, category_id
`

type CreateVendorCategoryParams struct {
	ID         uuid.UUID
	VendorID   uuid.UUID
	CategoryID uuid.UUID
}

func (q *Queries) CreateVendorCategory(ctx context.Context, arg CreateVendorCategoryParams) (VendorCategory, error) {
	row := q.db.QueryRowContext(ctx, createVendorCategory, arg.ID, arg.VendorID, arg.CategoryID)
	var i VendorCategory
	err := row.Scan(&i.ID, &i.VendorID, &i.CategoryID)
	return i, err
}

const getVendorCategory = `-- name: GetVendorCategory :one
SELECT id, vendor_id, category_id FROM vendor_categories WHERE id = $1
`

func (q *Queries) GetVendorCategory(ctx context.Context, id uuid.UUID) (VendorCategory, error) {
	row := q.db.QueryRowContext(ctx, getVendorCategory, id)
	var i VendorCategory
	err := row.Scan(&i.ID, &i.VendorID, &i.CategoryID)
	return i, err
}

const listVendorCategories = `-- name: ListVendorCategories :many
SELECT id, vendor_id, category_id FROM vendor_categories ORDER BY id DESC
`

func (q *Queries) ListVendorCategories(ctx context.Context) ([]VendorCategory, error) {
	rows, err := q.db.QueryContext(ctx, listVendorCategories)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []VendorCategory
	for rows.Next() {
		var i VendorCategory
		if err := rows.Scan(&i.ID, &i.VendorID, &i.CategoryID); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listVendorCategoriesByVendorID = `-- name: ListVendorCategoriesByVendorID :many
SELECT id, vendor_id, category_id FROM vendor_categories WHERE vendor_id = $1 ORDER BY id DESC
`

func (q *Queries) ListVendorCategoriesByVendorID(ctx context.Context, vendorID uuid.UUID) ([]VendorCategory, error) {
	rows, err := q.db.QueryContext(ctx, listVendorCategoriesByVendorID, vendorID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []VendorCategory
	for rows.Next() {
		var i VendorCategory
		if err := rows.Scan(&i.ID, &i.VendorID, &i.CategoryID); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const deleteVendorCategory = `-- name: DeleteVendorCategory :exec
DELETE FROM vendor_categories WHERE id = $1
`

func (q *Queries) DeleteVendorCategory(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, deleteVendorCategory, id)
	return err
}

const createVendorCommission = `-- name: CreateVendorCommission :one
INSERT INTO vendor_commissions (id, vendor_id, rate_percent)
VALUES ($1, $2, $3)
RETURNING id, vendor_id, rate_percent
`

type CreateVendorCommissionParams struct {
	ID          uuid.UUID
	VendorID    uuid.UUID
	RatePercent int32
}

func (q *Queries) CreateVendorCommission(ctx context.Context, arg CreateVendorCommissionParams) (VendorCommission, error) {
	row := q.db.QueryRowContext(ctx, createVendorCommission, arg.ID, arg.VendorID, arg.RatePercent)
	var i VendorCommission
	err := row.Scan(&i.ID, &i.VendorID, &i.RatePercent)
	return i, err
}

const getVendorCommission = `-- name: GetVendorCommission :one
SELECT id, vendor_id, rate_percent FROM vendor_commissions WHERE id = $1
`

func (q *Queries) GetVendorCommission(ctx context.Context, id uuid.UUID) (VendorCommission, error) {
	row := q.db.QueryRowContext(ctx, getVendorCommission, id)
	var i VendorCommission
	err := row.Scan(&i.ID, &i.VendorID, &i.RatePercent)
	return i, err
}

const listVendorCommissions = `-- name: ListVendorCommissions :many
SELECT id, vendor_id, rate_percent FROM vendor_commissions ORDER BY id DESC
`

func (q *Queries) ListVendorCommissions(ctx context.Context) ([]VendorCommission, error) {
	rows, err := q.db.QueryContext(ctx, listVendorCommissions)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []VendorCommission
	for rows.Next() {
		var i VendorCommission
		if err := rows.Scan(&i.ID, &i.VendorID, &i.RatePercent); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listVendorCommissionsByVendorID = `-- name: ListVendorCommissionsByVendorID :many
SELECT id, vendor_id, rate_percent FROM vendor_commissions WHERE vendor_id = $1 ORDER BY id DESC
`

func (q *Queries) ListVendorCommissionsByVendorID(ctx context.Context, vendorID uuid.UUID) ([]VendorCommission, error) {
	rows, err := q.db.QueryContext(ctx, listVendorCommissionsByVendorID, vendorID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []VendorCommission
	for rows.Next() {
		var i VendorCommission
		if err := rows.Scan(&i.ID, &i.VendorID, &i.RatePercent); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const deleteVendorCommission = `-- name: DeleteVendorCommission :exec
DELETE FROM vendor_commissions WHERE id = $1
`

func (q *Queries) DeleteVendorCommission(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, deleteVendorCommission, id)
	return err
}

const createVendorBankAccount = `-- name: CreateVendorBankAccount :one
INSERT INTO vendor_bank_accounts (id, vendor_id, account_number)
VALUES ($1, $2, $3)
RETURNING id, vendor_id, account_number
`

type CreateVendorBankAccountParams struct {
	ID            uuid.UUID
	VendorID      uuid.UUID
	AccountNumber string
}

func (q *Queries) CreateVendorBankAccount(ctx context.Context, arg CreateVendorBankAccountParams) (VendorBankAccount, error) {
	row := q.db.QueryRowContext(ctx, createVendorBankAccount, arg.ID, arg.VendorID, arg.AccountNumber)
	var i VendorBankAccount
	err := row.Scan(&i.ID, &i.VendorID, &i.AccountNumber)
	return i, err
}

const getVendorBankAccount = `-- name: GetVendorBankAccount :one
SELECT id, vendor_id, account_number FROM vendor_bank_accounts WHERE id = $1
`

func (q *Queries) GetVendorBankAccount(ctx context.Context, id uuid.UUID) (VendorBankAccount, error) {
	row := q.db.QueryRowContext(ctx, getVendorBankAccount, id)
	var i VendorBankAccount
	err := row.Scan(&i.ID, &i.VendorID, &i.AccountNumber)
	return i, err
}

const listVendorBankAccounts = `-- name: ListVendorBankAccounts :many
SELECT id, vendor_id, account_number FROM vendor_bank_accounts ORDER BY id DESC
`

func (q *Queries) ListVendorBankAccounts(ctx context.Context) ([]VendorBankAccount, error) {
	rows, err := q.db.QueryContext(ctx, listVendorBankAccounts)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []VendorBankAccount
	for rows.Next() {
		var i VendorBankAccount
		if err := rows.Scan(&i.ID, &i.VendorID, &i.AccountNumber); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listVendorBankAccountsByVendorID = `-- name: ListVendorBankAccountsByVendorID :many
SELECT id, vendor_id, account_number FROM vendor_bank_accounts WHERE vendor_id = $1 ORDER BY id DESC
`

func (q *Queries) ListVendorBankAccountsByVendorID(ctx context.Context, vendorID uuid.UUID) ([]VendorBankAccount, error) {
	rows, err := q.db.QueryContext(ctx, listVendorBankAccountsByVendorID, vendorID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []VendorBankAccount
	for rows.Next() {
		var i VendorBankAccount
		if err := rows.Scan(&i.ID, &i.VendorID, &i.AccountNumber); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const deleteVendorBankAccount = `-- name: DeleteVendorBankAccount :exec
DELETE FROM vendor_bank_accounts WHERE id = $1
`

func (q *Queries) DeleteVendorBankAccount(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, deleteVendorBankAccount, id)
	return err
}

const createVendorContract = `-- name: CreateVendorContract :one
INSERT INTO vendor_contracts (id, vendor_id, starts_at, ends_at)
VALUES ($1, $2, $3, $4)
RETURNING id, vendor_id, starts_at, ends_at
`

type CreateVendorContractParams struct {
	ID       uuid.UUID
	VendorID uuid.UUID
	StartsAt time.Time
	EndsAt   time.Time
}

func (q *Queries) CreateVendorContract(ctx context.Context, arg CreateVendorContractParams) (VendorContract, error) {
	row := q.db.QueryRowContext(ctx, createVendorContract, arg.ID, arg.VendorID, arg.StartsAt, arg.EndsAt)
	var i VendorContract
	err := row.Scan(&i.ID, &i.VendorID, &i.StartsAt, &i.EndsAt)
	return i, err
}

const getVendorContract = `-- name: GetVendorContract :one
SELECT id, vendor_id, starts_at, ends_at FROM vendor_contracts WHERE id = $1
`

func (q *Queries) GetVendorContract(ctx context.Context, id uuid.UUID) (VendorContract, error) {
	row := q.db.QueryRowContext(ctx, getVendorContract, id)
	var i VendorContract
	err := row.Scan(&i.ID, &i.VendorID, &i.StartsAt, &i.EndsAt)
	return i, err
}

const listVendorContracts = `-- name: ListVendorContracts :many
SELECT id, vendor_id, starts_at, ends_at FROM vendor_contracts ORDER BY starts_at DESC
`

func (q *Queries) ListVendorContracts(ctx context.Context) ([]VendorContract, error) {
	rows, err := q.db.QueryContext(ctx, listVendorContracts)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []VendorContract
	for rows.Next() {
		var i VendorContract
		if err := rows.Scan(&i.ID, &i.VendorID, &i.StartsAt, &i.EndsAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listVendorContractsByVendorID = `-- name: ListVendorContractsByVendorID :many
SELECT id, vendor_id, starts_at, ends_at FROM vendor_contracts WHERE vendor_id = $1 ORDER BY starts_at DESC
`

func (q *Queries) ListVendorContractsByVendorID(ctx context.Context, vendorID uuid.UUID) ([]VendorContract, error) {
	rows, err := q.db.QueryContext(ctx, listVendorContractsByVendorID, vendorID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []VendorContract
	for rows.Next() {
		var i VendorContract
		if err := rows.Scan(&i.ID, &i.VendorID, &i.StartsAt, &i.EndsAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const deleteVendorContract = `-- name: DeleteVendorContract :exec
DELETE FROM vendor_contracts WHERE id = $1
`

func (q *Queries) DeleteVendorContract(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, deleteVendorContract, id)
	return err
}

const createVendorPerformanceMetric = `-- name: CreateVendorPerformanceMetric :one
INSERT INTO vendor_performance_metrics (id, vendor_id, metric_name, value, recorded_at)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, vendor_id, metric_name, value, recorded_at
`

type CreateVendorPerformanceMetricParams struct {
	ID         uuid.UUID
	VendorID   uuid.UUID
	MetricName string
	Value      int32
	RecordedAt time.Time
}

func (q *Queries) CreateVendorPerformanceMetric(ctx context.Context, arg CreateVendorPerformanceMetricParams) (VendorPerformanceMetric, error) {
	row := q.db.QueryRowContext(ctx, createVendorPerformanceMetric, arg.ID, arg.VendorID, arg.MetricName, arg.Value, arg.RecordedAt)
	var i VendorPerformanceMetric
	err := row.Scan(&i.ID, &i.VendorID, &i.MetricName, &i.Value, &i.RecordedAt)
	return i, err
}

const getVendorPerformanceMetric = `-- name: GetVendorPerformanceMetric :one
SELECT id, vendor_id, metric_name, value, recorded_at FROM vendor_performance_metrics WHERE id = $1
`

func (q *Queries) GetVendorPerformanceMetric(ctx context.Context, id uuid.UUID) (VendorPerformanceMetric, error) {
	row := q.db.QueryRowContext(ctx, getVendorPerformanceMetric, id)
	var i VendorPerformanceMetric
	err := row.Scan(&i.ID, &i.VendorID, &i.MetricName, &i.Value, &i.RecordedAt)
	return i, err
}

const listVendorPerformanceMetrics = `-- name: ListVendorPerformanceMetrics :many
SELECT id, vendor_id, metric_name, value, recorded_at FROM vendor_performance_metrics ORDER BY recorded_at DESC
`

func (q *Queries) ListVendorPerformanceMetrics(ctx context.Context) ([]VendorPerformanceMetric, error) {
	rows, err := q.db.QueryContext(ctx, listVendorPerformanceMetrics)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []VendorPerformanceMetric
	for rows.Next() {
		var i VendorPerformanceMetric
		if err := rows.Scan(&i.ID, &i.VendorID, &i.MetricName, &i.Value, &i.RecordedAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listVendorPerformanceMetricsByVendorID = `-- name: ListVendorPerformanceMetricsByVendorID :many
SELECT id, vendor_id, metric_name, value, recorded_at FROM vendor_performance_metrics WHERE vendor_id = $1 ORDER BY recorded_at DESC
`

func (q *Queries) ListVendorPerformanceMetricsByVendorID(ctx context.Context, vendorID uuid.UUID) ([]VendorPerformanceMetric, error) {
	rows, err := q.db.QueryContext(ctx, listVendorPerformanceMetricsByVendorID, vendorID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []VendorPerformanceMetric
	for rows.Next() {
		var i VendorPerformanceMetric
		if err := rows.Scan(&i.ID, &i.VendorID, &i.MetricName, &i.Value, &i.RecordedAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const deleteVendorPerformanceMetric = `-- name: DeleteVendorPerformanceMetric :exec
DELETE FROM vendor_performance_metrics WHERE id = $1
`

func (q *Queries) DeleteVendorPerformanceMetric(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, deleteVendorPerformanceMetric, id)
	return err
}
