// Code generated by sqlc. DO NOT EDIT.
package sqlc

import (
	"time"

	"github.com/google/uuid"
)

type Product struct {
	ID        uuid.UUID
	Name      string
	PriceYen  int32
	CreatedAt time.Time
}

type Category struct {
	ID               uuid.UUID
	Name             string
	ParentCategoryID uuid.UUID
	CreatedAt        time.Time
}

type ProductCategory struct {
	ID         uuid.UUID
	ProductID  uuid.UUID
	CategoryID uuid.UUID
	CreatedAt  time.Time
}

type ProductAttribute struct {
	ID        uuid.UUID
	Name      string
	CreatedAt time.Time
}

type ProductAttributeValue struct {
	ID                  uuid.UUID
	ProductID           uuid.UUID
	ProductAttributeID  uuid.UUID
	Value               string
}

type ProductVariant struct {
	ID        uuid.UUID
	ProductID uuid.UUID
	SKU       string
	PriceYen  int32
	CreatedAt time.Time
}

type ProductImage struct {
	ID        uuid.UUID
	ProductID uuid.UUID
	URL       string
	SortOrder int32
}

type Brand struct {
	ID        uuid.UUID
	Name      string
	CreatedAt time.Time
}

type ProductTag struct {
	ID   uuid.UUID
	Name string
}

type ProductTagAssignment struct {
	ID           uuid.UUID
	ProductID    uuid.UUID
	ProductTagID uuid.UUID
}
