// Code generated by sqlc. DO NOT EDIT.
package sqlc

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const createProduct = `-- name: CreateProduct :one
INSERT INTO products (id, name, price_yen, created_at)
VALUES ($1, $2, $3, $4)
RETURNING id, name, price_yen, created_at
`

type CreateProductParams struct {
	ID        uuid.UUID
	Name      string
	PriceYen  int32
	CreatedAt time.Time
}

func (q *Queries) CreateProduct(ctx context.Context, arg CreateProductParams) (Product, error) {
	row := q.db.QueryRowContext(ctx, createProduct, arg.ID, arg.Name, arg.PriceYen, arg.CreatedAt)
	var i Product
	err := row.Scan(&i.ID, &i.Name, &i.PriceYen, &i.CreatedAt)
	return i, err
}

const getProduct = `-- name: GetProduct :one
SELECT id, name, price_yen, created_at FROM products WHERE id = $1
`

func (q *Queries) GetProduct(ctx context.Context, id uuid.UUID) (Product, error) {
	row := q.db.QueryRowContext(ctx, getProduct, id)
	var i Product
	err := row.Scan(&i.ID, &i.Name, &i.PriceYen, &i.CreatedAt)
	return i, err
}

const listProducts = `-- name: ListProducts :many
SELECT id, name, price_yen, created_at FROM products ORDER BY created_at DESC
`

func (q *Queries) ListProducts(ctx context.Context) ([]Product, error) {
	rows, err := q.db.QueryContext(ctx, listProducts)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Product
	for rows.Next() {
		var i Product
		if err := rows.Scan(&i.ID, &i.Name, &i.PriceYen, &i.CreatedAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

// カテゴリ

const createCategory = `-- name: CreateCategory :one
INSERT INTO categories (id, name, parent_category_id, created_at)
VALUES ($1, $2, $3, $4)
RETURNING id, name, parent_category_id, created_at
`

type CreateCategoryParams struct {
	ID               uuid.UUID
	Name             string
	ParentCategoryID uuid.UUID
	CreatedAt        time.Time
}

func (q *Queries) CreateCategory(ctx context.Context, arg CreateCategoryParams) (Category, error) {
	row := q.db.QueryRowContext(ctx, createCategory, arg.ID, arg.Name, arg.ParentCategoryID, arg.CreatedAt)
	var i Category
	err := row.Scan(&i.ID, &i.Name, &i.ParentCategoryID, &i.CreatedAt)
	return i, err
}

const getCategory = `-- name: GetCategory :one
SELECT id, name, parent_category_id, created_at FROM categories WHERE id = $1
`

func (q *Queries) GetCategory(ctx context.Context, id uuid.UUID) (Category, error) {
	row := q.db.QueryRowContext(ctx, getCategory, id)
	var i Category
	err := row.Scan(&i.ID, &i.Name, &i.ParentCategoryID, &i.CreatedAt)
	return i, err
}

const listCategories = `-- name: ListCategories :many
SELECT id, name, parent_category_id, created_at FROM categories ORDER BY created_at DESC
`

func (q *Queries) ListCategories(ctx context.Context) ([]Category, error) {
	rows, err := q.db.QueryContext(ctx, listCategories)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Category
	for rows.Next() {
		var i Category
		if err := rows.Scan(&i.ID, &i.Name, &i.ParentCategoryID, &i.CreatedAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCategoriesByParentCategoryID = `-- name: ListCategoriesByParentCategoryID :many
SELECT id, name, parent_category_id, created_at FROM categories WHERE parent_category_id = $1 ORDER BY created_at DESC
`

func (q *Queries) ListCategoriesByParentCategoryID(ctx context.Context, parentCategoryID uuid.UUID) ([]Category, error) {
	rows, err := q.db.QueryContext(ctx, listCategoriesByParentCategoryID, parentCategoryID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Category
	for rows.Next() {
		var i Category
		if err := rows.Scan(&i.ID, &i.Name, &i.ParentCategoryID, &i.CreatedAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const deleteCategory = `-- name: DeleteCategory :exec
DELETE FROM categories WHERE id = $1
`

func (q *Queries) DeleteCategory(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, deleteCategory, id)
	return err
}

// 商品とカテゴリの中間テーブル

const createProductCategory = `-- name: CreateProductCategory :one
INSERT INTO product_categories (id, product_id, category_id, created_at)
VALUES ($1, $2, $3, $4)
RETURNING id, product_id, category_id, created_at
`

type CreateProductCategoryParams struct {
	ID         uuid.UUID
	ProductID  uuid.UUID
	CategoryID uuid.UUID
	CreatedAt  time.Time
}

func (q *Queries) CreateProductCategory(ctx context.Context, arg CreateProductCategoryParams) (ProductCategory, error) {
	row := q.db.QueryRowContext(ctx, createProductCategory, arg.ID, arg.ProductID, arg.CategoryID, arg.CreatedAt)
	var i ProductCategory
	err := row.Scan(&i.ID, &i.ProductID, &i.CategoryID, &i.CreatedAt)
	return i, err
}

const getProductCategory = `-- name: GetProductCategory :one
SELECT id, product_id, category_id, created_at FROM product_categories WHERE id = $1
`

func (q *Queries) GetProductCategory(ctx context.Context, id uuid.UUID) (ProductCategory, error) {
	row := q.db.QueryRowContext(ctx, getProductCategory, id)
	var i ProductCategory
	err := row.Scan(&i.ID, &i.ProductID, &i.CategoryID, &i.CreatedAt)
	return i, err
}

const listProductCategories = `-- name: ListProductCategories :many
SELECT id, product_id, category_id, created_at FROM product_categories ORDER BY created_at DESC
`

func (q *Queries) ListProductCategories(ctx context.Context) ([]ProductCategory, error) {
	rows, err := q.db.QueryContext(ctx, listProductCategories)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ProductCategory
	for rows.Next() {
		var i ProductCategory
		if err := rows.Scan(&i.ID, &i.ProductID, &i.CategoryID, &i.CreatedAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listProductCategoriesByProductID = `-- name: ListProductCategoriesByProductID :many
SELECT id, product_id, category_id, created_at FROM product_categories WHERE product_id = $1 ORDER BY created_at DESC
`

func (q *Queries) ListProductCategoriesByProductID(ctx context.Context, productID uuid.UUID) ([]ProductCategory, error) {
	rows, err := q.db.QueryContext(ctx, listProductCategoriesByProductID, productID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ProductCategory
	for rows.Next() {
		var i ProductCategory
		if err := rows.Scan(&i.ID, &i.ProductID, &i.CategoryID, &i.CreatedAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listProductCategoriesByCategoryID = `-- name: ListProductCategoriesByCategoryID :many
SELECT id, product_id, category_id, created_at FROM product_categories WHERE category_id = $1 ORDER BY created_at DESC
`

func (q *Queries) ListProductCategoriesByCategoryID(ctx context.Context, categoryID uuid.UUID) ([]ProductCategory, error) {
	rows, err := q.db.QueryContext(ctx, listProductCategoriesByCategoryID, categoryID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ProductCategory
	for rows.Next() {
		var i ProductCategory
		if err := rows.Scan(&i.ID, &i.ProductID, &i.CategoryID, &i.CreatedAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const deleteProductCategory = `-- name: DeleteProductCategory :exec
DELETE FROM product_categories WHERE id = $1
`

func (q *Queries) DeleteProductCategory(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, deleteProductCategory, id)
	return err
}

// 商品属性マスタ

const createProductAttribute = `-- name: CreateProductAttribute :one
INSERT INTO product_attributes (id, name, created_at)
VALUES ($1, $2, $3)
RETURNING id, name, created_at
`

type CreateProductAttributeParams struct {
	ID        uuid.UUID
	Name      string
	CreatedAt time.Time
}

func (q *Queries) CreateProductAttribute(ctx context.Context, arg CreateProductAttributeParams) (ProductAttribute, error) {
	row := q.db.QueryRowContext(ctx, createProductAttribute, arg.ID, arg.Name, arg.CreatedAt)
	var i ProductAttribute
	err := row.Scan(&i.ID, &i.Name, &i.CreatedAt)
	return i, err
}

const getProductAttribute = `-- name: GetProductAttribute :one
SELECT id, name, created_at FROM product_attributes WHERE id = $1
`

func (q *Queries) GetProductAttribute(ctx context.Context, id uuid.UUID) (ProductAttribute, error) {
	row := q.db.QueryRowContext(ctx, getProductAttribute, id)
	var i ProductAttribute
	err := row.Scan(&i.ID, &i.Name, &i.CreatedAt)
	return i, err
}

const listProductAttributes = `-- name: ListProductAttributes :many
SELECT id, name, created_at FROM product_attributes ORDER BY created_at DESC
`

func (q *Queries) ListProductAttributes(ctx context.Context) ([]ProductAttribute, error) {
	rows, err := q.db.QueryContext(ctx, listProductAttributes)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ProductAttribute
	for rows.Next() {
		var i ProductAttribute
		if err := rows.Scan(&i.ID, &i.Name, &i.CreatedAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const deleteProductAttribute = `-- name: DeleteProductAttribute :exec
DELETE FROM product_attributes WHERE id = $1
`

func (q *Queries) DeleteProductAttribute(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, deleteProductAttribute, id)
	return err
}

// 商品属性値

const createProductAttributeValue = `-- name: CreateProductAttributeValue :one
INSERT INTO product_attribute_values (id, product_id, product_attribute_id, value)
VALUES ($1, $2, $3, $4)
RETURNING id, product_id, product_attribute_id, value
`

type CreateProductAttributeValueParams struct {
	ID                 uuid.UUID
	ProductID          uuid.UUID
	ProductAttributeID uuid.UUID
	Value              string
}

func (q *Queries) CreateProductAttributeValue(ctx context.Context, arg CreateProductAttributeValueParams) (ProductAttributeValue, error) {
	row := q.db.QueryRowContext(ctx, createProductAttributeValue, arg.ID, arg.ProductID, arg.ProductAttributeID, arg.Value)
	var i ProductAttributeValue
	err := row.Scan(&i.ID, &i.ProductID, &i.ProductAttributeID, &i.Value)
	return i, err
}

const getProductAttributeValue = `-- name: GetProductAttributeValue :one
SELECT id, product_id, product_attribute_id, value FROM product_attribute_values WHERE id = $1
`

func (q *Queries) GetProductAttributeValue(ctx context.Context, id uuid.UUID) (ProductAttributeValue, error) {
	row := q.db.QueryRowContext(ctx, getProductAttributeValue, id)
	var i ProductAttributeValue
	err := row.Scan(&i.ID, &i.ProductID, &i.ProductAttributeID, &i.Value)
	return i, err
}

const listProductAttributeValues = `-- name: ListProductAttributeValues :many
SELECT id, product_id, product_attribute_id, value FROM product_attribute_values ORDER BY id DESC
`

func (q *Queries) ListProductAttributeValues(ctx context.Context) ([]ProductAttributeValue, error) {
	rows, err := q.db.QueryContext(ctx, listProductAttributeValues)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ProductAttributeValue
	for rows.Next() {
		var i ProductAttributeValue
		if err := rows.Scan(&i.ID, &i.ProductID, &i.ProductAttributeID, &i.Value); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listProductAttributeValuesByProductID = `-- name: ListProductAttributeValuesByProductID :many
SELECT id, product_id, product_attribute_id, value FROM product_attribute_values WHERE product_id = $1 ORDER BY id DESC
`

func (q *Queries) ListProductAttributeValuesByProductID(ctx context.Context, productID uuid.UUID) ([]ProductAttributeValue, error) {
	rows, err := q.db.QueryContext(ctx, listProductAttributeValuesByProductID, productID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ProductAttributeValue
	for rows.Next() {
		var i ProductAttributeValue
		if err := rows.Scan(&i.ID, &i.ProductID, &i.ProductAttributeID, &i.Value); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listProductAttributeValuesByProductAttributeID = `-- name: ListProductAttributeValuesByProductAttributeID :many
SELECT id, product_id, product_attribute_id, value FROM product_attribute_values WHERE product_attribute_id = $1 ORDER BY id DESC
`

func (q *Queries) ListProductAttributeValuesByProductAttributeID(ctx context.Context, productAttributeID uuid.UUID) ([]ProductAttributeValue, error) {
	rows, err := q.db.QueryContext(ctx, listProductAttributeValuesByProductAttributeID, productAttributeID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ProductAttributeValue
	for rows.Next() {
		var i ProductAttributeValue
		if err := rows.Scan(&i.ID, &i.ProductID, &i.ProductAttributeID, &i.Value); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const deleteProductAttributeValue = `-- name: DeleteProductAttributeValue :exec
DELETE FROM product_attribute_values WHERE id = $1
`

func (q *Queries) DeleteProductAttributeValue(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, deleteProductAttributeValue, id)
	return err
}

// 商品バリエーション(SKU)

const createProductVariant = `-- name: CreateProductVariant :one
INSERT INTO product_variants (id, product_id, sku, price_yen, created_at)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, product_id, sku, price_yen, created_at
`

type CreateProductVariantParams struct {
	ID        uuid.UUID
	ProductID uuid.UUID
	SKU       string
	PriceYen  int32
	CreatedAt time.Time
}

func (q *Queries) CreateProductVariant(ctx context.Context, arg CreateProductVariantParams) (ProductVariant, error) {
	row := q.db.QueryRowContext(ctx, createProductVariant, arg.ID, arg.ProductID, arg.SKU, arg.PriceYen, arg.CreatedAt)
	var i ProductVariant
	err := row.Scan(&i.ID, &i.ProductID, &i.SKU, &i.PriceYen, &i.CreatedAt)
	return i, err
}

const getProductVariant = `-- name: GetProductVariant :one
SELECT id, product_id, sku, price_yen, created_at FROM product_variants WHERE id = $1
`

func (q *Queries) GetProductVariant(ctx context.Context, id uuid.UUID) (ProductVariant, error) {
	row := q.db.QueryRowContext(ctx, getProductVariant, id)
	var i ProductVariant
	err := row.Scan(&i.ID, &i.ProductID, &i.SKU, &i.PriceYen, &i.CreatedAt)
	return i, err
}

const listProductVariants = `-- name: ListProductVariants :many
SELECT id, product_id, sku, price_yen, created_at FROM product_variants ORDER BY created_at DESC
`

func (q *Queries) ListProductVariants(ctx context.Context) ([]ProductVariant, error) {
	rows, err := q.db.QueryContext(ctx, listProductVariants)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ProductVariant
	for rows.Next() {
		var i ProductVariant
		if err := rows.Scan(&i.ID, &i.ProductID, &i.SKU, &i.PriceYen, &i.CreatedAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listProductVariantsByProductID = `-- name: ListProductVariantsByProductID :many
SELECT id, product_id, sku, price_yen, created_at FROM product_variants WHERE product_id = $1 ORDER BY created_at DESC
`

func (q *Queries) ListProductVariantsByProductID(ctx context.Context, productID uuid.UUID) ([]ProductVariant, error) {
	rows, err := q.db.QueryContext(ctx, listProductVariantsByProductID, productID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ProductVariant
	for rows.Next() {
		var i ProductVariant
		if err := rows.Scan(&i.ID, &i.ProductID, &i.SKU, &i.PriceYen, &i.CreatedAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const deleteProductVariant = `-- name: DeleteProductVariant :exec
DELETE FROM product_variants WHERE id = $1
`

func (q *Queries) DeleteProductVariant(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, deleteProductVariant, id)
	return err
}

// 商品画像

const createProductImage = `-- name: CreateProductImage :one
INSERT INTO product_images (id, product_id, url, sort_order)
VALUES ($1, $2, $3, $4)
RETURNING id, product_id, url, sort_order
`

type CreateProductImageParams struct {
	ID        uuid.UUID
	ProductID uuid.UUID
	URL       string
	SortOrder int32
}

func (q *Queries) CreateProductImage(ctx context.Context, arg CreateProductImageParams) (ProductImage, error) {
	row := q.db.QueryRowContext(ctx, createProductImage, arg.ID, arg.ProductID, arg.URL, arg.SortOrder)
	var i ProductImage
	err := row.Scan(&i.ID, &i.ProductID, &i.URL, &i.SortOrder)
	return i, err
}

const getProductImage = `-- name: GetProductImage :one
SELECT id, product_id, url, sort_order FROM product_images WHERE id = $1
`

func (q *Queries) GetProductImage(ctx context.Context, id uuid.UUID) (ProductImage, error) {
	row := q.db.QueryRowContext(ctx, getProductImage, id)
	var i ProductImage
	err := row.Scan(&i.ID, &i.ProductID, &i.URL, &i.SortOrder)
	return i, err
}

const listProductImages = `-- name: ListProductImages :many
SELECT id, product_id, url, sort_order FROM product_images ORDER BY id DESC
`

func (q *Queries) ListProductImages(ctx context.Context) ([]ProductImage, error) {
	rows, err := q.db.QueryContext(ctx, listProductImages)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ProductImage
	for rows.Next() {
		var i ProductImage
		if err := rows.Scan(&i.ID, &i.ProductID, &i.URL, &i.SortOrder); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listProductImagesByProductID = `-- name: ListProductImagesByProductID :many
SELECT id, product_id, url, sort_order FROM product_images WHERE product_id = $1 ORDER BY id DESC
`

func (q *Queries) ListProductImagesByProductID(ctx context.Context, productID uuid.UUID) ([]ProductImage, error) {
	rows, err := q.db.QueryContext(ctx, listProductImagesByProductID, productID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ProductImage
	for rows.Next() {
		var i ProductImage
		if err := rows.Scan(&i.ID, &i.ProductID, &i.URL, &i.SortOrder); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const deleteProductImage = `-- name: DeleteProductImage :exec
DELETE FROM product_images WHERE id = $1
`

func (q *Queries) DeleteProductImage(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, deleteProductImage, id)
	return err
}

// ブランド

const createBrand = `-- name: CreateBrand :one
INSERT INTO brands (id, name, created_at)
VALUES ($1, $2, $3)
RETURNING id, name, created_at
`

type CreateBrandParams struct {
	ID        uuid.UUID
	Name      string
	CreatedAt time.Time
}

func (q *Queries) CreateBrand(ctx context.Context, arg CreateBrandParams) (Brand, error) {
	row := q.db.QueryRowContext(ctx, createBrand, arg.ID, arg.Name, arg.CreatedAt)
	var i Brand
	err := row.Scan(&i.ID, &i.Name, &i.CreatedAt)
	return i, err
}

const getBrand = `-- name: GetBrand :one
SELECT id, name, created_at FROM brands WHERE id = $1
`

func (q *Queries) GetBrand(ctx context.Context, id uuid.UUID) (Brand, error) {
	row := q.db.QueryRowContext(ctx, getBrand, id)
	var i Brand
	err := row.Scan(&i.ID, &i.Name, &i.CreatedAt)
	return i, err
}

const listBrands = `-- name: ListBrands :many
SELECT id, name, created_at FROM brands ORDER BY created_at DESC
`

func (q *Queries) ListBrands(ctx context.Context) ([]Brand, error) {
	rows, err := q.db.QueryContext(ctx, listBrands)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Brand
	for rows.Next() {
		var i Brand
		if err := rows.Scan(&i.ID, &i.Name, &i.CreatedAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const deleteBrand = `-- name: DeleteBrand :exec
DELETE FROM brands WHERE id = $1
`

func (q *Queries) DeleteBrand(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, deleteBrand, id)
	return err
}

// 商品タグマスタ

const createProductTag = `-- name: CreateProductTag :one
INSERT INTO product_tags (id, name)
VALUES ($1, $2)
RETURNING id, name
`

type CreateProductTagParams struct {
	ID   uuid.UUID
	Name string
}

func (q *Queries) CreateProductTag(ctx context.Context, arg CreateProductTagParams) (ProductTag, error) {
	row := q.db.QueryRowContext(ctx, createProductTag, arg.ID, arg.Name)
	var i ProductTag
	err := row.Scan(&i.ID, &i.Name)
	return i, err
}

const getProductTag = `-- name: GetProductTag :one
SELECT id, name FROM product_tags WHERE id = $1
`

func (q *Queries) GetProductTag(ctx context.Context, id uuid.UUID) (ProductTag, error) {
	row := q.db.QueryRowContext(ctx, getProductTag, id)
	var i ProductTag
	err := row.Scan(&i.ID, &i.Name)
	return i, err
}

const listProductTags = `-- name: ListProductTags :many
SELECT id, name FROM product_tags ORDER BY id DESC
`

func (q *Queries) ListProductTags(ctx context.Context) ([]ProductTag, error) {
	rows, err := q.db.QueryContext(ctx, listProductTags)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ProductTag
	for rows.Next() {
		var i ProductTag
		if err := rows.Scan(&i.ID, &i.Name); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const deleteProductTag = `-- name: DeleteProductTag :exec
DELETE FROM product_tags WHERE id = $1
`

func (q *Queries) DeleteProductTag(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, deleteProductTag, id)
	return err
}

// 商品とタグの割り当て

const createProductTagAssignment = `-- name: CreateProductTagAssignment :one
INSERT INTO product_tag_assignments (id, product_id, product_tag_id)
VALUES ($1, $2, $3)
RETURNING id, product_id, product_tag_id
`

type CreateProductTagAssignmentParams struct {
	ID           uuid.UUID
	ProductID    uuid.UUID
	ProductTagID uuid.UUID
}

func (q *Queries) CreateProductTagAssignment(ctx context.Context, arg CreateProductTagAssignmentParams) (ProductTagAssignment, error) {
	row := q.db.QueryRowContext(ctx, createProductTagAssignment, arg.ID, arg.ProductID, arg.ProductTagID)
	var i ProductTagAssignment
	err := row.Scan(&i.ID, &i.ProductID, &i.ProductTagID)
	return i, err
}

const getProductTagAssignment = `-- name: GetProductTagAssignment :one
SELECT id, product_id, product_tag_id FROM product_tag_assignments WHERE id = $1
`

func (q *Queries) GetProductTagAssignment(ctx context.Context, id uuid.UUID) (ProductTagAssignment, error) {
	row := q.db.QueryRowContext(ctx, getProductTagAssignment, id)
	var i ProductTagAssignment
	err := row.Scan(&i.ID, &i.ProductID, &i.ProductTagID)
	return i, err
}

const listProductTagAssignments = `-- name: ListProductTagAssignments :many
SELECT id, product_id, product_tag_id FROM product_tag_assignments ORDER BY id DESC
`

func (q *Queries) ListProductTagAssignments(ctx context.Context) ([]ProductTagAssignment, error) {
	rows, err := q.db.QueryContext(ctx, listProductTagAssignments)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ProductTagAssignment
	for rows.Next() {
		var i ProductTagAssignment
		if err := rows.Scan(&i.ID, &i.ProductID, &i.ProductTagID); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listProductTagAssignmentsByProductID = `-- name: ListProductTagAssignmentsByProductID :many
SELECT id, product_id, product_tag_id FROM product_tag_assignments WHERE product_id = $1 ORDER BY id DESC
`

func (q *Queries) ListProductTagAssignmentsByProductID(ctx context.Context, productID uuid.UUID) ([]ProductTagAssignment, error) {
	rows, err := q.db.QueryContext(ctx, listProductTagAssignmentsByProductID, productID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ProductTagAssignment
	for rows.Next() {
		var i ProductTagAssignment
		if err := rows.Scan(&i.ID, &i.ProductID, &i.ProductTagID); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listProductTagAssignmentsByProductTagID = `-- name: ListProductTagAssignmentsByProductTagID :many
SELECT id, product_id, product_tag_id FROM product_tag_assignments WHERE product_tag_id = $1 ORDER BY id DESC
`

func (q *Queries) ListProductTagAssignmentsByProductTagID(ctx context.Context, productTagID uuid.UUID) ([]ProductTagAssignment, error) {
	rows, err := q.db.QueryContext(ctx, listProductTagAssignmentsByProductTagID, productTagID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ProductTagAssignment
	for rows.Next() {
		var i ProductTagAssignment
		if err := rows.Scan(&i.ID, &i.ProductID, &i.ProductTagID); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const deleteProductTagAssignment = `-- name: DeleteProductTagAssignment :exec
DELETE FROM product_tag_assignments WHERE id = $1
`

func (q *Queries) DeleteProductTagAssignment(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, deleteProductTagAssignment, id)
	return err
}

// 集計クエリ

const listProductCountAndAvgPriceByCategory = `-- name: ListProductCountAndAvgPriceByCategory :many
SELECT
    c.id AS category_id,
    c.name AS category_name,
    COUNT(DISTINCT pc.product_id) AS product_count,
    COALESCE(AVG(p.price_yen), 0)::float8 AS avg_price_yen
FROM categories c
JOIN product_categories pc ON pc.category_id = c.id
JOIN products p ON p.id = pc.product_id
GROUP BY c.id, c.name
ORDER BY product_count DESC, c.name
`

type ListProductCountAndAvgPriceByCategoryRow struct {
	CategoryID   uuid.UUID
	CategoryName string
	ProductCount int64
	AvgPriceYen  float64
}

func (q *Queries) ListProductCountAndAvgPriceByCategory(ctx context.Context) ([]ListProductCountAndAvgPriceByCategoryRow, error) {
	rows, err := q.db.QueryContext(ctx, listProductCountAndAvgPriceByCategory)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListProductCountAndAvgPriceByCategoryRow
	for rows.Next() {
		var i ListProductCountAndAvgPriceByCategoryRow
		if err := rows.Scan(&i.CategoryID, &i.CategoryName, &i.ProductCount, &i.AvgPriceYen); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listVariantPriceRangeByProduct = `-- name: ListVariantPriceRangeByProduct :many
SELECT
    p.id AS product_id,
    p.name AS product_name,
    COUNT(pv.id) AS variant_count,
    MIN(pv.price_yen) AS min_price_yen,
    MAX(pv.price_yen) AS max_price_yen
FROM products p
JOIN product_variants pv ON pv.product_id = p.id
GROUP BY p.id, p.name
ORDER BY variant_count DESC, p.name
`

type ListVariantPriceRangeByProductRow struct {
	ProductID    uuid.UUID
	ProductName  string
	VariantCount int64
	MinPriceYen  int32
	MaxPriceYen  int32
}

func (q *Queries) ListVariantPriceRangeByProduct(ctx context.Context) ([]ListVariantPriceRangeByProductRow, error) {
	rows, err := q.db.QueryContext(ctx, listVariantPriceRangeByProduct)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListVariantPriceRangeByProductRow
	for rows.Next() {
		var i ListVariantPriceRangeByProductRow
		if err := rows.Scan(&i.ProductID, &i.ProductName, &i.VariantCount, &i.MinPriceYen, &i.MaxPriceYen); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listProductCountByTag = `-- name: ListProductCountByTag :many
SELECT
    pt.id AS product_tag_id,
    pt.name AS tag_name,
    COUNT(pta.product_id) AS product_count
FROM product_tags pt
JOIN product_tag_assignments pta ON pta.product_tag_id = pt.id
GROUP BY pt.id, pt.name
ORDER BY product_count DESC, pt.name
`

type ListProductCountByTagRow struct {
	ProductTagID uuid.UUID
	TagName      string
	ProductCount int64
}

func (q *Queries) ListProductCountByTag(ctx context.Context) ([]ListProductCountByTagRow, error) {
	rows, err := q.db.QueryContext(ctx, listProductCountByTag)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListProductCountByTagRow
	for rows.Next() {
		var i ListProductCountByTagRow
		if err := rows.Scan(&i.ProductTagID, &i.TagName, &i.ProductCount); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
