// Code generated by sqlc. DO NOT EDIT.
package sqlc

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const createInventory = `-- name: CreateInventory :one
INSERT INTO inventories (id, product_id, quantity, updated_at)
VALUES ($1, $2, $3, $4)
RETURNING id, product_id, quantity, updated_at
`

type CreateInventoryParams struct {
	ID        uuid.UUID
	ProductID uuid.UUID
	Quantity  int32
	UpdatedAt time.Time
}

func (q *Queries) CreateInventory(ctx context.Context, arg CreateInventoryParams) (Inventory, error) {
	row := q.db.QueryRowContext(ctx, createInventory, arg.ID, arg.ProductID, arg.Quantity, arg.UpdatedAt)
	var i Inventory
	err := row.Scan(&i.ID, &i.ProductID, &i.Quantity, &i.UpdatedAt)
	return i, err
}

const getInventory = `-- name: GetInventory :one
SELECT id, product_id, quantity, updated_at FROM inventories WHERE id = $1
`

func (q *Queries) GetInventory(ctx context.Context, id uuid.UUID) (Inventory, error) {
	row := q.db.QueryRowContext(ctx, getInventory, id)
	var i Inventory
	err := row.Scan(&i.ID, &i.ProductID, &i.Quantity, &i.UpdatedAt)
	return i, err
}

const listInventories = `-- name: ListInventories :many
SELECT id, product_id, quantity, updated_at FROM inventories ORDER BY updated_at DESC
`

func (q *Queries) ListInventories(ctx context.Context) ([]Inventory, error) {
	rows, err := q.db.QueryContext(ctx, listInventories)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Inventory
	for rows.Next() {
		var i Inventory
		if err := rows.Scan(&i.ID, &i.ProductID, &i.Quantity, &i.UpdatedAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const createWarehouse = `-- name: CreateWarehouse :one
INSERT INTO warehouses (id, name, address, created_at)
VALUES ($1, $2, $3, $4)
RETURNING id, name, address, created_at
`

type CreateWarehouseParams struct {
	ID        uuid.UUID
	Name      string
	Address   string
	CreatedAt time.Time
}

func (q *Queries) CreateWarehouse(ctx context.Context, arg CreateWarehouseParams) (Warehouse, error) {
	row := q.db.QueryRowContext(ctx, createWarehouse, arg.ID, arg.Name, arg.Address, arg.CreatedAt)
	var i Warehouse
	err := row.Scan(&i.ID, &i.Name, &i.Address, &i.CreatedAt)
	return i, err
}

const getWarehouse = `-- name: GetWarehouse :one
SELECT id, name, address, created_at FROM warehouses WHERE id = $1
`

func (q *Queries) GetWarehouse(ctx context.Context, id uuid.UUID) (Warehouse, error) {
	row := q.db.QueryRowContext(ctx, getWarehouse, id)
	var i Warehouse
	err := row.Scan(&i.ID, &i.Name, &i.Address, &i.CreatedAt)
	return i, err
}

const listWarehouses = `-- name: ListWarehouses :many
SELECT id, name, address, created_at FROM warehouses ORDER BY created_at DESC
`

func (q *Queries) ListWarehouses(ctx context.Context) ([]Warehouse, error) {
	rows, err := q.db.QueryContext(ctx, listWarehouses)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Warehouse
	for rows.Next() {
		var i Warehouse
		if err := rows.Scan(&i.ID, &i.Name, &i.Address, &i.CreatedAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const deleteWarehouse = `-- name: DeleteWarehouse :exec
DELETE FROM warehouses WHERE id = $1
`

func (q *Queries) DeleteWarehouse(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, deleteWarehouse, id)
	return err
}

const createStockMovement = `-- name: CreateStockMovement :one
INSERT INTO stock_movements (id, inventory_id, quantity_delta, reason, created_at)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, inventory_id, quantity_delta, reason, created_at
`

type CreateStockMovementParams struct {
	ID            uuid.UUID
	InventoryID   uuid.UUID
	QuantityDelta int32
	Reason        string
	CreatedAt     time.Time
}

func (q *Queries) CreateStockMovement(ctx context.Context, arg CreateStockMovementParams) (StockMovement, error) {
	row := q.db.QueryRowContext(ctx, createStockMovement, arg.ID, arg.InventoryID, arg.QuantityDelta, arg.Reason, arg.CreatedAt)
	var i StockMovement
	err := row.Scan(&i.ID, &i.InventoryID, &i.QuantityDelta, &i.Reason, &i.CreatedAt)
	return i, err
}

const getStockMovement = `-- name: GetStockMovement :one
SELECT id, inventory_id, quantity_delta, reason, created_at FROM stock_movements WHERE id = $1
`

func (q *Queries) GetStockMovement(ctx context.Context, id uuid.UUID) (StockMovement, error) {
	row := q.db.QueryRowContext(ctx, getStockMovement, id)
	var i StockMovement
	err := row.Scan(&i.ID, &i.InventoryID, &i.QuantityDelta, &i.Reason, &i.CreatedAt)
	return i, err
}

const listStockMovements = `-- name: ListStockMovements :many
SELECT id, inventory_id, quantity_delta, reason, created_at FROM stock_movements ORDER BY created_at DESC
`

func (q *Queries) ListStockMovements(ctx context.Context) ([]StockMovement, error) {
	rows, err := q.db.QueryContext(ctx, listStockMovements)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []StockMovement
	for rows.Next() {
		var i StockMovement
		if err := rows.Scan(&i.ID, &i.InventoryID, &i.QuantityDelta, &i.Reason, &i.CreatedAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listStockMovementsByInventoryID = `-- name: ListStockMovementsByInventoryID :many
SELECT id, inventory_id, quantity_delta, reason, created_at FROM stock_movements WHERE inventory_id = $1 ORDER BY created_at DESC
`

func (q *Queries) ListStockMovementsByInventoryID(ctx context.Context, inventoryID uuid.UUID) ([]StockMovement, error) {
	rows, err := q.db.QueryContext(ctx, listStockMovementsByInventoryID, inventoryID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []StockMovement
	for rows.Next() {
		var i StockMovement
		if err := rows.Scan(&i.ID, &i.InventoryID, &i.QuantityDelta, &i.Reason, &i.CreatedAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const deleteStockMovement = `-- name: DeleteStockMovement :exec
DELETE FROM stock_movements WHERE id = $1
`

func (q *Queries) DeleteStockMovement(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, deleteStockMovement, id)
	return err
}

const createStockReservation = `-- name: CreateStockReservation :one
INSERT INTO stock_reservations (id, inventory_id, order_id, quantity, created_at)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, inventory_id, order_id, quantity, created_at
`

type CreateStockReservationParams struct {
	ID          uuid.UUID
	InventoryID uuid.UUID
	OrderID     uuid.UUID
	Quantity    int32
	CreatedAt   time.Time
}

func (q *Queries) CreateStockReservation(ctx context.Context, arg CreateStockReservationParams) (StockReservation, error) {
	row := q.db.QueryRowContext(ctx, createStockReservation, arg.ID, arg.InventoryID, arg.OrderID, arg.Quantity, arg.CreatedAt)
	var i StockReservation
	err := row.Scan(&i.ID, &i.InventoryID, &i.OrderID, &i.Quantity, &i.CreatedAt)
	return i, err
}

const getStockReservation = `-- name: GetStockReservation :one
SELECT id, inventory_id, order_id, quantity, created_at FROM stock_reservations WHERE id = $1
`

func (q *Queries) GetStockReservation(ctx context.Context, id uuid.UUID) (StockReservation, error) {
	row := q.db.QueryRowContext(ctx, getStockReservation, id)
	var i StockReservation
	err := row.Scan(&i.ID, &i.InventoryID, &i.OrderID, &i.Quantity, &i.CreatedAt)
	return i, err
}

const listStockReservations = `-- name: ListStockReservations :many
SELECT id, inventory_id, order_id, quantity, created_at FROM stock_reservations ORDER BY created_at DESC
`

func (q *Queries) ListStockReservations(ctx context.Context) ([]StockReservation, error) {
	rows, err := q.db.QueryContext(ctx, listStockReservations)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []StockReservation
	for rows.Next() {
		var i StockReservation
		if err := rows.Scan(&i.ID, &i.InventoryID, &i.OrderID, &i.Quantity, &i.CreatedAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listStockReservationsByInventoryID = `-- name: ListStockReservationsByInventoryID :many
SELECT id, inventory_id, order_id, quantity, created_at FROM stock_reservations WHERE inventory_id = $1 ORDER BY created_at DESC
`

func (q *Queries) ListStockReservationsByInventoryID(ctx context.Context, inventoryID uuid.UUID) ([]StockReservation, error) {
	rows, err := q.db.QueryContext(ctx, listStockReservationsByInventoryID, inventoryID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []StockReservation
	for rows.Next() {
		var i StockReservation
		if err := rows.Scan(&i.ID, &i.InventoryID, &i.OrderID, &i.Quantity, &i.CreatedAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listStockReservationsByOrderID = `-- name: ListStockReservationsByOrderID :many
SELECT id, inventory_id, order_id, quantity, created_at FROM stock_reservations WHERE order_id = $1 ORDER BY created_at DESC
`

func (q *Queries) ListStockReservationsByOrderID(ctx context.Context, orderID uuid.UUID) ([]StockReservation, error) {
	rows, err := q.db.QueryContext(ctx, listStockReservationsByOrderID, orderID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []StockReservation
	for rows.Next() {
		var i StockReservation
		if err := rows.Scan(&i.ID, &i.InventoryID, &i.OrderID, &i.Quantity, &i.CreatedAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const deleteStockReservation = `-- name: DeleteStockReservation :exec
DELETE FROM stock_reservations WHERE id = $1
`

func (q *Queries) DeleteStockReservation(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, deleteStockReservation, id)
	return err
}

const createSupplier = `-- name: CreateSupplier :one
INSERT INTO suppliers (id, name, contact_email, created_at)
VALUES ($1, $2, $3, $4)
RETURNING id, name, contact_email, created_at
`

type CreateSupplierParams struct {
	ID           uuid.UUID
	Name         string
	ContactEmail string
	CreatedAt    time.Time
}

func (q *Queries) CreateSupplier(ctx context.Context, arg CreateSupplierParams) (Supplier, error) {
	row := q.db.QueryRowContext(ctx, createSupplier, arg.ID, arg.Name, arg.ContactEmail, arg.CreatedAt)
	var i Supplier
	err := row.Scan(&i.ID, &i.Name, &i.ContactEmail, &i.CreatedAt)
	return i, err
}

const getSupplier = `-- name: GetSupplier :one
SELECT id, name, contact_email, created_at FROM suppliers WHERE id = $1
`

func (q *Queries) GetSupplier(ctx context.Context, id uuid.UUID) (Supplier, error) {
	row := q.db.QueryRowContext(ctx, getSupplier, id)
	var i Supplier
	err := row.Scan(&i.ID, &i.Name, &i.ContactEmail, &i.CreatedAt)
	return i, err
}

const listSuppliers = `-- name: ListSuppliers :many
SELECT id, name, contact_email, created_at FROM suppliers ORDER BY created_at DESC
`

func (q *Queries) ListSuppliers(ctx context.Context) ([]Supplier, error) {
	rows, err := q.db.QueryContext(ctx, listSuppliers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Supplier
	for rows.Next() {
		var i Supplier
		if err := rows.Scan(&i.ID, &i.Name, &i.ContactEmail, &i.CreatedAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const deleteSupplier = `-- name: DeleteSupplier :exec
DELETE FROM suppliers WHERE id = $1
`

func (q *Queries) DeleteSupplier(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, deleteSupplier, id)
	return err
}

const createPurchaseOrder = `-- name: CreatePurchaseOrder :one
INSERT INTO purchase_orders (id, supplier_id, status, created_at)
VALUES ($1, $2, $3, $4)
RETURNING id, supplier_id, status, created_at
`

type CreatePurchaseOrderParams struct {
	ID         uuid.UUID
	SupplierID uuid.UUID
	Status     string
	CreatedAt  time.Time
}

func (q *Queries) CreatePurchaseOrder(ctx context.Context, arg CreatePurchaseOrderParams) (PurchaseOrder, error) {
	row := q.db.QueryRowContext(ctx, createPurchaseOrder, arg.ID, arg.SupplierID, arg.Status, arg.CreatedAt)
	var i PurchaseOrder
	err := row.Scan(&i.ID, &i.SupplierID, &i.Status, &i.CreatedAt)
	return i, err
}

const getPurchaseOrder = `-- name: GetPurchaseOrder :one
SELECT id, supplier_id, status, created_at FROM purchase_orders WHERE id = $1
`

func (q *Queries) GetPurchaseOrder(ctx context.Context, id uuid.UUID) (PurchaseOrder, error) {
	row := q.db.QueryRowContext(ctx, getPurchaseOrder, id)
	var i PurchaseOrder
	err := row.Scan(&i.ID, &i.SupplierID, &i.Status, &i.CreatedAt)
	return i, err
}

const listPurchaseOrders = `-- name: ListPurchaseOrders :many
SELECT id, supplier_id, status, created_at FROM purchase_orders ORDER BY created_at DESC
`

func (q *Queries) ListPurchaseOrders(ctx context.Context) ([]PurchaseOrder, error) {
	rows, err := q.db.QueryContext(ctx, listPurchaseOrders)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []PurchaseOrder
	for rows.Next() {
		var i PurchaseOrder
		if err := rows.Scan(&i.ID, &i.SupplierID, &i.Status, &i.CreatedAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPurchaseOrdersBySupplierID = `-- name: ListPurchaseOrdersBySupplierID :many
SELECT id, supplier_id, status, created_at FROM purchase_orders WHERE supplier_id = $1 ORDER BY created_at DESC
`

func (q *Queries) ListPurchaseOrdersBySupplierID(ctx context.Context, supplierID uuid.UUID) ([]PurchaseOrder, error) {
	rows, err := q.db.QueryContext(ctx, listPurchaseOrdersBySupplierID, supplierID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []PurchaseOrder
	for rows.Next() {
		var i PurchaseOrder
		if err := rows.Scan(&i.ID, &i.SupplierID, &i.Status, &i.CreatedAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const deletePurchaseOrder = `-- name: DeletePurchaseOrder :exec
DELETE FROM purchase_orders WHERE id = $1
`

func (q *Queries) DeletePurchaseOrder(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, deletePurchaseOrder, id)
	return err
}

const createPurchaseOrderItem = `-- name: CreatePurchaseOrderItem :one
INSERT INTO purchase_order_items (id, purchase_order_id, product_id, quantity, unit_price_yen)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, purchase_order_id, product_id, quantity, unit_price_yen
`

type CreatePurchaseOrderItemParams struct {
	ID              uuid.UUID
	PurchaseOrderID uuid.UUID
	ProductID       uuid.UUID
	Quantity        int32
	UnitPriceYen    int32
}

func (q *Queries) CreatePurchaseOrderItem(ctx context.Context, arg CreatePurchaseOrderItemParams) (PurchaseOrderItem, error) {
	row := q.db.QueryRowContext(ctx, createPurchaseOrderItem, arg.ID, arg.PurchaseOrderID, arg.ProductID, arg.Quantity, arg.UnitPriceYen)
	var i PurchaseOrderItem
	err := row.Scan(&i.ID, &i.PurchaseOrderID, &i.ProductID, &i.Quantity, &i.UnitPriceYen)
	return i, err
}

const getPurchaseOrderItem = `-- name: GetPurchaseOrderItem :one
SELECT id, purchase_order_id, product_id, quantity, unit_price_yen FROM purchase_order_items WHERE id = $1
`

func (q *Queries) GetPurchaseOrderItem(ctx context.Context, id uuid.UUID) (PurchaseOrderItem, error) {
	row := q.db.QueryRowContext(ctx, getPurchaseOrderItem, id)
	var i PurchaseOrderItem
	err := row.Scan(&i.ID, &i.PurchaseOrderID, &i.ProductID, &i.Quantity, &i.UnitPriceYen)
	return i, err
}

const listPurchaseOrderItems = `-- name: ListPurchaseOrderItems :many
SELECT id, purchase_order_id, product_id, quantity, unit_price_yen FROM purchase_order_items ORDER BY id DESC
`

func (q *Queries) ListPurchaseOrderItems(ctx context.Context) ([]PurchaseOrderItem, error) {
	rows, err := q.db.QueryContext(ctx, listPurchaseOrderItems)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []PurchaseOrderItem
	for rows.Next() {
		var i PurchaseOrderItem
		if err := rows.Scan(&i.ID, &i.PurchaseOrderID, &i.ProductID, &i.Quantity, &i.UnitPriceYen); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPurchaseOrderItemsByPurchaseOrderID = `-- name: ListPurchaseOrderItemsByPurchaseOrderID :many
SELECT id, purchase_order_id, product_id, quantity, unit_price_yen FROM purchase_order_items WHERE purchase_order_id = $1 ORDER BY id DESC
`

func (q *Queries) ListPurchaseOrderItemsByPurchaseOrderID(ctx context.Context, purchaseOrderID uuid.UUID) ([]PurchaseOrderItem, error) {
	rows, err := q.db.QueryContext(ctx, listPurchaseOrderItemsByPurchaseOrderID, purchaseOrderID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []PurchaseOrderItem
	for rows.Next() {
		var i PurchaseOrderItem
		if err := rows.Scan(&i.ID, &i.PurchaseOrderID, &i.ProductID, &i.Quantity, &i.UnitPriceYen); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPurchaseOrderItemsByProductID = `-- name: ListPurchaseOrderItemsByProductID :many
SELECT id, purchase_order_id, product_id, quantity, unit_price_yen FROM purchase_order_items WHERE product_id = $1 ORDER BY id DESC
`

func (q *Queries) ListPurchaseOrderItemsByProductID(ctx context.Context, productID uuid.UUID) ([]PurchaseOrderItem, error) {
	rows, err := q.db.QueryContext(ctx, listPurchaseOrderItemsByProductID, productID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []PurchaseOrderItem
	for rows.Next() {
		var i PurchaseOrderItem
		if err := rows.Scan(&i.ID, &i.PurchaseOrderID, &i.ProductID, &i.Quantity, &i.UnitPriceYen); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const deletePurchaseOrderItem = `-- name: DeletePurchaseOrderItem :exec
DELETE FROM purchase_order_items WHERE id = $1
`

func (q *Queries) DeletePurchaseOrderItem(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, deletePurchaseOrderItem, id)
	return err
}

const createSupplierProduct = `-- name: CreateSupplierProduct :one
INSERT INTO supplier_products (id, supplier_id, product_id, lead_time_days)
VALUES ($1, $2, $3, $4)
RETURNING id, supplier_id, product_id, lead_time_days
`

type CreateSupplierProductParams struct {
	ID           uuid.UUID
	SupplierID   uuid.UUID
	ProductID    uuid.UUID
	LeadTimeDays int32
}

func (q *Queries) CreateSupplierProduct(ctx context.Context, arg CreateSupplierProductParams) (SupplierProduct, error) {
	row := q.db.QueryRowContext(ctx, createSupplierProduct, arg.ID, arg.SupplierID, arg.ProductID, arg.LeadTimeDays)
	var i SupplierProduct
	err := row.Scan(&i.ID, &i.SupplierID, &i.ProductID, &i.LeadTimeDays)
	return i, err
}

const getSupplierProduct = `-- name: GetSupplierProduct :one
SELECT id, supplier_id, product_id, lead_time_days FROM supplier_products WHERE id = $1
`

func (q *Queries) GetSupplierProduct(ctx context.Context, id uuid.UUID) (SupplierProduct, error) {
	row := q.db.QueryRowContext(ctx, getSupplierProduct, id)
	var i SupplierProduct
	err := row.Scan(&i.ID, &i.SupplierID, &i.ProductID, &i.LeadTimeDays)
	return i, err
}

const listSupplierProducts = `-- name: ListSupplierProducts :many
SELECT id, supplier_id, product_id, lead_time_days FROM supplier_products ORDER BY id DESC
`

func (q *Queries) ListSupplierProducts(ctx context.Context) ([]SupplierProduct, error) {
	rows, err := q.db.QueryContext(ctx, listSupplierProducts)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SupplierProduct
	for rows.Next() {
		var i SupplierProduct
		if err := rows.Scan(&i.ID, &i.SupplierID, &i.ProductID, &i.LeadTimeDays); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSupplierProductsBySupplierID = `-- name: ListSupplierProductsBySupplierID :many
SELECT id, supplier_id, product_id, lead_time_days FROM supplier_products WHERE supplier_id = $1 ORDER BY id DESC
`

func (q *Queries) ListSupplierProductsBySupplierID(ctx context.Context, supplierID uuid.UUID) ([]SupplierProduct, error) {
	rows, err := q.db.QueryContext(ctx, listSupplierProductsBySupplierID, supplierID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SupplierProduct
	for rows.Next() {
		var i SupplierProduct
		if err := rows.Scan(&i.ID, &i.SupplierID, &i.ProductID, &i.LeadTimeDays); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSupplierProductsByProductID = `-- name: ListSupplierProductsByProductID :many
SELECT id, supplier_id, product_id, lead_time_days FROM supplier_products WHERE product_id = $1 ORDER BY id DESC
`

func (q *Queries) ListSupplierProductsByProductID(ctx context.Context, productID uuid.UUID) ([]SupplierProduct, error) {
	rows, err := q.db.QueryContext(ctx, listSupplierProductsByProductID, productID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SupplierProduct
	for rows.Next() {
		var i SupplierProduct
		if err := rows.Scan(&i.ID, &i.SupplierID, &i.ProductID, &i.LeadTimeDays); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const deleteSupplierProduct = `-- name: DeleteSupplierProduct :exec
DELETE FROM supplier_products WHERE id = $1
`

func (q *Queries) DeleteSupplierProduct(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, deleteSupplierProduct, id)
	return err
}

const createStockAdjustment = `-- name: CreateStockAdjustment :one
INSERT INTO stock_adjustments (id, inventory_id, adjusted_quantity, note, created_at)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, inventory_id, adjusted_quantity, note, created_at
`

type CreateStockAdjustmentParams struct {
	ID               uuid.UUID
	InventoryID      uuid.UUID
	AdjustedQuantity int32
	Note             string
	CreatedAt        time.Time
}

func (q *Queries) CreateStockAdjustment(ctx context.Context, arg CreateStockAdjustmentParams) (StockAdjustment, error) {
	row := q.db.QueryRowContext(ctx, createStockAdjustment, arg.ID, arg.InventoryID, arg.AdjustedQuantity, arg.Note, arg.CreatedAt)
	var i StockAdjustment
	err := row.Scan(&i.ID, &i.InventoryID, &i.AdjustedQuantity, &i.Note, &i.CreatedAt)
	return i, err
}

const getStockAdjustment = `-- name: GetStockAdjustment :one
SELECT id, inventory_id, adjusted_quantity, note, created_at FROM stock_adjustments WHERE id = $1
`

func (q *Queries) GetStockAdjustment(ctx context.Context, id uuid.UUID) (StockAdjustment, error) {
	row := q.db.QueryRowContext(ctx, getStockAdjustment, id)
	var i StockAdjustment
	err := row.Scan(&i.ID, &i.InventoryID, &i.AdjustedQuantity, &i.Note, &i.CreatedAt)
	return i, err
}

const listStockAdjustments = `-- name: ListStockAdjustments :many
SELECT id, inventory_id, adjusted_quantity, note, created_at FROM stock_adjustments ORDER BY created_at DESC
`

func (q *Queries) ListStockAdjustments(ctx context.Context) ([]StockAdjustment, error) {
	rows, err := q.db.QueryContext(ctx, listStockAdjustments)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []StockAdjustment
	for rows.Next() {
		var i StockAdjustment
		if err := rows.Scan(&i.ID, &i.InventoryID, &i.AdjustedQuantity, &i.Note, &i.CreatedAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listStockAdjustmentsByInventoryID = `-- name: ListStockAdjustmentsByInventoryID :many
SELECT id, inventory_id, adjusted_quantity, note, created_at FROM stock_adjustments WHERE inventory_id = $1 ORDER BY created_at DESC
`

func (q *Queries) ListStockAdjustmentsByInventoryID(ctx context.Context, inventoryID uuid.UUID) ([]StockAdjustment, error) {
	rows, err := q.db.QueryContext(ctx, listStockAdjustmentsByInventoryID, inventoryID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []StockAdjustment
	for rows.Next() {
		var i StockAdjustment
		if err := rows.Scan(&i.ID, &i.InventoryID, &i.AdjustedQuantity, &i.Note, &i.CreatedAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const deleteStockAdjustment = `-- name: DeleteStockAdjustment :exec
DELETE FROM stock_adjustments WHERE id = $1
`

func (q *Queries) DeleteStockAdjustment(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, deleteStockAdjustment, id)
	return err
}

const createInventoryAudit = `-- name: CreateInventoryAudit :one
INSERT INTO inventory_audits (id, warehouse_id, performed_at, result)
VALUES ($1, $2, $3, $4)
RETURNING id, warehouse_id, performed_at, result
`

type CreateInventoryAuditParams struct {
	ID          uuid.UUID
	WarehouseID uuid.UUID
	PerformedAt time.Time
	Result      string
}

func (q *Queries) CreateInventoryAudit(ctx context.Context, arg CreateInventoryAuditParams) (InventoryAudit, error) {
	row := q.db.QueryRowContext(ctx, createInventoryAudit, arg.ID, arg.WarehouseID, arg.PerformedAt, arg.Result)
	var i InventoryAudit
	err := row.Scan(&i.ID, &i.WarehouseID, &i.PerformedAt, &i.Result)
	return i, err
}

const getInventoryAudit = `-- name: GetInventoryAudit :one
SELECT id, warehouse_id, performed_at, result FROM inventory_audits WHERE id = $1
`

func (q *Queries) GetInventoryAudit(ctx context.Context, id uuid.UUID) (InventoryAudit, error) {
	row := q.db.QueryRowContext(ctx, getInventoryAudit, id)
	var i InventoryAudit
	err := row.Scan(&i.ID, &i.WarehouseID, &i.PerformedAt, &i.Result)
	return i, err
}

const listInventoryAudits = `-- name: ListInventoryAudits :many
SELECT id, warehouse_id, performed_at, result FROM inventory_audits ORDER BY performed_at DESC
`

func (q *Queries) ListInventoryAudits(ctx context.Context) ([]InventoryAudit, error) {
	rows, err := q.db.QueryContext(ctx, listInventoryAudits)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []InventoryAudit
	for rows.Next() {
		var i InventoryAudit
		if err := rows.Scan(&i.ID, &i.WarehouseID, &i.PerformedAt, &i.Result); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listInventoryAuditsByWarehouseID = `-- name: ListInventoryAuditsByWarehouseID :many
SELECT id, warehouse_id, performed_at, result FROM inventory_audits WHERE warehouse_id = $1 ORDER BY performed_at DESC
`

func (q *Queries) ListInventoryAuditsByWarehouseID(ctx context.Context, warehouseID uuid.UUID) ([]InventoryAudit, error) {
	rows, err := q.db.QueryContext(ctx, listInventoryAuditsByWarehouseID, warehouseID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []InventoryAudit
	for rows.Next() {
		var i InventoryAudit
		if err := rows.Scan(&i.ID, &i.WarehouseID, &i.PerformedAt, &i.Result); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const deleteInventoryAudit = `-- name: DeleteInventoryAudit :exec
DELETE FROM inventory_audits WHERE id = $1
`

func (q *Queries) DeleteInventoryAudit(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, deleteInventoryAudit, id)
	return err
}
