// Code generated by sqlc. DO NOT EDIT.
package sqlc

import (
	"time"

	"github.com/google/uuid"
)

type Inventory struct {
	ID        uuid.UUID
	ProductID uuid.UUID
	Quantity  int32
	UpdatedAt time.Time
}

type Warehouse struct {
	ID        uuid.UUID
	Name      string
	Address   string
	CreatedAt time.Time
}

type StockMovement struct {
	ID            uuid.UUID
	InventoryID   uuid.UUID
	QuantityDelta int32
	Reason        string
	CreatedAt     time.Time
}

type StockReservation struct {
	ID          uuid.UUID
	InventoryID uuid.UUID
	OrderID     uuid.UUID
	Quantity    int32
	CreatedAt   time.Time
}

type Supplier struct {
	ID           uuid.UUID
	Name         string
	ContactEmail string
	CreatedAt    time.Time
}

type PurchaseOrder struct {
	ID         uuid.UUID
	SupplierID uuid.UUID
	Status     string
	CreatedAt  time.Time
}

type PurchaseOrderItem struct {
	ID              uuid.UUID
	PurchaseOrderID uuid.UUID
	ProductID       uuid.UUID
	Quantity        int32
	UnitPriceYen    int32
}

type SupplierProduct struct {
	ID           uuid.UUID
	SupplierID   uuid.UUID
	ProductID    uuid.UUID
	LeadTimeDays int32
}

type StockAdjustment struct {
	ID               uuid.UUID
	InventoryID      uuid.UUID
	AdjustedQuantity int32
	Note             string
	CreatedAt        time.Time
}

type InventoryAudit struct {
	ID          uuid.UUID
	WarehouseID uuid.UUID
	PerformedAt time.Time
	Result      string
}
