// Code generated by sqlc. DO NOT EDIT.
package sqlc

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const createBanner = `-- name: CreateBanner :one
INSERT INTO banners (id, title, image_url, starts_at, ends_at)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, title, image_url, starts_at, ends_at
`

type CreateBannerParams struct {
	ID       uuid.UUID
	Title    string
	ImageUrl string
	StartsAt time.Time
	EndsAt   time.Time
}

func (q *Queries) CreateBanner(ctx context.Context, arg CreateBannerParams) (Banner, error) {
	row := q.db.QueryRowContext(ctx, createBanner, arg.ID, arg.Title, arg.ImageUrl, arg.StartsAt, arg.EndsAt)
	var i Banner
	err := row.Scan(&i.ID, &i.Title, &i.ImageUrl, &i.StartsAt, &i.EndsAt)
	return i, err
}

const getBanner = `-- name: GetBanner :one
SELECT id, title, image_url, starts_at, ends_at FROM banners WHERE id = $1
`

func (q *Queries) GetBanner(ctx context.Context, id uuid.UUID) (Banner, error) {
	row := q.db.QueryRowContext(ctx, getBanner, id)
	var i Banner
	err := row.Scan(&i.ID, &i.Title, &i.ImageUrl, &i.StartsAt, &i.EndsAt)
	return i, err
}

const listBanners = `-- name: ListBanners :many
SELECT id, title, image_url, starts_at, ends_at FROM banners ORDER BY id DESC
`

func (q *Queries) ListBanners(ctx context.Context) ([]Banner, error) {
	rows, err := q.db.QueryContext(ctx, listBanners)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Banner
	for rows.Next() {
		var i Banner
		if err := rows.Scan(&i.ID, &i.Title, &i.ImageUrl, &i.StartsAt, &i.EndsAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const deleteBanner = `-- name: DeleteBanner :exec
DELETE FROM banners WHERE id = $1
`

func (q *Queries) DeleteBanner(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, deleteBanner, id)
	return err
}

const createPage = `-- name: CreatePage :one
INSERT INTO pages (id, slug, title, body)
VALUES ($1, $2, $3, $4)
RETURNING id, slug, title, body
`

type CreatePageParams struct {
	ID    uuid.UUID
	Slug  string
	Title string
	Body  string
}

func (q *Queries) CreatePage(ctx context.Context, arg CreatePageParams) (Page, error) {
	row := q.db.QueryRowContext(ctx, createPage, arg.ID, arg.Slug, arg.Title, arg.Body)
	var i Page
	err := row.Scan(&i.ID, &i.Slug, &i.Title, &i.Body)
	return i, err
}

const getPage = `-- name: GetPage :one
SELECT id, slug, title, body FROM pages WHERE id = $1
`

func (q *Queries) GetPage(ctx context.Context, id uuid.UUID) (Page, error) {
	row := q.db.QueryRowContext(ctx, getPage, id)
	var i Page
	err := row.Scan(&i.ID, &i.Slug, &i.Title, &i.Body)
	return i, err
}

const listPages = `-- name: ListPages :many
SELECT id, slug, title, body FROM pages ORDER BY id DESC
`

func (q *Queries) ListPages(ctx context.Context) ([]Page, error) {
	rows, err := q.db.QueryContext(ctx, listPages)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Page
	for rows.Next() {
		var i Page
		if err := rows.Scan(&i.ID, &i.Slug, &i.Title, &i.Body); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const deletePage = `-- name: DeletePage :exec
DELETE FROM pages WHERE id = $1
`

func (q *Queries) DeletePage(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, deletePage, id)
	return err
}

const createBlogPost = `-- name: CreateBlogPost :one
INSERT INTO blog_posts (id, title, body, published_at)
VALUES ($1, $2, $3, $4)
RETURNING id, title, body, published_at
`

type CreateBlogPostParams struct {
	ID          uuid.UUID
	Title       string
	Body        string
	PublishedAt time.Time
}

func (q *Queries) CreateBlogPost(ctx context.Context, arg CreateBlogPostParams) (BlogPost, error) {
	row := q.db.QueryRowContext(ctx, createBlogPost, arg.ID, arg.Title, arg.Body, arg.PublishedAt)
	var i BlogPost
	err := row.Scan(&i.ID, &i.Title, &i.Body, &i.PublishedAt)
	return i, err
}

const getBlogPost = `-- name: GetBlogPost :one
SELECT id, title, body, published_at FROM blog_posts WHERE id = $1
`

func (q *Queries) GetBlogPost(ctx context.Context, id uuid.UUID) (BlogPost, error) {
	row := q.db.QueryRowContext(ctx, getBlogPost, id)
	var i BlogPost
	err := row.Scan(&i.ID, &i.Title, &i.Body, &i.PublishedAt)
	return i, err
}

const listBlogPosts = `-- name: ListBlogPosts :many
SELECT id, title, body, published_at FROM blog_posts ORDER BY id DESC
`

func (q *Queries) ListBlogPosts(ctx context.Context) ([]BlogPost, error) {
	rows, err := q.db.QueryContext(ctx, listBlogPosts)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []BlogPost
	for rows.Next() {
		var i BlogPost
		if err := rows.Scan(&i.ID, &i.Title, &i.Body, &i.PublishedAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const deleteBlogPost = `-- name: DeleteBlogPost :exec
DELETE FROM blog_posts WHERE id = $1
`

func (q *Queries) DeleteBlogPost(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, deleteBlogPost, id)
	return err
}

const createBlogCategory = `-- name: CreateBlogCategory :one
INSERT INTO blog_categories (id, name)
VALUES ($1, $2)
RETURNING id, name
`

type CreateBlogCategoryParams struct {
	ID   uuid.UUID
	Name string
}

func (q *Queries) CreateBlogCategory(ctx context.Context, arg CreateBlogCategoryParams) (BlogCategory, error) {
	row := q.db.QueryRowContext(ctx, createBlogCategory, arg.ID, arg.Name)
	var i BlogCategory
	err := row.Scan(&i.ID, &i.Name)
	return i, err
}

const getBlogCategory = `-- name: GetBlogCategory :one
SELECT id, name FROM blog_categories WHERE id = $1
`

func (q *Queries) GetBlogCategory(ctx context.Context, id uuid.UUID) (BlogCategory, error) {
	row := q.db.QueryRowContext(ctx, getBlogCategory, id)
	var i BlogCategory
	err := row.Scan(&i.ID, &i.Name)
	return i, err
}

const listBlogCategories = `-- name: ListBlogCategories :many
SELECT id, name FROM blog_categories ORDER BY id DESC
`

func (q *Queries) ListBlogCategories(ctx context.Context) ([]BlogCategory, error) {
	rows, err := q.db.QueryContext(ctx, listBlogCategories)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []BlogCategory
	for rows.Next() {
		var i BlogCategory
		if err := rows.Scan(&i.ID, &i.Name); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const deleteBlogCategory = `-- name: DeleteBlogCategory :exec
DELETE FROM blog_categories WHERE id = $1
`

func (q *Queries) DeleteBlogCategory(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, deleteBlogCategory, id)
	return err
}

const createBlogPostTag = `-- name: CreateBlogPostTag :one
INSERT INTO blog_post_tags (id, blog_post_id, tag)
VALUES ($1, $2, $3)
RETURNING id, blog_post_id, tag
`

type CreateBlogPostTagParams struct {
	ID         uuid.UUID
	BlogPostID uuid.UUID
	Tag        string
}

func (q *Queries) CreateBlogPostTag(ctx context.Context, arg CreateBlogPostTagParams) (BlogPostTag, error) {
	row := q.db.QueryRowContext(ctx, createBlogPostTag, arg.ID, arg.BlogPostID, arg.Tag)
	var i BlogPostTag
	err := row.Scan(&i.ID, &i.BlogPostID, &i.Tag)
	return i, err
}

const getBlogPostTag = `-- name: GetBlogPostTag :one
SELECT id, blog_post_id, tag FROM blog_post_tags WHERE id = $1
`

func (q *Queries) GetBlogPostTag(ctx context.Context, id uuid.UUID) (BlogPostTag, error) {
	row := q.db.QueryRowContext(ctx, getBlogPostTag, id)
	var i BlogPostTag
	err := row.Scan(&i.ID, &i.BlogPostID, &i.Tag)
	return i, err
}

const listBlogPostTags = `-- name: ListBlogPostTags :many
SELECT id, blog_post_id, tag FROM blog_post_tags ORDER BY id DESC
`

func (q *Queries) ListBlogPostTags(ctx context.Context) ([]BlogPostTag, error) {
	rows, err := q.db.QueryContext(ctx, listBlogPostTags)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []BlogPostTag
	for rows.Next() {
		var i BlogPostTag
		if err := rows.Scan(&i.ID, &i.BlogPostID, &i.Tag); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listBlogPostTagsByBlogPostID = `-- name: ListBlogPostTagsByBlogPostID :many
SELECT id, blog_post_id, tag FROM blog_post_tags WHERE blog_post_id = $1 ORDER BY id DESC
`

func (q *Queries) ListBlogPostTagsByBlogPostID(ctx context.Context, blogPostID uuid.UUID) ([]BlogPostTag, error) {
	rows, err := q.db.QueryContext(ctx, listBlogPostTagsByBlogPostID, blogPostID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []BlogPostTag
	for rows.Next() {
		var i BlogPostTag
		if err := rows.Scan(&i.ID, &i.BlogPostID, &i.Tag); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const deleteBlogPostTag = `-- name: DeleteBlogPostTag :exec
DELETE FROM blog_post_tags WHERE id = $1
`

func (q *Queries) DeleteBlogPostTag(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, deleteBlogPostTag, id)
	return err
}

const createMediaAsset = `-- name: CreateMediaAsset :one
INSERT INTO media_assets (id, url, media_type, created_at)
VALUES ($1, $2, $3, $4)
RETURNING id, url, media_type, created_at
`

type CreateMediaAssetParams struct {
	ID        uuid.UUID
	Url       string
	MediaType string
	CreatedAt time.Time
}

func (q *Queries) CreateMediaAsset(ctx context.Context, arg CreateMediaAssetParams) (MediaAsset, error) {
	row := q.db.QueryRowContext(ctx, createMediaAsset, arg.ID, arg.Url, arg.MediaType, arg.CreatedAt)
	var i MediaAsset
	err := row.Scan(&i.ID, &i.Url, &i.MediaType, &i.CreatedAt)
	return i, err
}

const getMediaAsset = `-- name: GetMediaAsset :one
SELECT id, url, media_type, created_at FROM media_assets WHERE id = $1
`

func (q *Queries) GetMediaAsset(ctx context.Context, id uuid.UUID) (MediaAsset, error) {
	row := q.db.QueryRowContext(ctx, getMediaAsset, id)
	var i MediaAsset
	err := row.Scan(&i.ID, &i.Url, &i.MediaType, &i.CreatedAt)
	return i, err
}

const listMediaAssets = `-- name: ListMediaAssets :many
SELECT id, url, media_type, created_at FROM media_assets ORDER BY created_at DESC
`

func (q *Queries) ListMediaAssets(ctx context.Context) ([]MediaAsset, error) {
	rows, err := q.db.QueryContext(ctx, listMediaAssets)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []MediaAsset
	for rows.Next() {
		var i MediaAsset
		if err := rows.Scan(&i.ID, &i.Url, &i.MediaType, &i.CreatedAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const deleteMediaAsset = `-- name: DeleteMediaAsset :exec
DELETE FROM media_assets WHERE id = $1
`

func (q *Queries) DeleteMediaAsset(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, deleteMediaAsset, id)
	return err
}

const createSiteSetting = `-- name: CreateSiteSetting :one
INSERT INTO site_settings (id, setting_key, setting_value)
VALUES ($1, $2, $3)
RETURNING id, setting_key, setting_value
`

type CreateSiteSettingParams struct {
	ID           uuid.UUID
	SettingKey   string
	SettingValue string
}

func (q *Queries) CreateSiteSetting(ctx context.Context, arg CreateSiteSettingParams) (SiteSetting, error) {
	row := q.db.QueryRowContext(ctx, createSiteSetting, arg.ID, arg.SettingKey, arg.SettingValue)
	var i SiteSetting
	err := row.Scan(&i.ID, &i.SettingKey, &i.SettingValue)
	return i, err
}

const getSiteSetting = `-- name: GetSiteSetting :one
SELECT id, setting_key, setting_value FROM site_settings WHERE id = $1
`

func (q *Queries) GetSiteSetting(ctx context.Context, id uuid.UUID) (SiteSetting, error) {
	row := q.db.QueryRowContext(ctx, getSiteSetting, id)
	var i SiteSetting
	err := row.Scan(&i.ID, &i.SettingKey, &i.SettingValue)
	return i, err
}

const listSiteSettings = `-- name: ListSiteSettings :many
SELECT id, setting_key, setting_value FROM site_settings ORDER BY id DESC
`

func (q *Queries) ListSiteSettings(ctx context.Context) ([]SiteSetting, error) {
	rows, err := q.db.QueryContext(ctx, listSiteSettings)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SiteSetting
	for rows.Next() {
		var i SiteSetting
		if err := rows.Scan(&i.ID, &i.SettingKey, &i.SettingValue); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const deleteSiteSetting = `-- name: DeleteSiteSetting :exec
DELETE FROM site_settings WHERE id = $1
`

func (q *Queries) DeleteSiteSetting(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, deleteSiteSetting, id)
	return err
}

const createMenu = `-- name: CreateMenu :one
INSERT INTO menus (id, name)
VALUES ($1, $2)
RETURNING id, name
`

type CreateMenuParams struct {
	ID   uuid.UUID
	Name string
}

func (q *Queries) CreateMenu(ctx context.Context, arg CreateMenuParams) (Menu, error) {
	row := q.db.QueryRowContext(ctx, createMenu, arg.ID, arg.Name)
	var i Menu
	err := row.Scan(&i.ID, &i.Name)
	return i, err
}

const getMenu = `-- name: GetMenu :one
SELECT id, name FROM menus WHERE id = $1
`

func (q *Queries) GetMenu(ctx context.Context, id uuid.UUID) (Menu, error) {
	row := q.db.QueryRowContext(ctx, getMenu, id)
	var i Menu
	err := row.Scan(&i.ID, &i.Name)
	return i, err
}

const listMenus = `-- name: ListMenus :many
SELECT id, name FROM menus ORDER BY id DESC
`

func (q *Queries) ListMenus(ctx context.Context) ([]Menu, error) {
	rows, err := q.db.QueryContext(ctx, listMenus)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Menu
	for rows.Next() {
		var i Menu
		if err := rows.Scan(&i.ID, &i.Name); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const deleteMenu = `-- name: DeleteMenu :exec
DELETE FROM menus WHERE id = $1
`

func (q *Queries) DeleteMenu(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, deleteMenu, id)
	return err
}

const createMenuItem = `-- name: CreateMenuItem :one
INSERT INTO menu_items (id, menu_id, label, url, sort_order)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, menu_id, label, url, sort_order
`

type CreateMenuItemParams struct {
	ID        uuid.UUID
	MenuID    uuid.UUID
	Label     string
	Url       string
	SortOrder int32
}

func (q *Queries) CreateMenuItem(ctx context.Context, arg CreateMenuItemParams) (MenuItem, error) {
	row := q.db.QueryRowContext(ctx, createMenuItem, arg.ID, arg.MenuID, arg.Label, arg.Url, arg.SortOrder)
	var i MenuItem
	err := row.Scan(&i.ID, &i.MenuID, &i.Label, &i.Url, &i.SortOrder)
	return i, err
}

const getMenuItem = `-- name: GetMenuItem :one
SELECT id, menu_id, label, url, sort_order FROM menu_items WHERE id = $1
`

func (q *Queries) GetMenuItem(ctx context.Context, id uuid.UUID) (MenuItem, error) {
	row := q.db.QueryRowContext(ctx, getMenuItem, id)
	var i MenuItem
	err := row.Scan(&i.ID, &i.MenuID, &i.Label, &i.Url, &i.SortOrder)
	return i, err
}

const listMenuItems = `-- name: ListMenuItems :many
SELECT id, menu_id, label, url, sort_order FROM menu_items ORDER BY id DESC
`

func (q *Queries) ListMenuItems(ctx context.Context) ([]MenuItem, error) {
	rows, err := q.db.QueryContext(ctx, listMenuItems)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []MenuItem
	for rows.Next() {
		var i MenuItem
		if err := rows.Scan(&i.ID, &i.MenuID, &i.Label, &i.Url, &i.SortOrder); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMenuItemsByMenuID = `-- name: ListMenuItemsByMenuID :many
SELECT id, menu_id, label, url, sort_order FROM menu_items WHERE menu_id = $1 ORDER BY id DESC
`

func (q *Queries) ListMenuItemsByMenuID(ctx context.Context, menuID uuid.UUID) ([]MenuItem, error) {
	rows, err := q.db.QueryContext(ctx, listMenuItemsByMenuID, menuID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []MenuItem
	for rows.Next() {
		var i MenuItem
		if err := rows.Scan(&i.ID, &i.MenuID, &i.Label, &i.Url, &i.SortOrder); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const deleteMenuItem = `-- name: DeleteMenuItem :exec
DELETE FROM menu_items WHERE id = $1
`

func (q *Queries) DeleteMenuItem(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, deleteMenuItem, id)
	return err
}

const createContentTranslation = `-- name: CreateContentTranslation :one
INSERT INTO content_translations (id, page_id, locale, translated_body)
VALUES ($1, $2, $3, $4)
RETURNING id, page_id, locale, translated_body
`

type CreateContentTranslationParams struct {
	ID             uuid.UUID
	PageID         uuid.UUID
	Locale         string
	TranslatedBody string
}

func (q *Queries) CreateContentTranslation(ctx context.Context, arg CreateContentTranslationParams) (ContentTranslation, error) {
	row := q.db.QueryRowContext(ctx, createContentTranslation, arg.ID, arg.PageID, arg.Locale, arg.TranslatedBody)
	var i ContentTranslation
	err := row.Scan(&i.ID, &i.PageID, &i.Locale, &i.TranslatedBody)
	return i, err
}

const getContentTranslation = `-- name: GetContentTranslation :one
SELECT id, page_id, locale, translated_body FROM content_translations WHERE id = $1
`

func (q *Queries) GetContentTranslation(ctx context.Context, id uuid.UUID) (ContentTranslation, error) {
	row := q.db.QueryRowContext(ctx, getContentTranslation, id)
	var i ContentTranslation
	err := row.Scan(&i.ID, &i.PageID, &i.Locale, &i.TranslatedBody)
	return i, err
}

const listContentTranslations = `-- name: ListContentTranslations :many
SELECT id, page_id, locale, translated_body FROM content_translations ORDER BY id DESC
`

func (q *Queries) ListContentTranslations(ctx context.Context) ([]ContentTranslation, error) {
	rows, err := q.db.QueryContext(ctx, listContentTranslations)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ContentTranslation
	for rows.Next() {
		var i ContentTranslation
		if err := rows.Scan(&i.ID, &i.PageID, &i.Locale, &i.TranslatedBody); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listContentTranslationsByPageID = `-- name: ListContentTranslationsByPageID :many
SELECT id, page_id, locale, translated_body FROM content_translations WHERE page_id = $1 ORDER BY id DESC
`

func (q *Queries) ListContentTranslationsByPageID(ctx context.Context, pageID uuid.UUID) ([]ContentTranslation, error) {
	rows, err := q.db.QueryContext(ctx, listContentTranslationsByPageID, pageID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ContentTranslation
	for rows.Next() {
		var i ContentTranslation
		if err := rows.Scan(&i.ID, &i.PageID, &i.Locale, &i.TranslatedBody); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const deleteContentTranslation = `-- name: DeleteContentTranslation :exec
DELETE FROM content_translations WHERE id = $1
`

func (q *Queries) DeleteContentTranslation(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, deleteContentTranslation, id)
	return err
}
