// Code generated by sqlc. DO NOT EDIT.
package sqlc

import (
	"time"

	"github.com/google/uuid"
)

type Banner struct {
	ID       uuid.UUID
	Title    string
	ImageUrl string
	StartsAt time.Time
	EndsAt   time.Time
}

type Page struct {
	ID    uuid.UUID
	Slug  string
	Title string
	Body  string
}

type BlogPost struct {
	ID          uuid.UUID
	Title       string
	Body        string
	PublishedAt time.Time
}

type BlogCategory struct {
	ID   uuid.UUID
	Name string
}

type BlogPostTag struct {
	ID         uuid.UUID
	BlogPostID uuid.UUID
	Tag        string
}

type MediaAsset struct {
	ID        uuid.UUID
	Url       string
	MediaType string
	CreatedAt time.Time
}

type SiteSetting struct {
	ID           uuid.UUID
	SettingKey   string
	SettingValue string
}

type Menu struct {
	ID   uuid.UUID
	Name string
}

type MenuItem struct {
	ID        uuid.UUID
	MenuID    uuid.UUID
	Label     string
	Url       string
	SortOrder int32
}

type ContentTranslation struct {
	ID             uuid.UUID
	PageID         uuid.UUID
	Locale         string
	TranslatedBody string
}
