// Code generated by sqlc. DO NOT EDIT.
package sqlc

import (
	"time"

	"github.com/google/uuid"
)

type PriceList struct {
	ID        uuid.UUID
	Name      string
	CreatedAt time.Time
}

type PriceRule struct {
	ID          uuid.UUID
	PriceListID uuid.UUID
	ProductID   uuid.UUID
	PriceYen    int32
}

type TaxRate struct {
	ID   uuid.UUID
	Name string
	Rate int32
}

type TaxRule struct {
	ID        uuid.UUID
	TaxRateID uuid.UUID
	Region    string
}

type Currency struct {
	ID   uuid.UUID
	Code string
}

type CurrencyRate struct {
	ID          uuid.UUID
	CurrencyID  uuid.UUID
	RateToJpy   int32
	EffectiveAt time.Time
}

type DiscountTier struct {
	ID              uuid.UUID
	MinQuantity     int32
	DiscountPercent int32
}

type PriceHistory struct {
	ID        uuid.UUID
	ProductID uuid.UUID
	PriceYen  int32
	ChangedAt time.Time
}

type BundleOffer struct {
	ID       uuid.UUID
	Name     string
	PriceYen int32
}

type BundleOfferItem struct {
	ID            uuid.UUID
	BundleOfferID uuid.UUID
	ProductID     uuid.UUID
	Quantity      int32
}
