// Code generated by sqlc. DO NOT EDIT.
package sqlc

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const createPriceList = `-- name: CreatePriceList :one
INSERT INTO price_lists (id, name, created_at)
VALUES ($1, $2, $3)
RETURNING id, name, created_at
`

type CreatePriceListParams struct {
	ID        uuid.UUID
	Name      string
	CreatedAt time.Time
}

func (q *Queries) CreatePriceList(ctx context.Context, arg CreatePriceListParams) (PriceList, error) {
	row := q.db.QueryRowContext(ctx, createPriceList, arg.ID, arg.Name, arg.CreatedAt)
	var i PriceList
	err := row.Scan(&i.ID, &i.Name, &i.CreatedAt)
	return i, err
}

const getPriceList = `-- name: GetPriceList :one
SELECT id, name, created_at FROM price_lists WHERE id = $1
`

func (q *Queries) GetPriceList(ctx context.Context, id uuid.UUID) (PriceList, error) {
	row := q.db.QueryRowContext(ctx, getPriceList, id)
	var i PriceList
	err := row.Scan(&i.ID, &i.Name, &i.CreatedAt)
	return i, err
}

const listPriceLists = `-- name: ListPriceLists :many
SELECT id, name, created_at FROM price_lists ORDER BY created_at DESC
`

func (q *Queries) ListPriceLists(ctx context.Context) ([]PriceList, error) {
	rows, err := q.db.QueryContext(ctx, listPriceLists)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []PriceList
	for rows.Next() {
		var i PriceList
		if err := rows.Scan(&i.ID, &i.Name, &i.CreatedAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const deletePriceList = `-- name: DeletePriceList :exec
DELETE FROM price_lists WHERE id = $1
`

func (q *Queries) DeletePriceList(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, deletePriceList, id)
	return err
}

const createPriceRule = `-- name: CreatePriceRule :one
INSERT INTO price_rules (id, price_list_id, product_id, price_yen)
VALUES ($1, $2, $3, $4)
RETURNING id, price_list_id, product_id, price_yen
`

type CreatePriceRuleParams struct {
	ID          uuid.UUID
	PriceListID uuid.UUID
	ProductID   uuid.UUID
	PriceYen    int32
}

func (q *Queries) CreatePriceRule(ctx context.Context, arg CreatePriceRuleParams) (PriceRule, error) {
	row := q.db.QueryRowContext(ctx, createPriceRule, arg.ID, arg.PriceListID, arg.ProductID, arg.PriceYen)
	var i PriceRule
	err := row.Scan(&i.ID, &i.PriceListID, &i.ProductID, &i.PriceYen)
	return i, err
}

const getPriceRule = `-- name: GetPriceRule :one
SELECT id, price_list_id, product_id, price_yen FROM price_rules WHERE id = $1
`

func (q *Queries) GetPriceRule(ctx context.Context, id uuid.UUID) (PriceRule, error) {
	row := q.db.QueryRowContext(ctx, getPriceRule, id)
	var i PriceRule
	err := row.Scan(&i.ID, &i.PriceListID, &i.ProductID, &i.PriceYen)
	return i, err
}

const listPriceRules = `-- name: ListPriceRules :many
SELECT id, price_list_id, product_id, price_yen FROM price_rules ORDER BY id DESC
`

func (q *Queries) ListPriceRules(ctx context.Context) ([]PriceRule, error) {
	rows, err := q.db.QueryContext(ctx, listPriceRules)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []PriceRule
	for rows.Next() {
		var i PriceRule
		if err := rows.Scan(&i.ID, &i.PriceListID, &i.ProductID, &i.PriceYen); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPriceRulesByPriceListID = `-- name: ListPriceRulesByPriceListID :many
SELECT id, price_list_id, product_id, price_yen FROM price_rules WHERE price_list_id = $1 ORDER BY id DESC
`

func (q *Queries) ListPriceRulesByPriceListID(ctx context.Context, priceListID uuid.UUID) ([]PriceRule, error) {
	rows, err := q.db.QueryContext(ctx, listPriceRulesByPriceListID, priceListID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []PriceRule
	for rows.Next() {
		var i PriceRule
		if err := rows.Scan(&i.ID, &i.PriceListID, &i.ProductID, &i.PriceYen); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const deletePriceRule = `-- name: DeletePriceRule :exec
DELETE FROM price_rules WHERE id = $1
`

func (q *Queries) DeletePriceRule(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, deletePriceRule, id)
	return err
}

const createTaxRate = `-- name: CreateTaxRate :one
INSERT INTO tax_rates (id, name, rate)
VALUES ($1, $2, $3)
RETURNING id, name, rate
`

type CreateTaxRateParams struct {
	ID   uuid.UUID
	Name string
	Rate int32
}

func (q *Queries) CreateTaxRate(ctx context.Context, arg CreateTaxRateParams) (TaxRate, error) {
	row := q.db.QueryRowContext(ctx, createTaxRate, arg.ID, arg.Name, arg.Rate)
	var i TaxRate
	err := row.Scan(&i.ID, &i.Name, &i.Rate)
	return i, err
}

const getTaxRate = `-- name: GetTaxRate :one
SELECT id, name, rate FROM tax_rates WHERE id = $1
`

func (q *Queries) GetTaxRate(ctx context.Context, id uuid.UUID) (TaxRate, error) {
	row := q.db.QueryRowContext(ctx, getTaxRate, id)
	var i TaxRate
	err := row.Scan(&i.ID, &i.Name, &i.Rate)
	return i, err
}

const listTaxRates = `-- name: ListTaxRates :many
SELECT id, name, rate FROM tax_rates ORDER BY id DESC
`

func (q *Queries) ListTaxRates(ctx context.Context) ([]TaxRate, error) {
	rows, err := q.db.QueryContext(ctx, listTaxRates)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []TaxRate
	for rows.Next() {
		var i TaxRate
		if err := rows.Scan(&i.ID, &i.Name, &i.Rate); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const deleteTaxRate = `-- name: DeleteTaxRate :exec
DELETE FROM tax_rates WHERE id = $1
`

func (q *Queries) DeleteTaxRate(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, deleteTaxRate, id)
	return err
}

const createTaxRule = `-- name: CreateTaxRule :one
INSERT INTO tax_rules (id, tax_rate_id, region)
VALUES ($1, $2, $3)
RETURNING id, tax_rate_id, region
`

type CreateTaxRuleParams struct {
	ID        uuid.UUID
	TaxRateID uuid.UUID
	Region    string
}

func (q *Queries) CreateTaxRule(ctx context.Context, arg CreateTaxRuleParams) (TaxRule, error) {
	row := q.db.QueryRowContext(ctx, createTaxRule, arg.ID, arg.TaxRateID, arg.Region)
	var i TaxRule
	err := row.Scan(&i.ID, &i.TaxRateID, &i.Region)
	return i, err
}

const getTaxRule = `-- name: GetTaxRule :one
SELECT id, tax_rate_id, region FROM tax_rules WHERE id = $1
`

func (q *Queries) GetTaxRule(ctx context.Context, id uuid.UUID) (TaxRule, error) {
	row := q.db.QueryRowContext(ctx, getTaxRule, id)
	var i TaxRule
	err := row.Scan(&i.ID, &i.TaxRateID, &i.Region)
	return i, err
}

const listTaxRules = `-- name: ListTaxRules :many
SELECT id, tax_rate_id, region FROM tax_rules ORDER BY id DESC
`

func (q *Queries) ListTaxRules(ctx context.Context) ([]TaxRule, error) {
	rows, err := q.db.QueryContext(ctx, listTaxRules)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []TaxRule
	for rows.Next() {
		var i TaxRule
		if err := rows.Scan(&i.ID, &i.TaxRateID, &i.Region); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTaxRulesByTaxRateID = `-- name: ListTaxRulesByTaxRateID :many
SELECT id, tax_rate_id, region FROM tax_rules WHERE tax_rate_id = $1 ORDER BY id DESC
`

func (q *Queries) ListTaxRulesByTaxRateID(ctx context.Context, taxRateID uuid.UUID) ([]TaxRule, error) {
	rows, err := q.db.QueryContext(ctx, listTaxRulesByTaxRateID, taxRateID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []TaxRule
	for rows.Next() {
		var i TaxRule
		if err := rows.Scan(&i.ID, &i.TaxRateID, &i.Region); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const deleteTaxRule = `-- name: DeleteTaxRule :exec
DELETE FROM tax_rules WHERE id = $1
`

func (q *Queries) DeleteTaxRule(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, deleteTaxRule, id)
	return err
}

const createCurrency = `-- name: CreateCurrency :one
INSERT INTO currencies (id, code)
VALUES ($1, $2)
RETURNING id, code
`

type CreateCurrencyParams struct {
	ID   uuid.UUID
	Code string
}

func (q *Queries) CreateCurrency(ctx context.Context, arg CreateCurrencyParams) (Currency, error) {
	row := q.db.QueryRowContext(ctx, createCurrency, arg.ID, arg.Code)
	var i Currency
	err := row.Scan(&i.ID, &i.Code)
	return i, err
}

const getCurrency = `-- name: GetCurrency :one
SELECT id, code FROM currencies WHERE id = $1
`

func (q *Queries) GetCurrency(ctx context.Context, id uuid.UUID) (Currency, error) {
	row := q.db.QueryRowContext(ctx, getCurrency, id)
	var i Currency
	err := row.Scan(&i.ID, &i.Code)
	return i, err
}

const listCurrencies = `-- name: ListCurrencies :many
SELECT id, code FROM currencies ORDER BY id DESC
`

func (q *Queries) ListCurrencies(ctx context.Context) ([]Currency, error) {
	rows, err := q.db.QueryContext(ctx, listCurrencies)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Currency
	for rows.Next() {
		var i Currency
		if err := rows.Scan(&i.ID, &i.Code); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const deleteCurrency = `-- name: DeleteCurrency :exec
DELETE FROM currencies WHERE id = $1
`

func (q *Queries) DeleteCurrency(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, deleteCurrency, id)
	return err
}

const createCurrencyRate = `-- name: CreateCurrencyRate :one
INSERT INTO currency_rates (id, currency_id, rate_to_jpy, effective_at)
VALUES ($1, $2, $3, $4)
RETURNING id, currency_id, rate_to_jpy, effective_at
`

type CreateCurrencyRateParams struct {
	ID          uuid.UUID
	CurrencyID  uuid.UUID
	RateToJpy   int32
	EffectiveAt time.Time
}

func (q *Queries) CreateCurrencyRate(ctx context.Context, arg CreateCurrencyRateParams) (CurrencyRate, error) {
	row := q.db.QueryRowContext(ctx, createCurrencyRate, arg.ID, arg.CurrencyID, arg.RateToJpy, arg.EffectiveAt)
	var i CurrencyRate
	err := row.Scan(&i.ID, &i.CurrencyID, &i.RateToJpy, &i.EffectiveAt)
	return i, err
}

const getCurrencyRate = `-- name: GetCurrencyRate :one
SELECT id, currency_id, rate_to_jpy, effective_at FROM currency_rates WHERE id = $1
`

func (q *Queries) GetCurrencyRate(ctx context.Context, id uuid.UUID) (CurrencyRate, error) {
	row := q.db.QueryRowContext(ctx, getCurrencyRate, id)
	var i CurrencyRate
	err := row.Scan(&i.ID, &i.CurrencyID, &i.RateToJpy, &i.EffectiveAt)
	return i, err
}

const listCurrencyRates = `-- name: ListCurrencyRates :many
SELECT id, currency_id, rate_to_jpy, effective_at FROM currency_rates ORDER BY effective_at DESC
`

func (q *Queries) ListCurrencyRates(ctx context.Context) ([]CurrencyRate, error) {
	rows, err := q.db.QueryContext(ctx, listCurrencyRates)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []CurrencyRate
	for rows.Next() {
		var i CurrencyRate
		if err := rows.Scan(&i.ID, &i.CurrencyID, &i.RateToJpy, &i.EffectiveAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCurrencyRatesByCurrencyID = `-- name: ListCurrencyRatesByCurrencyID :many
SELECT id, currency_id, rate_to_jpy, effective_at FROM currency_rates WHERE currency_id = $1 ORDER BY effective_at DESC
`

func (q *Queries) ListCurrencyRatesByCurrencyID(ctx context.Context, currencyID uuid.UUID) ([]CurrencyRate, error) {
	rows, err := q.db.QueryContext(ctx, listCurrencyRatesByCurrencyID, currencyID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []CurrencyRate
	for rows.Next() {
		var i CurrencyRate
		if err := rows.Scan(&i.ID, &i.CurrencyID, &i.RateToJpy, &i.EffectiveAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const deleteCurrencyRate = `-- name: DeleteCurrencyRate :exec
DELETE FROM currency_rates WHERE id = $1
`

func (q *Queries) DeleteCurrencyRate(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, deleteCurrencyRate, id)
	return err
}

const createDiscountTier = `-- name: CreateDiscountTier :one
INSERT INTO discount_tiers (id, min_quantity, discount_percent)
VALUES ($1, $2, $3)
RETURNING id, min_quantity, discount_percent
`

type CreateDiscountTierParams struct {
	ID              uuid.UUID
	MinQuantity     int32
	DiscountPercent int32
}

func (q *Queries) CreateDiscountTier(ctx context.Context, arg CreateDiscountTierParams) (DiscountTier, error) {
	row := q.db.QueryRowContext(ctx, createDiscountTier, arg.ID, arg.MinQuantity, arg.DiscountPercent)
	var i DiscountTier
	err := row.Scan(&i.ID, &i.MinQuantity, &i.DiscountPercent)
	return i, err
}

const getDiscountTier = `-- name: GetDiscountTier :one
SELECT id, min_quantity, discount_percent FROM discount_tiers WHERE id = $1
`

func (q *Queries) GetDiscountTier(ctx context.Context, id uuid.UUID) (DiscountTier, error) {
	row := q.db.QueryRowContext(ctx, getDiscountTier, id)
	var i DiscountTier
	err := row.Scan(&i.ID, &i.MinQuantity, &i.DiscountPercent)
	return i, err
}

const listDiscountTiers = `-- name: ListDiscountTiers :many
SELECT id, min_quantity, discount_percent FROM discount_tiers ORDER BY id DESC
`

func (q *Queries) ListDiscountTiers(ctx context.Context) ([]DiscountTier, error) {
	rows, err := q.db.QueryContext(ctx, listDiscountTiers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []DiscountTier
	for rows.Next() {
		var i DiscountTier
		if err := rows.Scan(&i.ID, &i.MinQuantity, &i.DiscountPercent); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const deleteDiscountTier = `-- name: DeleteDiscountTier :exec
DELETE FROM discount_tiers WHERE id = $1
`

func (q *Queries) DeleteDiscountTier(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, deleteDiscountTier, id)
	return err
}

const createPriceHistory = `-- name: CreatePriceHistory :one
INSERT INTO price_histories (id, product_id, price_yen, changed_at)
VALUES ($1, $2, $3, $4)
RETURNING id, product_id, price_yen, changed_at
`

type CreatePriceHistoryParams struct {
	ID        uuid.UUID
	ProductID uuid.UUID
	PriceYen  int32
	ChangedAt time.Time
}

func (q *Queries) CreatePriceHistory(ctx context.Context, arg CreatePriceHistoryParams) (PriceHistory, error) {
	row := q.db.QueryRowContext(ctx, createPriceHistory, arg.ID, arg.ProductID, arg.PriceYen, arg.ChangedAt)
	var i PriceHistory
	err := row.Scan(&i.ID, &i.ProductID, &i.PriceYen, &i.ChangedAt)
	return i, err
}

const getPriceHistory = `-- name: GetPriceHistory :one
SELECT id, product_id, price_yen, changed_at FROM price_histories WHERE id = $1
`

func (q *Queries) GetPriceHistory(ctx context.Context, id uuid.UUID) (PriceHistory, error) {
	row := q.db.QueryRowContext(ctx, getPriceHistory, id)
	var i PriceHistory
	err := row.Scan(&i.ID, &i.ProductID, &i.PriceYen, &i.ChangedAt)
	return i, err
}

const listPriceHistories = `-- name: ListPriceHistories :many
SELECT id, product_id, price_yen, changed_at FROM price_histories ORDER BY changed_at DESC
`

func (q *Queries) ListPriceHistories(ctx context.Context) ([]PriceHistory, error) {
	rows, err := q.db.QueryContext(ctx, listPriceHistories)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []PriceHistory
	for rows.Next() {
		var i PriceHistory
		if err := rows.Scan(&i.ID, &i.ProductID, &i.PriceYen, &i.ChangedAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPriceHistoriesByProductID = `-- name: ListPriceHistoriesByProductID :many
SELECT id, product_id, price_yen, changed_at FROM price_histories WHERE product_id = $1 ORDER BY changed_at DESC
`

func (q *Queries) ListPriceHistoriesByProductID(ctx context.Context, productID uuid.UUID) ([]PriceHistory, error) {
	rows, err := q.db.QueryContext(ctx, listPriceHistoriesByProductID, productID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []PriceHistory
	for rows.Next() {
		var i PriceHistory
		if err := rows.Scan(&i.ID, &i.ProductID, &i.PriceYen, &i.ChangedAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const deletePriceHistory = `-- name: DeletePriceHistory :exec
DELETE FROM price_histories WHERE id = $1
`

func (q *Queries) DeletePriceHistory(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, deletePriceHistory, id)
	return err
}

const createBundleOffer = `-- name: CreateBundleOffer :one
INSERT INTO bundle_offers (id, name, price_yen)
VALUES ($1, $2, $3)
RETURNING id, name, price_yen
`

type CreateBundleOfferParams struct {
	ID       uuid.UUID
	Name     string
	PriceYen int32
}

func (q *Queries) CreateBundleOffer(ctx context.Context, arg CreateBundleOfferParams) (BundleOffer, error) {
	row := q.db.QueryRowContext(ctx, createBundleOffer, arg.ID, arg.Name, arg.PriceYen)
	var i BundleOffer
	err := row.Scan(&i.ID, &i.Name, &i.PriceYen)
	return i, err
}

const getBundleOffer = `-- name: GetBundleOffer :one
SELECT id, name, price_yen FROM bundle_offers WHERE id = $1
`

func (q *Queries) GetBundleOffer(ctx context.Context, id uuid.UUID) (BundleOffer, error) {
	row := q.db.QueryRowContext(ctx, getBundleOffer, id)
	var i BundleOffer
	err := row.Scan(&i.ID, &i.Name, &i.PriceYen)
	return i, err
}

const listBundleOffers = `-- name: ListBundleOffers :many
SELECT id, name, price_yen FROM bundle_offers ORDER BY id DESC
`

func (q *Queries) ListBundleOffers(ctx context.Context) ([]BundleOffer, error) {
	rows, err := q.db.QueryContext(ctx, listBundleOffers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []BundleOffer
	for rows.Next() {
		var i BundleOffer
		if err := rows.Scan(&i.ID, &i.Name, &i.PriceYen); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const deleteBundleOffer = `-- name: DeleteBundleOffer :exec
DELETE FROM bundle_offers WHERE id = $1
`

func (q *Queries) DeleteBundleOffer(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, deleteBundleOffer, id)
	return err
}

const createBundleOfferItem = `-- name: CreateBundleOfferItem :one
INSERT INTO bundle_offer_items (id, bundle_offer_id, product_id, quantity)
VALUES ($1, $2, $3, $4)
RETURNING id, bundle_offer_id, product_id, quantity
`

type CreateBundleOfferItemParams struct {
	ID            uuid.UUID
	BundleOfferID uuid.UUID
	ProductID     uuid.UUID
	Quantity      int32
}

func (q *Queries) CreateBundleOfferItem(ctx context.Context, arg CreateBundleOfferItemParams) (BundleOfferItem, error) {
	row := q.db.QueryRowContext(ctx, createBundleOfferItem, arg.ID, arg.BundleOfferID, arg.ProductID, arg.Quantity)
	var i BundleOfferItem
	err := row.Scan(&i.ID, &i.BundleOfferID, &i.ProductID, &i.Quantity)
	return i, err
}

const getBundleOfferItem = `-- name: GetBundleOfferItem :one
SELECT id, bundle_offer_id, product_id, quantity FROM bundle_offer_items WHERE id = $1
`

func (q *Queries) GetBundleOfferItem(ctx context.Context, id uuid.UUID) (BundleOfferItem, error) {
	row := q.db.QueryRowContext(ctx, getBundleOfferItem, id)
	var i BundleOfferItem
	err := row.Scan(&i.ID, &i.BundleOfferID, &i.ProductID, &i.Quantity)
	return i, err
}

const listBundleOfferItems = `-- name: ListBundleOfferItems :many
SELECT id, bundle_offer_id, product_id, quantity FROM bundle_offer_items ORDER BY id DESC
`

func (q *Queries) ListBundleOfferItems(ctx context.Context) ([]BundleOfferItem, error) {
	rows, err := q.db.QueryContext(ctx, listBundleOfferItems)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []BundleOfferItem
	for rows.Next() {
		var i BundleOfferItem
		if err := rows.Scan(&i.ID, &i.BundleOfferID, &i.ProductID, &i.Quantity); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listBundleOfferItemsByBundleOfferID = `-- name: ListBundleOfferItemsByBundleOfferID :many
SELECT id, bundle_offer_id, product_id, quantity FROM bundle_offer_items WHERE bundle_offer_id = $1 ORDER BY id DESC
`

func (q *Queries) ListBundleOfferItemsByBundleOfferID(ctx context.Context, bundleOfferID uuid.UUID) ([]BundleOfferItem, error) {
	rows, err := q.db.QueryContext(ctx, listBundleOfferItemsByBundleOfferID, bundleOfferID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []BundleOfferItem
	for rows.Next() {
		var i BundleOfferItem
		if err := rows.Scan(&i.ID, &i.BundleOfferID, &i.ProductID, &i.Quantity); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const deleteBundleOfferItem = `-- name: DeleteBundleOfferItem :exec
DELETE FROM bundle_offer_items WHERE id = $1
`

func (q *Queries) DeleteBundleOfferItem(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, deleteBundleOfferItem, id)
	return err
}
