// Code generated by oapi-codegen from openapi/openapi.yaml. DO NOT EDIT.
//
// Regenerate with:
//
//	go generate ./...
package api

import "github.com/labstack/echo/v4"

type Member struct {
	Id    string `json:"id"`
	Name  string `json:"name"`
	Email string `json:"email"`
}

type CreateMemberRequest struct {
	Name  string `json:"name"`
	Email string `json:"email"`
}

// ServerInterface represents all server handlers described by openapi.yaml.
type ServerInterface interface {
	GetHealth(ctx echo.Context) error
	ListMembers(ctx echo.Context) error
	CreateMember(ctx echo.Context) error
}

// EchoRouter is the subset of *echo.Echo (or echo.Group) RegisterHandlers
// needs to wire up routes.
type EchoRouter interface {
	GET(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	POST(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
}

// RegisterHandlers adds each openapi.yaml route to router.
func RegisterHandlers(router EchoRouter, si ServerInterface) {
	router.GET("/health", si.GetHealth)
	router.GET("/members", si.ListMembers)
	router.POST("/members", si.CreateMember)
}
