// Code generated by sqlc. DO NOT EDIT.
package sqlc

import (
	"time"

	"github.com/google/uuid"
)

type Ticket struct {
	ID        uuid.UUID
	MemberID  uuid.UUID
	Subject   string
	Status    string
	CreatedAt time.Time
}

type TicketMessage struct {
	ID             uuid.UUID
	TicketID       uuid.UUID
	SenderMemberID uuid.UUID
	Body           string
	CreatedAt      time.Time
}

type TicketAttachment struct {
	ID              uuid.UUID
	TicketMessageID uuid.UUID
	URL             string
}

type TicketCategory struct {
	ID   uuid.UUID
	Name string
}

type TicketAssignment struct {
	ID            uuid.UUID
	TicketID      uuid.UUID
	StaffMemberID uuid.UUID
	AssignedAt    time.Time
}

type TicketStatusHistory struct {
	ID        uuid.UUID
	TicketID  uuid.UUID
	Status    string
	ChangedAt time.Time
}

type Faq struct {
	ID        uuid.UUID
	Question  string
	Answer    string
	CreatedAt time.Time
}

type FaqCategory struct {
	ID   uuid.UUID
	Name string
}

type SupportAgent struct {
	ID    uuid.UUID
	Name  string
	Email string
}

type SatisfactionSurvey struct {
	ID          uuid.UUID
	TicketID    uuid.UUID
	Score       int32
	Comment     string
	SubmittedAt time.Time
}
