// Code generated by sqlc. DO NOT EDIT.
package sqlc

import (
	"context"
	"time"

	"github.com/google/uuid"
)

// --- tickets ---

const createTicket = `-- name: CreateTicket :one
INSERT INTO tickets (id, member_id, subject, status, created_at)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, member_id, subject, status, created_at
`

type CreateTicketParams struct {
	ID        uuid.UUID
	MemberID  uuid.UUID
	Subject   string
	Status    string
	CreatedAt time.Time
}

func (q *Queries) CreateTicket(ctx context.Context, arg CreateTicketParams) (Ticket, error) {
	row := q.db.QueryRowContext(ctx, createTicket, arg.ID, arg.MemberID, arg.Subject, arg.Status, arg.CreatedAt)
	var i Ticket
	err := row.Scan(&i.ID, &i.MemberID, &i.Subject, &i.Status, &i.CreatedAt)
	return i, err
}

const getTicket = `-- name: GetTicket :one
SELECT id, member_id, subject, status, created_at FROM tickets WHERE id = $1
`

func (q *Queries) GetTicket(ctx context.Context, id uuid.UUID) (Ticket, error) {
	row := q.db.QueryRowContext(ctx, getTicket, id)
	var i Ticket
	err := row.Scan(&i.ID, &i.MemberID, &i.Subject, &i.Status, &i.CreatedAt)
	return i, err
}

const listTickets = `-- name: ListTickets :many
SELECT id, member_id, subject, status, created_at FROM tickets ORDER BY created_at DESC
`

func (q *Queries) ListTickets(ctx context.Context) ([]Ticket, error) {
	rows, err := q.db.QueryContext(ctx, listTickets)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Ticket
	for rows.Next() {
		var i Ticket
		if err := rows.Scan(&i.ID, &i.MemberID, &i.Subject, &i.Status, &i.CreatedAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTicketsByMemberID = `-- name: ListTicketsByMemberID :many
SELECT id, member_id, subject, status, created_at FROM tickets WHERE member_id = $1 ORDER BY created_at DESC
`

func (q *Queries) ListTicketsByMemberID(ctx context.Context, memberID uuid.UUID) ([]Ticket, error) {
	rows, err := q.db.QueryContext(ctx, listTicketsByMemberID, memberID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Ticket
	for rows.Next() {
		var i Ticket
		if err := rows.Scan(&i.ID, &i.MemberID, &i.Subject, &i.Status, &i.CreatedAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const deleteTicket = `-- name: DeleteTicket :exec
DELETE FROM tickets WHERE id = $1
`

func (q *Queries) DeleteTicket(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, deleteTicket, id)
	return err
}

// --- ticket_messages ---

const createTicketMessage = `-- name: CreateTicketMessage :one
INSERT INTO ticket_messages (id, ticket_id, sender_member_id, body, created_at)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, ticket_id, sender_member_id, body, created_at
`

type CreateTicketMessageParams struct {
	ID             uuid.UUID
	TicketID       uuid.UUID
	SenderMemberID uuid.UUID
	Body           string
	CreatedAt      time.Time
}

func (q *Queries) CreateTicketMessage(ctx context.Context, arg CreateTicketMessageParams) (TicketMessage, error) {
	row := q.db.QueryRowContext(ctx, createTicketMessage, arg.ID, arg.TicketID, arg.SenderMemberID, arg.Body, arg.CreatedAt)
	var i TicketMessage
	err := row.Scan(&i.ID, &i.TicketID, &i.SenderMemberID, &i.Body, &i.CreatedAt)
	return i, err
}

const getTicketMessage = `-- name: GetTicketMessage :one
SELECT id, ticket_id, sender_member_id, body, created_at FROM ticket_messages WHERE id = $1
`

func (q *Queries) GetTicketMessage(ctx context.Context, id uuid.UUID) (TicketMessage, error) {
	row := q.db.QueryRowContext(ctx, getTicketMessage, id)
	var i TicketMessage
	err := row.Scan(&i.ID, &i.TicketID, &i.SenderMemberID, &i.Body, &i.CreatedAt)
	return i, err
}

const listTicketMessages = `-- name: ListTicketMessages :many
SELECT id, ticket_id, sender_member_id, body, created_at FROM ticket_messages ORDER BY created_at DESC
`

func (q *Queries) ListTicketMessages(ctx context.Context) ([]TicketMessage, error) {
	rows, err := q.db.QueryContext(ctx, listTicketMessages)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []TicketMessage
	for rows.Next() {
		var i TicketMessage
		if err := rows.Scan(&i.ID, &i.TicketID, &i.SenderMemberID, &i.Body, &i.CreatedAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTicketMessagesByTicketID = `-- name: ListTicketMessagesByTicketID :many
SELECT id, ticket_id, sender_member_id, body, created_at FROM ticket_messages WHERE ticket_id = $1 ORDER BY created_at DESC
`

func (q *Queries) ListTicketMessagesByTicketID(ctx context.Context, ticketID uuid.UUID) ([]TicketMessage, error) {
	rows, err := q.db.QueryContext(ctx, listTicketMessagesByTicketID, ticketID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []TicketMessage
	for rows.Next() {
		var i TicketMessage
		if err := rows.Scan(&i.ID, &i.TicketID, &i.SenderMemberID, &i.Body, &i.CreatedAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const deleteTicketMessage = `-- name: DeleteTicketMessage :exec
DELETE FROM ticket_messages WHERE id = $1
`

func (q *Queries) DeleteTicketMessage(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, deleteTicketMessage, id)
	return err
}

// --- ticket_attachments ---

const createTicketAttachment = `-- name: CreateTicketAttachment :one
INSERT INTO ticket_attachments (id, ticket_message_id, url)
VALUES ($1, $2, $3)
RETURNING id, ticket_message_id, url
`

type CreateTicketAttachmentParams struct {
	ID              uuid.UUID
	TicketMessageID uuid.UUID
	URL             string
}

func (q *Queries) CreateTicketAttachment(ctx context.Context, arg CreateTicketAttachmentParams) (TicketAttachment, error) {
	row := q.db.QueryRowContext(ctx, createTicketAttachment, arg.ID, arg.TicketMessageID, arg.URL)
	var i TicketAttachment
	err := row.Scan(&i.ID, &i.TicketMessageID, &i.URL)
	return i, err
}

const getTicketAttachment = `-- name: GetTicketAttachment :one
SELECT id, ticket_message_id, url FROM ticket_attachments WHERE id = $1
`

func (q *Queries) GetTicketAttachment(ctx context.Context, id uuid.UUID) (TicketAttachment, error) {
	row := q.db.QueryRowContext(ctx, getTicketAttachment, id)
	var i TicketAttachment
	err := row.Scan(&i.ID, &i.TicketMessageID, &i.URL)
	return i, err
}

const listTicketAttachments = `-- name: ListTicketAttachments :many
SELECT id, ticket_message_id, url FROM ticket_attachments ORDER BY id DESC
`

func (q *Queries) ListTicketAttachments(ctx context.Context) ([]TicketAttachment, error) {
	rows, err := q.db.QueryContext(ctx, listTicketAttachments)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []TicketAttachment
	for rows.Next() {
		var i TicketAttachment
		if err := rows.Scan(&i.ID, &i.TicketMessageID, &i.URL); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTicketAttachmentsByTicketMessageID = `-- name: ListTicketAttachmentsByTicketMessageID :many
SELECT id, ticket_message_id, url FROM ticket_attachments WHERE ticket_message_id = $1 ORDER BY id DESC
`

func (q *Queries) ListTicketAttachmentsByTicketMessageID(ctx context.Context, ticketMessageID uuid.UUID) ([]TicketAttachment, error) {
	rows, err := q.db.QueryContext(ctx, listTicketAttachmentsByTicketMessageID, ticketMessageID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []TicketAttachment
	for rows.Next() {
		var i TicketAttachment
		if err := rows.Scan(&i.ID, &i.TicketMessageID, &i.URL); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const deleteTicketAttachment = `-- name: DeleteTicketAttachment :exec
DELETE FROM ticket_attachments WHERE id = $1
`

func (q *Queries) DeleteTicketAttachment(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, deleteTicketAttachment, id)
	return err
}

// --- ticket_categories ---

const createTicketCategory = `-- name: CreateTicketCategory :one
INSERT INTO ticket_categories (id, name)
VALUES ($1, $2)
RETURNING id, name
`

type CreateTicketCategoryParams struct {
	ID   uuid.UUID
	Name string
}

func (q *Queries) CreateTicketCategory(ctx context.Context, arg CreateTicketCategoryParams) (TicketCategory, error) {
	row := q.db.QueryRowContext(ctx, createTicketCategory, arg.ID, arg.Name)
	var i TicketCategory
	err := row.Scan(&i.ID, &i.Name)
	return i, err
}

const getTicketCategory = `-- name: GetTicketCategory :one
SELECT id, name FROM ticket_categories WHERE id = $1
`

func (q *Queries) GetTicketCategory(ctx context.Context, id uuid.UUID) (TicketCategory, error) {
	row := q.db.QueryRowContext(ctx, getTicketCategory, id)
	var i TicketCategory
	err := row.Scan(&i.ID, &i.Name)
	return i, err
}

const listTicketCategories = `-- name: ListTicketCategories :many
SELECT id, name FROM ticket_categories ORDER BY id DESC
`

func (q *Queries) ListTicketCategories(ctx context.Context) ([]TicketCategory, error) {
	rows, err := q.db.QueryContext(ctx, listTicketCategories)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []TicketCategory
	for rows.Next() {
		var i TicketCategory
		if err := rows.Scan(&i.ID, &i.Name); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const deleteTicketCategory = `-- name: DeleteTicketCategory :exec
DELETE FROM ticket_categories WHERE id = $1
`

func (q *Queries) DeleteTicketCategory(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, deleteTicketCategory, id)
	return err
}

// --- ticket_assignments ---

const createTicketAssignment = `-- name: CreateTicketAssignment :one
INSERT INTO ticket_assignments (id, ticket_id, staff_member_id, assigned_at)
VALUES ($1, $2, $3, $4)
RETURNING id, ticket_id, staff_member_id, assigned_at
`

type CreateTicketAssignmentParams struct {
	ID            uuid.UUID
	TicketID      uuid.UUID
	StaffMemberID uuid.UUID
	AssignedAt    time.Time
}

func (q *Queries) CreateTicketAssignment(ctx context.Context, arg CreateTicketAssignmentParams) (TicketAssignment, error) {
	row := q.db.QueryRowContext(ctx, createTicketAssignment, arg.ID, arg.TicketID, arg.StaffMemberID, arg.AssignedAt)
	var i TicketAssignment
	err := row.Scan(&i.ID, &i.TicketID, &i.StaffMemberID, &i.AssignedAt)
	return i, err
}

const getTicketAssignment = `-- name: GetTicketAssignment :one
SELECT id, ticket_id, staff_member_id, assigned_at FROM ticket_assignments WHERE id = $1
`

func (q *Queries) GetTicketAssignment(ctx context.Context, id uuid.UUID) (TicketAssignment, error) {
	row := q.db.QueryRowContext(ctx, getTicketAssignment, id)
	var i TicketAssignment
	err := row.Scan(&i.ID, &i.TicketID, &i.StaffMemberID, &i.AssignedAt)
	return i, err
}

const listTicketAssignments = `-- name: ListTicketAssignments :many
SELECT id, ticket_id, staff_member_id, assigned_at FROM ticket_assignments ORDER BY assigned_at DESC
`

func (q *Queries) ListTicketAssignments(ctx context.Context) ([]TicketAssignment, error) {
	rows, err := q.db.QueryContext(ctx, listTicketAssignments)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []TicketAssignment
	for rows.Next() {
		var i TicketAssignment
		if err := rows.Scan(&i.ID, &i.TicketID, &i.StaffMemberID, &i.AssignedAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTicketAssignmentsByTicketID = `-- name: ListTicketAssignmentsByTicketID :many
SELECT id, ticket_id, staff_member_id, assigned_at FROM ticket_assignments WHERE ticket_id = $1 ORDER BY assigned_at DESC
`

func (q *Queries) ListTicketAssignmentsByTicketID(ctx context.Context, ticketID uuid.UUID) ([]TicketAssignment, error) {
	rows, err := q.db.QueryContext(ctx, listTicketAssignmentsByTicketID, ticketID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []TicketAssignment
	for rows.Next() {
		var i TicketAssignment
		if err := rows.Scan(&i.ID, &i.TicketID, &i.StaffMemberID, &i.AssignedAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const deleteTicketAssignment = `-- name: DeleteTicketAssignment :exec
DELETE FROM ticket_assignments WHERE id = $1
`

func (q *Queries) DeleteTicketAssignment(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, deleteTicketAssignment, id)
	return err
}

// --- ticket_status_histories ---

const createTicketStatusHistory = `-- name: CreateTicketStatusHistory :one
INSERT INTO ticket_status_histories (id, ticket_id, status, changed_at)
VALUES ($1, $2, $3, $4)
RETURNING id, ticket_id, status, changed_at
`

type CreateTicketStatusHistoryParams struct {
	ID        uuid.UUID
	TicketID  uuid.UUID
	Status    string
	ChangedAt time.Time
}

func (q *Queries) CreateTicketStatusHistory(ctx context.Context, arg CreateTicketStatusHistoryParams) (TicketStatusHistory, error) {
	row := q.db.QueryRowContext(ctx, createTicketStatusHistory, arg.ID, arg.TicketID, arg.Status, arg.ChangedAt)
	var i TicketStatusHistory
	err := row.Scan(&i.ID, &i.TicketID, &i.Status, &i.ChangedAt)
	return i, err
}

const getTicketStatusHistory = `-- name: GetTicketStatusHistory :one
SELECT id, ticket_id, status, changed_at FROM ticket_status_histories WHERE id = $1
`

func (q *Queries) GetTicketStatusHistory(ctx context.Context, id uuid.UUID) (TicketStatusHistory, error) {
	row := q.db.QueryRowContext(ctx, getTicketStatusHistory, id)
	var i TicketStatusHistory
	err := row.Scan(&i.ID, &i.TicketID, &i.Status, &i.ChangedAt)
	return i, err
}

const listTicketStatusHistories = `-- name: ListTicketStatusHistories :many
SELECT id, ticket_id, status, changed_at FROM ticket_status_histories ORDER BY changed_at DESC
`

func (q *Queries) ListTicketStatusHistories(ctx context.Context) ([]TicketStatusHistory, error) {
	rows, err := q.db.QueryContext(ctx, listTicketStatusHistories)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []TicketStatusHistory
	for rows.Next() {
		var i TicketStatusHistory
		if err := rows.Scan(&i.ID, &i.TicketID, &i.Status, &i.ChangedAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTicketStatusHistoriesByTicketID = `-- name: ListTicketStatusHistoriesByTicketID :many
SELECT id, ticket_id, status, changed_at FROM ticket_status_histories WHERE ticket_id = $1 ORDER BY changed_at DESC
`

func (q *Queries) ListTicketStatusHistoriesByTicketID(ctx context.Context, ticketID uuid.UUID) ([]TicketStatusHistory, error) {
	rows, err := q.db.QueryContext(ctx, listTicketStatusHistoriesByTicketID, ticketID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []TicketStatusHistory
	for rows.Next() {
		var i TicketStatusHistory
		if err := rows.Scan(&i.ID, &i.TicketID, &i.Status, &i.ChangedAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const deleteTicketStatusHistory = `-- name: DeleteTicketStatusHistory :exec
DELETE FROM ticket_status_histories WHERE id = $1
`

func (q *Queries) DeleteTicketStatusHistory(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, deleteTicketStatusHistory, id)
	return err
}

// --- faqs ---

const createFaq = `-- name: CreateFaq :one
INSERT INTO faqs (id, question, answer, created_at)
VALUES ($1, $2, $3, $4)
RETURNING id, question, answer, created_at
`

type CreateFaqParams struct {
	ID        uuid.UUID
	Question  string
	Answer    string
	CreatedAt time.Time
}

func (q *Queries) CreateFaq(ctx context.Context, arg CreateFaqParams) (Faq, error) {
	row := q.db.QueryRowContext(ctx, createFaq, arg.ID, arg.Question, arg.Answer, arg.CreatedAt)
	var i Faq
	err := row.Scan(&i.ID, &i.Question, &i.Answer, &i.CreatedAt)
	return i, err
}

const getFaq = `-- name: GetFaq :one
SELECT id, question, answer, created_at FROM faqs WHERE id = $1
`

func (q *Queries) GetFaq(ctx context.Context, id uuid.UUID) (Faq, error) {
	row := q.db.QueryRowContext(ctx, getFaq, id)
	var i Faq
	err := row.Scan(&i.ID, &i.Question, &i.Answer, &i.CreatedAt)
	return i, err
}

const listFaqs = `-- name: ListFaqs :many
SELECT id, question, answer, created_at FROM faqs ORDER BY created_at DESC
`

func (q *Queries) ListFaqs(ctx context.Context) ([]Faq, error) {
	rows, err := q.db.QueryContext(ctx, listFaqs)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Faq
	for rows.Next() {
		var i Faq
		if err := rows.Scan(&i.ID, &i.Question, &i.Answer, &i.CreatedAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const deleteFaq = `-- name: DeleteFaq :exec
DELETE FROM faqs WHERE id = $1
`

func (q *Queries) DeleteFaq(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, deleteFaq, id)
	return err
}

// --- faq_categories ---

const createFaqCategory = `-- name: CreateFaqCategory :one
INSERT INTO faq_categories (id, name)
VALUES ($1, $2)
RETURNING id, name
`

type CreateFaqCategoryParams struct {
	ID   uuid.UUID
	Name string
}

func (q *Queries) CreateFaqCategory(ctx context.Context, arg CreateFaqCategoryParams) (FaqCategory, error) {
	row := q.db.QueryRowContext(ctx, createFaqCategory, arg.ID, arg.Name)
	var i FaqCategory
	err := row.Scan(&i.ID, &i.Name)
	return i, err
}

const getFaqCategory = `-- name: GetFaqCategory :one
SELECT id, name FROM faq_categories WHERE id = $1
`

func (q *Queries) GetFaqCategory(ctx context.Context, id uuid.UUID) (FaqCategory, error) {
	row := q.db.QueryRowContext(ctx, getFaqCategory, id)
	var i FaqCategory
	err := row.Scan(&i.ID, &i.Name)
	return i, err
}

const listFaqCategories = `-- name: ListFaqCategories :many
SELECT id, name FROM faq_categories ORDER BY id DESC
`

func (q *Queries) ListFaqCategories(ctx context.Context) ([]FaqCategory, error) {
	rows, err := q.db.QueryContext(ctx, listFaqCategories)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []FaqCategory
	for rows.Next() {
		var i FaqCategory
		if err := rows.Scan(&i.ID, &i.Name); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const deleteFaqCategory = `-- name: DeleteFaqCategory :exec
DELETE FROM faq_categories WHERE id = $1
`

func (q *Queries) DeleteFaqCategory(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, deleteFaqCategory, id)
	return err
}

// --- support_agents ---

const createSupportAgent = `-- name: CreateSupportAgent :one
INSERT INTO support_agents (id, name, email)
VALUES ($1, $2, $3)
RETURNING id, name, email
`

type CreateSupportAgentParams struct {
	ID    uuid.UUID
	Name  string
	Email string
}

func (q *Queries) CreateSupportAgent(ctx context.Context, arg CreateSupportAgentParams) (SupportAgent, error) {
	row := q.db.QueryRowContext(ctx, createSupportAgent, arg.ID, arg.Name, arg.Email)
	var i SupportAgent
	err := row.Scan(&i.ID, &i.Name, &i.Email)
	return i, err
}

const getSupportAgent = `-- name: GetSupportAgent :one
SELECT id, name, email FROM support_agents WHERE id = $1
`

func (q *Queries) GetSupportAgent(ctx context.Context, id uuid.UUID) (SupportAgent, error) {
	row := q.db.QueryRowContext(ctx, getSupportAgent, id)
	var i SupportAgent
	err := row.Scan(&i.ID, &i.Name, &i.Email)
	return i, err
}

const listSupportAgents = `-- name: ListSupportAgents :many
SELECT id, name, email FROM support_agents ORDER BY id DESC
`

func (q *Queries) ListSupportAgents(ctx context.Context) ([]SupportAgent, error) {
	rows, err := q.db.QueryContext(ctx, listSupportAgents)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SupportAgent
	for rows.Next() {
		var i SupportAgent
		if err := rows.Scan(&i.ID, &i.Name, &i.Email); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const deleteSupportAgent = `-- name: DeleteSupportAgent :exec
DELETE FROM support_agents WHERE id = $1
`

func (q *Queries) DeleteSupportAgent(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, deleteSupportAgent, id)
	return err
}

// --- satisfaction_surveys ---

const createSatisfactionSurvey = `-- name: CreateSatisfactionSurvey :one
INSERT INTO satisfaction_surveys (id, ticket_id, score, comment, submitted_at)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, ticket_id, score, comment, submitted_at
`

type CreateSatisfactionSurveyParams struct {
	ID          uuid.UUID
	TicketID    uuid.UUID
	Score       int32
	Comment     string
	SubmittedAt time.Time
}

func (q *Queries) CreateSatisfactionSurvey(ctx context.Context, arg CreateSatisfactionSurveyParams) (SatisfactionSurvey, error) {
	row := q.db.QueryRowContext(ctx, createSatisfactionSurvey, arg.ID, arg.TicketID, arg.Score, arg.Comment, arg.SubmittedAt)
	var i SatisfactionSurvey
	err := row.Scan(&i.ID, &i.TicketID, &i.Score, &i.Comment, &i.SubmittedAt)
	return i, err
}

const getSatisfactionSurvey = `-- name: GetSatisfactionSurvey :one
SELECT id, ticket_id, score, comment, submitted_at FROM satisfaction_surveys WHERE id = $1
`

func (q *Queries) GetSatisfactionSurvey(ctx context.Context, id uuid.UUID) (SatisfactionSurvey, error) {
	row := q.db.QueryRowContext(ctx, getSatisfactionSurvey, id)
	var i SatisfactionSurvey
	err := row.Scan(&i.ID, &i.TicketID, &i.Score, &i.Comment, &i.SubmittedAt)
	return i, err
}

const listSatisfactionSurveys = `-- name: ListSatisfactionSurveys :many
SELECT id, ticket_id, score, comment, submitted_at FROM satisfaction_surveys ORDER BY submitted_at DESC
`

func (q *Queries) ListSatisfactionSurveys(ctx context.Context) ([]SatisfactionSurvey, error) {
	rows, err := q.db.QueryContext(ctx, listSatisfactionSurveys)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SatisfactionSurvey
	for rows.Next() {
		var i SatisfactionSurvey
		if err := rows.Scan(&i.ID, &i.TicketID, &i.Score, &i.Comment, &i.SubmittedAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSatisfactionSurveysByTicketID = `-- name: ListSatisfactionSurveysByTicketID :many
SELECT id, ticket_id, score, comment, submitted_at FROM satisfaction_surveys WHERE ticket_id = $1 ORDER BY submitted_at DESC
`

func (q *Queries) ListSatisfactionSurveysByTicketID(ctx context.Context, ticketID uuid.UUID) ([]SatisfactionSurvey, error) {
	rows, err := q.db.QueryContext(ctx, listSatisfactionSurveysByTicketID, ticketID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SatisfactionSurvey
	for rows.Next() {
		var i SatisfactionSurvey
		if err := rows.Scan(&i.ID, &i.TicketID, &i.Score, &i.Comment, &i.SubmittedAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const deleteSatisfactionSurvey = `-- name: DeleteSatisfactionSurvey :exec
DELETE FROM satisfaction_surveys WHERE id = $1
`

func (q *Queries) DeleteSatisfactionSurvey(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, deleteSatisfactionSurvey, id)
	return err
}
