// Code generated by sqlc. DO NOT EDIT.
package sqlc

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const createLoyaltyProgram = `-- name: CreateLoyaltyProgram :one
INSERT INTO loyalty_programs (id, name, created_at)
VALUES ($1, $2, $3)
RETURNING id, name, created_at
`

type CreateLoyaltyProgramParams struct {
	ID        uuid.UUID
	Name      string
	CreatedAt time.Time
}

func (q *Queries) CreateLoyaltyProgram(ctx context.Context, arg CreateLoyaltyProgramParams) (LoyaltyProgram, error) {
	row := q.db.QueryRowContext(ctx, createLoyaltyProgram, arg.ID, arg.Name, arg.CreatedAt)
	var i LoyaltyProgram
	err := row.Scan(&i.ID, &i.Name, &i.CreatedAt)
	return i, err
}

const getLoyaltyProgram = `-- name: GetLoyaltyProgram :one
SELECT id, name, created_at FROM loyalty_programs WHERE id = $1
`

func (q *Queries) GetLoyaltyProgram(ctx context.Context, id uuid.UUID) (LoyaltyProgram, error) {
	row := q.db.QueryRowContext(ctx, getLoyaltyProgram, id)
	var i LoyaltyProgram
	err := row.Scan(&i.ID, &i.Name, &i.CreatedAt)
	return i, err
}

const listLoyaltyPrograms = `-- name: ListLoyaltyPrograms :many
SELECT id, name, created_at FROM loyalty_programs ORDER BY created_at DESC
`

func (q *Queries) ListLoyaltyPrograms(ctx context.Context) ([]LoyaltyProgram, error) {
	rows, err := q.db.QueryContext(ctx, listLoyaltyPrograms)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []LoyaltyProgram
	for rows.Next() {
		var i LoyaltyProgram
		if err := rows.Scan(&i.ID, &i.Name, &i.CreatedAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const deleteLoyaltyProgram = `-- name: DeleteLoyaltyProgram :exec
DELETE FROM loyalty_programs WHERE id = $1
`

func (q *Queries) DeleteLoyaltyProgram(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, deleteLoyaltyProgram, id)
	return err
}

const createLoyaltyTier = `-- name: CreateLoyaltyTier :one
INSERT INTO loyalty_tiers (id, loyalty_program_id, name, min_points)
VALUES ($1, $2, $3, $4)
RETURNING id, loyalty_program_id, name, min_points
`

type CreateLoyaltyTierParams struct {
	ID               uuid.UUID
	LoyaltyProgramID uuid.UUID
	Name             string
	MinPoints        int32
}

func (q *Queries) CreateLoyaltyTier(ctx context.Context, arg CreateLoyaltyTierParams) (LoyaltyTier, error) {
	row := q.db.QueryRowContext(ctx, createLoyaltyTier, arg.ID, arg.LoyaltyProgramID, arg.Name, arg.MinPoints)
	var i LoyaltyTier
	err := row.Scan(&i.ID, &i.LoyaltyProgramID, &i.Name, &i.MinPoints)
	return i, err
}

const getLoyaltyTier = `-- name: GetLoyaltyTier :one
SELECT id, loyalty_program_id, name, min_points FROM loyalty_tiers WHERE id = $1
`

func (q *Queries) GetLoyaltyTier(ctx context.Context, id uuid.UUID) (LoyaltyTier, error) {
	row := q.db.QueryRowContext(ctx, getLoyaltyTier, id)
	var i LoyaltyTier
	err := row.Scan(&i.ID, &i.LoyaltyProgramID, &i.Name, &i.MinPoints)
	return i, err
}

const listLoyaltyTiers = `-- name: ListLoyaltyTiers :many
SELECT id, loyalty_program_id, name, min_points FROM loyalty_tiers ORDER BY id DESC
`

func (q *Queries) ListLoyaltyTiers(ctx context.Context) ([]LoyaltyTier, error) {
	rows, err := q.db.QueryContext(ctx, listLoyaltyTiers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []LoyaltyTier
	for rows.Next() {
		var i LoyaltyTier
		if err := rows.Scan(&i.ID, &i.LoyaltyProgramID, &i.Name, &i.MinPoints); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listLoyaltyTiersByLoyaltyProgramID = `-- name: ListLoyaltyTiersByLoyaltyProgramID :many
SELECT id, loyalty_program_id, name, min_points FROM loyalty_tiers WHERE loyalty_program_id = $1 ORDER BY id DESC
`

func (q *Queries) ListLoyaltyTiersByLoyaltyProgramID(ctx context.Context, loyaltyProgramID uuid.UUID) ([]LoyaltyTier, error) {
	rows, err := q.db.QueryContext(ctx, listLoyaltyTiersByLoyaltyProgramID, loyaltyProgramID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []LoyaltyTier
	for rows.Next() {
		var i LoyaltyTier
		if err := rows.Scan(&i.ID, &i.LoyaltyProgramID, &i.Name, &i.MinPoints); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const deleteLoyaltyTier = `-- name: DeleteLoyaltyTier :exec
DELETE FROM loyalty_tiers WHERE id = $1
`

func (q *Queries) DeleteLoyaltyTier(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, deleteLoyaltyTier, id)
	return err
}

const createPointRule = `-- name: CreatePointRule :one
INSERT INTO point_rules (id, loyalty_program_id, action, points)
VALUES ($1, $2, $3, $4)
RETURNING id, loyalty_program_id, action, points
`

type CreatePointRuleParams struct {
	ID               uuid.UUID
	LoyaltyProgramID uuid.UUID
	Action           string
	Points           int32
}

func (q *Queries) CreatePointRule(ctx context.Context, arg CreatePointRuleParams) (PointRule, error) {
	row := q.db.QueryRowContext(ctx, createPointRule, arg.ID, arg.LoyaltyProgramID, arg.Action, arg.Points)
	var i PointRule
	err := row.Scan(&i.ID, &i.LoyaltyProgramID, &i.Action, &i.Points)
	return i, err
}

const getPointRule = `-- name: GetPointRule :one
SELECT id, loyalty_program_id, action, points FROM point_rules WHERE id = $1
`

func (q *Queries) GetPointRule(ctx context.Context, id uuid.UUID) (PointRule, error) {
	row := q.db.QueryRowContext(ctx, getPointRule, id)
	var i PointRule
	err := row.Scan(&i.ID, &i.LoyaltyProgramID, &i.Action, &i.Points)
	return i, err
}

const listPointRules = `-- name: ListPointRules :many
SELECT id, loyalty_program_id, action, points FROM point_rules ORDER BY id DESC
`

func (q *Queries) ListPointRules(ctx context.Context) ([]PointRule, error) {
	rows, err := q.db.QueryContext(ctx, listPointRules)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []PointRule
	for rows.Next() {
		var i PointRule
		if err := rows.Scan(&i.ID, &i.LoyaltyProgramID, &i.Action, &i.Points); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPointRulesByLoyaltyProgramID = `-- name: ListPointRulesByLoyaltyProgramID :many
SELECT id, loyalty_program_id, action, points FROM point_rules WHERE loyalty_program_id = $1 ORDER BY id DESC
`

func (q *Queries) ListPointRulesByLoyaltyProgramID(ctx context.Context, loyaltyProgramID uuid.UUID) ([]PointRule, error) {
	rows, err := q.db.QueryContext(ctx, listPointRulesByLoyaltyProgramID, loyaltyProgramID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []PointRule
	for rows.Next() {
		var i PointRule
		if err := rows.Scan(&i.ID, &i.LoyaltyProgramID, &i.Action, &i.Points); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const deletePointRule = `-- name: DeletePointRule :exec
DELETE FROM point_rules WHERE id = $1
`

func (q *Queries) DeletePointRule(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, deletePointRule, id)
	return err
}

const createPointRedemption = `-- name: CreatePointRedemption :one
INSERT INTO point_redemptions (id, member_id, points, redeemed_at)
VALUES ($1, $2, $3, $4)
RETURNING id, member_id, points, redeemed_at
`

type CreatePointRedemptionParams struct {
	ID         uuid.UUID
	MemberID   uuid.UUID
	Points     int32
	RedeemedAt time.Time
}

func (q *Queries) CreatePointRedemption(ctx context.Context, arg CreatePointRedemptionParams) (PointRedemption, error) {
	row := q.db.QueryRowContext(ctx, createPointRedemption, arg.ID, arg.MemberID, arg.Points, arg.RedeemedAt)
	var i PointRedemption
	err := row.Scan(&i.ID, &i.MemberID, &i.Points, &i.RedeemedAt)
	return i, err
}

const getPointRedemption = `-- name: GetPointRedemption :one
SELECT id, member_id, points, redeemed_at FROM point_redemptions WHERE id = $1
`

func (q *Queries) GetPointRedemption(ctx context.Context, id uuid.UUID) (PointRedemption, error) {
	row := q.db.QueryRowContext(ctx, getPointRedemption, id)
	var i PointRedemption
	err := row.Scan(&i.ID, &i.MemberID, &i.Points, &i.RedeemedAt)
	return i, err
}

const listPointRedemptions = `-- name: ListPointRedemptions :many
SELECT id, member_id, points, redeemed_at FROM point_redemptions ORDER BY redeemed_at DESC
`

func (q *Queries) ListPointRedemptions(ctx context.Context) ([]PointRedemption, error) {
	rows, err := q.db.QueryContext(ctx, listPointRedemptions)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []PointRedemption
	for rows.Next() {
		var i PointRedemption
		if err := rows.Scan(&i.ID, &i.MemberID, &i.Points, &i.RedeemedAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPointRedemptionsByMemberID = `-- name: ListPointRedemptionsByMemberID :many
SELECT id, member_id, points, redeemed_at FROM point_redemptions WHERE member_id = $1 ORDER BY redeemed_at DESC
`

func (q *Queries) ListPointRedemptionsByMemberID(ctx context.Context, memberID uuid.UUID) ([]PointRedemption, error) {
	rows, err := q.db.QueryContext(ctx, listPointRedemptionsByMemberID, memberID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []PointRedemption
	for rows.Next() {
		var i PointRedemption
		if err := rows.Scan(&i.ID, &i.MemberID, &i.Points, &i.RedeemedAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const deletePointRedemption = `-- name: DeletePointRedemption :exec
DELETE FROM point_redemptions WHERE id = $1
`

func (q *Queries) DeletePointRedemption(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, deletePointRedemption, id)
	return err
}

const createLoyaltyTierHistory = `-- name: CreateLoyaltyTierHistory :one
INSERT INTO loyalty_tier_histories (id, member_id, loyalty_tier_id, changed_at)
VALUES ($1, $2, $3, $4)
RETURNING id, member_id, loyalty_tier_id, changed_at
`

type CreateLoyaltyTierHistoryParams struct {
	ID            uuid.UUID
	MemberID      uuid.UUID
	LoyaltyTierID uuid.UUID
	ChangedAt     time.Time
}

func (q *Queries) CreateLoyaltyTierHistory(ctx context.Context, arg CreateLoyaltyTierHistoryParams) (LoyaltyTierHistory, error) {
	row := q.db.QueryRowContext(ctx, createLoyaltyTierHistory, arg.ID, arg.MemberID, arg.LoyaltyTierID, arg.ChangedAt)
	var i LoyaltyTierHistory
	err := row.Scan(&i.ID, &i.MemberID, &i.LoyaltyTierID, &i.ChangedAt)
	return i, err
}

const getLoyaltyTierHistory = `-- name: GetLoyaltyTierHistory :one
SELECT id, member_id, loyalty_tier_id, changed_at FROM loyalty_tier_histories WHERE id = $1
`

func (q *Queries) GetLoyaltyTierHistory(ctx context.Context, id uuid.UUID) (LoyaltyTierHistory, error) {
	row := q.db.QueryRowContext(ctx, getLoyaltyTierHistory, id)
	var i LoyaltyTierHistory
	err := row.Scan(&i.ID, &i.MemberID, &i.LoyaltyTierID, &i.ChangedAt)
	return i, err
}

const listLoyaltyTierHistories = `-- name: ListLoyaltyTierHistories :many
SELECT id, member_id, loyalty_tier_id, changed_at FROM loyalty_tier_histories ORDER BY changed_at DESC
`

func (q *Queries) ListLoyaltyTierHistories(ctx context.Context) ([]LoyaltyTierHistory, error) {
	rows, err := q.db.QueryContext(ctx, listLoyaltyTierHistories)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []LoyaltyTierHistory
	for rows.Next() {
		var i LoyaltyTierHistory
		if err := rows.Scan(&i.ID, &i.MemberID, &i.LoyaltyTierID, &i.ChangedAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listLoyaltyTierHistoriesByMemberID = `-- name: ListLoyaltyTierHistoriesByMemberID :many
SELECT id, member_id, loyalty_tier_id, changed_at FROM loyalty_tier_histories WHERE member_id = $1 ORDER BY changed_at DESC
`

func (q *Queries) ListLoyaltyTierHistoriesByMemberID(ctx context.Context, memberID uuid.UUID) ([]LoyaltyTierHistory, error) {
	rows, err := q.db.QueryContext(ctx, listLoyaltyTierHistoriesByMemberID, memberID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []LoyaltyTierHistory
	for rows.Next() {
		var i LoyaltyTierHistory
		if err := rows.Scan(&i.ID, &i.MemberID, &i.LoyaltyTierID, &i.ChangedAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const deleteLoyaltyTierHistory = `-- name: DeleteLoyaltyTierHistory :exec
DELETE FROM loyalty_tier_histories WHERE id = $1
`

func (q *Queries) DeleteLoyaltyTierHistory(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, deleteLoyaltyTierHistory, id)
	return err
}

const createRewardItem = `-- name: CreateRewardItem :one
INSERT INTO reward_items (id, name, points_cost)
VALUES ($1, $2, $3)
RETURNING id, name, points_cost
`

type CreateRewardItemParams struct {
	ID         uuid.UUID
	Name       string
	PointsCost int32
}

func (q *Queries) CreateRewardItem(ctx context.Context, arg CreateRewardItemParams) (RewardItem, error) {
	row := q.db.QueryRowContext(ctx, createRewardItem, arg.ID, arg.Name, arg.PointsCost)
	var i RewardItem
	err := row.Scan(&i.ID, &i.Name, &i.PointsCost)
	return i, err
}

const getRewardItem = `-- name: GetRewardItem :one
SELECT id, name, points_cost FROM reward_items WHERE id = $1
`

func (q *Queries) GetRewardItem(ctx context.Context, id uuid.UUID) (RewardItem, error) {
	row := q.db.QueryRowContext(ctx, getRewardItem, id)
	var i RewardItem
	err := row.Scan(&i.ID, &i.Name, &i.PointsCost)
	return i, err
}

const listRewardItems = `-- name: ListRewardItems :many
SELECT id, name, points_cost FROM reward_items ORDER BY id DESC
`

func (q *Queries) ListRewardItems(ctx context.Context) ([]RewardItem, error) {
	rows, err := q.db.QueryContext(ctx, listRewardItems)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []RewardItem
	for rows.Next() {
		var i RewardItem
		if err := rows.Scan(&i.ID, &i.Name, &i.PointsCost); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const deleteRewardItem = `-- name: DeleteRewardItem :exec
DELETE FROM reward_items WHERE id = $1
`

func (q *Queries) DeleteRewardItem(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, deleteRewardItem, id)
	return err
}

const createRewardRedemption = `-- name: CreateRewardRedemption :one
INSERT INTO reward_redemptions (id, member_id, reward_item_id, redeemed_at)
VALUES ($1, $2, $3, $4)
RETURNING id, member_id, reward_item_id, redeemed_at
`

type CreateRewardRedemptionParams struct {
	ID           uuid.UUID
	MemberID     uuid.UUID
	RewardItemID uuid.UUID
	RedeemedAt   time.Time
}

func (q *Queries) CreateRewardRedemption(ctx context.Context, arg CreateRewardRedemptionParams) (RewardRedemption, error) {
	row := q.db.QueryRowContext(ctx, createRewardRedemption, arg.ID, arg.MemberID, arg.RewardItemID, arg.RedeemedAt)
	var i RewardRedemption
	err := row.Scan(&i.ID, &i.MemberID, &i.RewardItemID, &i.RedeemedAt)
	return i, err
}

const getRewardRedemption = `-- name: GetRewardRedemption :one
SELECT id, member_id, reward_item_id, redeemed_at FROM reward_redemptions WHERE id = $1
`

func (q *Queries) GetRewardRedemption(ctx context.Context, id uuid.UUID) (RewardRedemption, error) {
	row := q.db.QueryRowContext(ctx, getRewardRedemption, id)
	var i RewardRedemption
	err := row.Scan(&i.ID, &i.MemberID, &i.RewardItemID, &i.RedeemedAt)
	return i, err
}

const listRewardRedemptions = `-- name: ListRewardRedemptions :many
SELECT id, member_id, reward_item_id, redeemed_at FROM reward_redemptions ORDER BY redeemed_at DESC
`

func (q *Queries) ListRewardRedemptions(ctx context.Context) ([]RewardRedemption, error) {
	rows, err := q.db.QueryContext(ctx, listRewardRedemptions)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []RewardRedemption
	for rows.Next() {
		var i RewardRedemption
		if err := rows.Scan(&i.ID, &i.MemberID, &i.RewardItemID, &i.RedeemedAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRewardRedemptionsByMemberID = `-- name: ListRewardRedemptionsByMemberID :many
SELECT id, member_id, reward_item_id, redeemed_at FROM reward_redemptions WHERE member_id = $1 ORDER BY redeemed_at DESC
`

func (q *Queries) ListRewardRedemptionsByMemberID(ctx context.Context, memberID uuid.UUID) ([]RewardRedemption, error) {
	rows, err := q.db.QueryContext(ctx, listRewardRedemptionsByMemberID, memberID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []RewardRedemption
	for rows.Next() {
		var i RewardRedemption
		if err := rows.Scan(&i.ID, &i.MemberID, &i.RewardItemID, &i.RedeemedAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const deleteRewardRedemption = `-- name: DeleteRewardRedemption :exec
DELETE FROM reward_redemptions WHERE id = $1
`

func (q *Queries) DeleteRewardRedemption(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, deleteRewardRedemption, id)
	return err
}

const createReferralBonus = `-- name: CreateReferralBonus :one
INSERT INTO referral_bonuses (id, member_id, points, granted_at)
VALUES ($1, $2, $3, $4)
RETURNING id, member_id, points, granted_at
`

type CreateReferralBonusParams struct {
	ID        uuid.UUID
	MemberID  uuid.UUID
	Points    int32
	GrantedAt time.Time
}

func (q *Queries) CreateReferralBonus(ctx context.Context, arg CreateReferralBonusParams) (ReferralBonus, error) {
	row := q.db.QueryRowContext(ctx, createReferralBonus, arg.ID, arg.MemberID, arg.Points, arg.GrantedAt)
	var i ReferralBonus
	err := row.Scan(&i.ID, &i.MemberID, &i.Points, &i.GrantedAt)
	return i, err
}

const getReferralBonus = `-- name: GetReferralBonus :one
SELECT id, member_id, points, granted_at FROM referral_bonuses WHERE id = $1
`

func (q *Queries) GetReferralBonus(ctx context.Context, id uuid.UUID) (ReferralBonus, error) {
	row := q.db.QueryRowContext(ctx, getReferralBonus, id)
	var i ReferralBonus
	err := row.Scan(&i.ID, &i.MemberID, &i.Points, &i.GrantedAt)
	return i, err
}

const listReferralBonuses = `-- name: ListReferralBonuses :many
SELECT id, member_id, points, granted_at FROM referral_bonuses ORDER BY granted_at DESC
`

func (q *Queries) ListReferralBonuses(ctx context.Context) ([]ReferralBonus, error) {
	rows, err := q.db.QueryContext(ctx, listReferralBonuses)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ReferralBonus
	for rows.Next() {
		var i ReferralBonus
		if err := rows.Scan(&i.ID, &i.MemberID, &i.Points, &i.GrantedAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listReferralBonusesByMemberID = `-- name: ListReferralBonusesByMemberID :many
SELECT id, member_id, points, granted_at FROM referral_bonuses WHERE member_id = $1 ORDER BY granted_at DESC
`

func (q *Queries) ListReferralBonusesByMemberID(ctx context.Context, memberID uuid.UUID) ([]ReferralBonus, error) {
	rows, err := q.db.QueryContext(ctx, listReferralBonusesByMemberID, memberID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ReferralBonus
	for rows.Next() {
		var i ReferralBonus
		if err := rows.Scan(&i.ID, &i.MemberID, &i.Points, &i.GrantedAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const deleteReferralBonus = `-- name: DeleteReferralBonus :exec
DELETE FROM referral_bonuses WHERE id = $1
`

func (q *Queries) DeleteReferralBonus(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, deleteReferralBonus, id)
	return err
}

const createBirthdayReward = `-- name: CreateBirthdayReward :one
INSERT INTO birthday_rewards (id, member_id, points, granted_at)
VALUES ($1, $2, $3, $4)
RETURNING id, member_id, points, granted_at
`

type CreateBirthdayRewardParams struct {
	ID        uuid.UUID
	MemberID  uuid.UUID
	Points    int32
	GrantedAt time.Time
}

func (q *Queries) CreateBirthdayReward(ctx context.Context, arg CreateBirthdayRewardParams) (BirthdayReward, error) {
	row := q.db.QueryRowContext(ctx, createBirthdayReward, arg.ID, arg.MemberID, arg.Points, arg.GrantedAt)
	var i BirthdayReward
	err := row.Scan(&i.ID, &i.MemberID, &i.Points, &i.GrantedAt)
	return i, err
}

const getBirthdayReward = `-- name: GetBirthdayReward :one
SELECT id, member_id, points, granted_at FROM birthday_rewards WHERE id = $1
`

func (q *Queries) GetBirthdayReward(ctx context.Context, id uuid.UUID) (BirthdayReward, error) {
	row := q.db.QueryRowContext(ctx, getBirthdayReward, id)
	var i BirthdayReward
	err := row.Scan(&i.ID, &i.MemberID, &i.Points, &i.GrantedAt)
	return i, err
}

const listBirthdayRewards = `-- name: ListBirthdayRewards :many
SELECT id, member_id, points, granted_at FROM birthday_rewards ORDER BY granted_at DESC
`

func (q *Queries) ListBirthdayRewards(ctx context.Context) ([]BirthdayReward, error) {
	rows, err := q.db.QueryContext(ctx, listBirthdayRewards)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []BirthdayReward
	for rows.Next() {
		var i BirthdayReward
		if err := rows.Scan(&i.ID, &i.MemberID, &i.Points, &i.GrantedAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listBirthdayRewardsByMemberID = `-- name: ListBirthdayRewardsByMemberID :many
SELECT id, member_id, points, granted_at FROM birthday_rewards WHERE member_id = $1 ORDER BY granted_at DESC
`

func (q *Queries) ListBirthdayRewardsByMemberID(ctx context.Context, memberID uuid.UUID) ([]BirthdayReward, error) {
	rows, err := q.db.QueryContext(ctx, listBirthdayRewardsByMemberID, memberID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []BirthdayReward
	for rows.Next() {
		var i BirthdayReward
		if err := rows.Scan(&i.ID, &i.MemberID, &i.Points, &i.GrantedAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const deleteBirthdayReward = `-- name: DeleteBirthdayReward :exec
DELETE FROM birthday_rewards WHERE id = $1
`

func (q *Queries) DeleteBirthdayReward(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, deleteBirthdayReward, id)
	return err
}

const createLoyaltyPointExpiration = `-- name: CreateLoyaltyPointExpiration :one
INSERT INTO loyalty_point_expirations (id, member_id, points, expires_at)
VALUES ($1, $2, $3, $4)
RETURNING id, member_id, points, expires_at
`

type CreateLoyaltyPointExpirationParams struct {
	ID        uuid.UUID
	MemberID  uuid.UUID
	Points    int32
	ExpiresAt time.Time
}

func (q *Queries) CreateLoyaltyPointExpiration(ctx context.Context, arg CreateLoyaltyPointExpirationParams) (LoyaltyPointExpiration, error) {
	row := q.db.QueryRowContext(ctx, createLoyaltyPointExpiration, arg.ID, arg.MemberID, arg.Points, arg.ExpiresAt)
	var i LoyaltyPointExpiration
	err := row.Scan(&i.ID, &i.MemberID, &i.Points, &i.ExpiresAt)
	return i, err
}

const getLoyaltyPointExpiration = `-- name: GetLoyaltyPointExpiration :one
SELECT id, member_id, points, expires_at FROM loyalty_point_expirations WHERE id = $1
`

func (q *Queries) GetLoyaltyPointExpiration(ctx context.Context, id uuid.UUID) (LoyaltyPointExpiration, error) {
	row := q.db.QueryRowContext(ctx, getLoyaltyPointExpiration, id)
	var i LoyaltyPointExpiration
	err := row.Scan(&i.ID, &i.MemberID, &i.Points, &i.ExpiresAt)
	return i, err
}

const listLoyaltyPointExpirations = `-- name: ListLoyaltyPointExpirations :many
SELECT id, member_id, points, expires_at FROM loyalty_point_expirations ORDER BY expires_at DESC
`

func (q *Queries) ListLoyaltyPointExpirations(ctx context.Context) ([]LoyaltyPointExpiration, error) {
	rows, err := q.db.QueryContext(ctx, listLoyaltyPointExpirations)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []LoyaltyPointExpiration
	for rows.Next() {
		var i LoyaltyPointExpiration
		if err := rows.Scan(&i.ID, &i.MemberID, &i.Points, &i.ExpiresAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listLoyaltyPointExpirationsByMemberID = `-- name: ListLoyaltyPointExpirationsByMemberID :many
SELECT id, member_id, points, expires_at FROM loyalty_point_expirations WHERE member_id = $1 ORDER BY expires_at DESC
`

func (q *Queries) ListLoyaltyPointExpirationsByMemberID(ctx context.Context, memberID uuid.UUID) ([]LoyaltyPointExpiration, error) {
	rows, err := q.db.QueryContext(ctx, listLoyaltyPointExpirationsByMemberID, memberID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []LoyaltyPointExpiration
	for rows.Next() {
		var i LoyaltyPointExpiration
		if err := rows.Scan(&i.ID, &i.MemberID, &i.Points, &i.ExpiresAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const deleteLoyaltyPointExpiration = `-- name: DeleteLoyaltyPointExpiration :exec
DELETE FROM loyalty_point_expirations WHERE id = $1
`

func (q *Queries) DeleteLoyaltyPointExpiration(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, deleteLoyaltyPointExpiration, id)
	return err
}
