// Code generated by sqlc. DO NOT EDIT.
package sqlc

import (
	"time"

	"github.com/google/uuid"
)

type LoyaltyProgram struct {
	ID        uuid.UUID
	Name      string
	CreatedAt time.Time
}

type LoyaltyTier struct {
	ID               uuid.UUID
	LoyaltyProgramID uuid.UUID
	Name             string
	MinPoints        int32
}

type PointRule struct {
	ID               uuid.UUID
	LoyaltyProgramID uuid.UUID
	Action           string
	Points           int32
}

type PointRedemption struct {
	ID         uuid.UUID
	MemberID   uuid.UUID
	Points     int32
	RedeemedAt time.Time
}

type LoyaltyTierHistory struct {
	ID            uuid.UUID
	MemberID      uuid.UUID
	LoyaltyTierID uuid.UUID
	ChangedAt     time.Time
}

type RewardItem struct {
	ID         uuid.UUID
	Name       string
	PointsCost int32
}

type RewardRedemption struct {
	ID           uuid.UUID
	MemberID     uuid.UUID
	RewardItemID uuid.UUID
	RedeemedAt   time.Time
}

type ReferralBonus struct {
	ID        uuid.UUID
	MemberID  uuid.UUID
	Points    int32
	GrantedAt time.Time
}

type BirthdayReward struct {
	ID        uuid.UUID
	MemberID  uuid.UUID
	Points    int32
	GrantedAt time.Time
}

type LoyaltyPointExpiration struct {
	ID        uuid.UUID
	MemberID  uuid.UUID
	Points    int32
	ExpiresAt time.Time
}
