// Code generated by sqlc. DO NOT EDIT.
package sqlc

import (
	"time"

	"github.com/google/uuid"
)

type Payment struct {
	ID        uuid.UUID
	OrderID   uuid.UUID
	AmountYen int32
	Method    string
	PaidAt    time.Time
}

type PaymentMethod struct {
	ID        uuid.UUID
	MemberID  uuid.UUID
	Type      string
	IsDefault bool
	CreatedAt time.Time
}

type PaymentTransaction struct {
	ID          uuid.UUID
	PaymentID   uuid.UUID
	Status      string
	ProcessedAt time.Time
}

type Refund struct {
	ID         uuid.UUID
	PaymentID  uuid.UUID
	AmountYen  int32
	Reason     string
	RefundedAt time.Time
}

type Invoice struct {
	ID        uuid.UUID
	OrderID   uuid.UUID
	AmountYen int32
	IssuedAt  time.Time
}

type PaymentProvider struct {
	ID   uuid.UUID
	Name string
}

type PaymentProviderAccount struct {
	ID                 uuid.UUID
	PaymentProviderID  uuid.UUID
	MemberID           uuid.UUID
	ExternalAccountID  string
}

type InstallmentPlan struct {
	ID                   uuid.UUID
	PaymentID            uuid.UUID
	NumberOfInstallments int32
}

type InstallmentPayment struct {
	ID                uuid.UUID
	InstallmentPlanID uuid.UUID
	AmountYen         int32
	DueAt             time.Time
	PaidAt            time.Time
}

type PaymentDispute struct {
	ID        uuid.UUID
	PaymentID uuid.UUID
	Reason    string
	Status    string
	CreatedAt time.Time
}
