// Code generated by sqlc. DO NOT EDIT.
package sqlc

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const createPayment = `-- name: CreatePayment :one
INSERT INTO payments (id, order_id, amount_yen, method, paid_at)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, order_id, amount_yen, method, paid_at
`

type CreatePaymentParams struct {
	ID        uuid.UUID
	OrderID   uuid.UUID
	AmountYen int32
	Method    string
	PaidAt    time.Time
}

func (q *Queries) CreatePayment(ctx context.Context, arg CreatePaymentParams) (Payment, error) {
	row := q.db.QueryRowContext(ctx, createPayment, arg.ID, arg.OrderID, arg.AmountYen, arg.Method, arg.PaidAt)
	var i Payment
	err := row.Scan(&i.ID, &i.OrderID, &i.AmountYen, &i.Method, &i.PaidAt)
	return i, err
}

const getPayment = `-- name: GetPayment :one
SELECT id, order_id, amount_yen, method, paid_at FROM payments WHERE id = $1
`

func (q *Queries) GetPayment(ctx context.Context, id uuid.UUID) (Payment, error) {
	row := q.db.QueryRowContext(ctx, getPayment, id)
	var i Payment
	err := row.Scan(&i.ID, &i.OrderID, &i.AmountYen, &i.Method, &i.PaidAt)
	return i, err
}

const listPayments = `-- name: ListPayments :many
SELECT id, order_id, amount_yen, method, paid_at FROM payments ORDER BY paid_at DESC
`

func (q *Queries) ListPayments(ctx context.Context) ([]Payment, error) {
	rows, err := q.db.QueryContext(ctx, listPayments)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Payment
	for rows.Next() {
		var i Payment
		if err := rows.Scan(&i.ID, &i.OrderID, &i.AmountYen, &i.Method, &i.PaidAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const createPaymentMethod = `-- name: CreatePaymentMethod :one
INSERT INTO payment_methods (id, member_id, type, is_default, created_at)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, member_id, type, is_default, created_at
`

type CreatePaymentMethodParams struct {
	ID        uuid.UUID
	MemberID  uuid.UUID
	Type      string
	IsDefault bool
	CreatedAt time.Time
}

func (q *Queries) CreatePaymentMethod(ctx context.Context, arg CreatePaymentMethodParams) (PaymentMethod, error) {
	row := q.db.QueryRowContext(ctx, createPaymentMethod, arg.ID, arg.MemberID, arg.Type, arg.IsDefault, arg.CreatedAt)
	var i PaymentMethod
	err := row.Scan(&i.ID, &i.MemberID, &i.Type, &i.IsDefault, &i.CreatedAt)
	return i, err
}

const getPaymentMethod = `-- name: GetPaymentMethod :one
SELECT id, member_id, type, is_default, created_at FROM payment_methods WHERE id = $1
`

func (q *Queries) GetPaymentMethod(ctx context.Context, id uuid.UUID) (PaymentMethod, error) {
	row := q.db.QueryRowContext(ctx, getPaymentMethod, id)
	var i PaymentMethod
	err := row.Scan(&i.ID, &i.MemberID, &i.Type, &i.IsDefault, &i.CreatedAt)
	return i, err
}

const listPaymentMethods = `-- name: ListPaymentMethods :many
SELECT id, member_id, type, is_default, created_at FROM payment_methods ORDER BY created_at DESC
`

func (q *Queries) ListPaymentMethods(ctx context.Context) ([]PaymentMethod, error) {
	rows, err := q.db.QueryContext(ctx, listPaymentMethods)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []PaymentMethod
	for rows.Next() {
		var i PaymentMethod
		if err := rows.Scan(&i.ID, &i.MemberID, &i.Type, &i.IsDefault, &i.CreatedAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPaymentMethodsByMemberID = `-- name: ListPaymentMethodsByMemberID :many
SELECT id, member_id, type, is_default, created_at FROM payment_methods WHERE member_id = $1 ORDER BY created_at DESC
`

func (q *Queries) ListPaymentMethodsByMemberID(ctx context.Context, memberID uuid.UUID) ([]PaymentMethod, error) {
	rows, err := q.db.QueryContext(ctx, listPaymentMethodsByMemberID, memberID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []PaymentMethod
	for rows.Next() {
		var i PaymentMethod
		if err := rows.Scan(&i.ID, &i.MemberID, &i.Type, &i.IsDefault, &i.CreatedAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const deletePaymentMethod = `-- name: DeletePaymentMethod :exec
DELETE FROM payment_methods WHERE id = $1
`

func (q *Queries) DeletePaymentMethod(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, deletePaymentMethod, id)
	return err
}

const createPaymentTransaction = `-- name: CreatePaymentTransaction :one
INSERT INTO payment_transactions (id, payment_id, status, processed_at)
VALUES ($1, $2, $3, $4)
RETURNING id, payment_id, status, processed_at
`

type CreatePaymentTransactionParams struct {
	ID          uuid.UUID
	PaymentID   uuid.UUID
	Status      string
	ProcessedAt time.Time
}

func (q *Queries) CreatePaymentTransaction(ctx context.Context, arg CreatePaymentTransactionParams) (PaymentTransaction, error) {
	row := q.db.QueryRowContext(ctx, createPaymentTransaction, arg.ID, arg.PaymentID, arg.Status, arg.ProcessedAt)
	var i PaymentTransaction
	err := row.Scan(&i.ID, &i.PaymentID, &i.Status, &i.ProcessedAt)
	return i, err
}

const getPaymentTransaction = `-- name: GetPaymentTransaction :one
SELECT id, payment_id, status, processed_at FROM payment_transactions WHERE id = $1
`

func (q *Queries) GetPaymentTransaction(ctx context.Context, id uuid.UUID) (PaymentTransaction, error) {
	row := q.db.QueryRowContext(ctx, getPaymentTransaction, id)
	var i PaymentTransaction
	err := row.Scan(&i.ID, &i.PaymentID, &i.Status, &i.ProcessedAt)
	return i, err
}

const listPaymentTransactions = `-- name: ListPaymentTransactions :many
SELECT id, payment_id, status, processed_at FROM payment_transactions ORDER BY processed_at DESC
`

func (q *Queries) ListPaymentTransactions(ctx context.Context) ([]PaymentTransaction, error) {
	rows, err := q.db.QueryContext(ctx, listPaymentTransactions)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []PaymentTransaction
	for rows.Next() {
		var i PaymentTransaction
		if err := rows.Scan(&i.ID, &i.PaymentID, &i.Status, &i.ProcessedAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPaymentTransactionsByPaymentID = `-- name: ListPaymentTransactionsByPaymentID :many
SELECT id, payment_id, status, processed_at FROM payment_transactions WHERE payment_id = $1 ORDER BY processed_at DESC
`

func (q *Queries) ListPaymentTransactionsByPaymentID(ctx context.Context, paymentID uuid.UUID) ([]PaymentTransaction, error) {
	rows, err := q.db.QueryContext(ctx, listPaymentTransactionsByPaymentID, paymentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []PaymentTransaction
	for rows.Next() {
		var i PaymentTransaction
		if err := rows.Scan(&i.ID, &i.PaymentID, &i.Status, &i.ProcessedAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const deletePaymentTransaction = `-- name: DeletePaymentTransaction :exec
DELETE FROM payment_transactions WHERE id = $1
`

func (q *Queries) DeletePaymentTransaction(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, deletePaymentTransaction, id)
	return err
}

const createRefund = `-- name: CreateRefund :one
INSERT INTO refunds (id, payment_id, amount_yen, reason, refunded_at)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, payment_id, amount_yen, reason, refunded_at
`

type CreateRefundParams struct {
	ID         uuid.UUID
	PaymentID  uuid.UUID
	AmountYen  int32
	Reason     string
	RefundedAt time.Time
}

func (q *Queries) CreateRefund(ctx context.Context, arg CreateRefundParams) (Refund, error) {
	row := q.db.QueryRowContext(ctx, createRefund, arg.ID, arg.PaymentID, arg.AmountYen, arg.Reason, arg.RefundedAt)
	var i Refund
	err := row.Scan(&i.ID, &i.PaymentID, &i.AmountYen, &i.Reason, &i.RefundedAt)
	return i, err
}

const getRefund = `-- name: GetRefund :one
SELECT id, payment_id, amount_yen, reason, refunded_at FROM refunds WHERE id = $1
`

func (q *Queries) GetRefund(ctx context.Context, id uuid.UUID) (Refund, error) {
	row := q.db.QueryRowContext(ctx, getRefund, id)
	var i Refund
	err := row.Scan(&i.ID, &i.PaymentID, &i.AmountYen, &i.Reason, &i.RefundedAt)
	return i, err
}

const listRefunds = `-- name: ListRefunds :many
SELECT id, payment_id, amount_yen, reason, refunded_at FROM refunds ORDER BY refunded_at DESC
`

func (q *Queries) ListRefunds(ctx context.Context) ([]Refund, error) {
	rows, err := q.db.QueryContext(ctx, listRefunds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Refund
	for rows.Next() {
		var i Refund
		if err := rows.Scan(&i.ID, &i.PaymentID, &i.AmountYen, &i.Reason, &i.RefundedAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRefundsByPaymentID = `-- name: ListRefundsByPaymentID :many
SELECT id, payment_id, amount_yen, reason, refunded_at FROM refunds WHERE payment_id = $1 ORDER BY refunded_at DESC
`

func (q *Queries) ListRefundsByPaymentID(ctx context.Context, paymentID uuid.UUID) ([]Refund, error) {
	rows, err := q.db.QueryContext(ctx, listRefundsByPaymentID, paymentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Refund
	for rows.Next() {
		var i Refund
		if err := rows.Scan(&i.ID, &i.PaymentID, &i.AmountYen, &i.Reason, &i.RefundedAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const deleteRefund = `-- name: DeleteRefund :exec
DELETE FROM refunds WHERE id = $1
`

func (q *Queries) DeleteRefund(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, deleteRefund, id)
	return err
}

const createInvoice = `-- name: CreateInvoice :one
INSERT INTO invoices (id, order_id, amount_yen, issued_at)
VALUES ($1, $2, $3, $4)
RETURNING id, order_id, amount_yen, issued_at
`

type CreateInvoiceParams struct {
	ID        uuid.UUID
	OrderID   uuid.UUID
	AmountYen int32
	IssuedAt  time.Time
}

func (q *Queries) CreateInvoice(ctx context.Context, arg CreateInvoiceParams) (Invoice, error) {
	row := q.db.QueryRowContext(ctx, createInvoice, arg.ID, arg.OrderID, arg.AmountYen, arg.IssuedAt)
	var i Invoice
	err := row.Scan(&i.ID, &i.OrderID, &i.AmountYen, &i.IssuedAt)
	return i, err
}

const getInvoice = `-- name: GetInvoice :one
SELECT id, order_id, amount_yen, issued_at FROM invoices WHERE id = $1
`

func (q *Queries) GetInvoice(ctx context.Context, id uuid.UUID) (Invoice, error) {
	row := q.db.QueryRowContext(ctx, getInvoice, id)
	var i Invoice
	err := row.Scan(&i.ID, &i.OrderID, &i.AmountYen, &i.IssuedAt)
	return i, err
}

const listInvoices = `-- name: ListInvoices :many
SELECT id, order_id, amount_yen, issued_at FROM invoices ORDER BY issued_at DESC
`

func (q *Queries) ListInvoices(ctx context.Context) ([]Invoice, error) {
	rows, err := q.db.QueryContext(ctx, listInvoices)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Invoice
	for rows.Next() {
		var i Invoice
		if err := rows.Scan(&i.ID, &i.OrderID, &i.AmountYen, &i.IssuedAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listInvoicesByOrderID = `-- name: ListInvoicesByOrderID :many
SELECT id, order_id, amount_yen, issued_at FROM invoices WHERE order_id = $1 ORDER BY issued_at DESC
`

func (q *Queries) ListInvoicesByOrderID(ctx context.Context, orderID uuid.UUID) ([]Invoice, error) {
	rows, err := q.db.QueryContext(ctx, listInvoicesByOrderID, orderID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Invoice
	for rows.Next() {
		var i Invoice
		if err := rows.Scan(&i.ID, &i.OrderID, &i.AmountYen, &i.IssuedAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const deleteInvoice = `-- name: DeleteInvoice :exec
DELETE FROM invoices WHERE id = $1
`

func (q *Queries) DeleteInvoice(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, deleteInvoice, id)
	return err
}

const createPaymentProvider = `-- name: CreatePaymentProvider :one
INSERT INTO payment_providers (id, name)
VALUES ($1, $2)
RETURNING id, name
`

type CreatePaymentProviderParams struct {
	ID   uuid.UUID
	Name string
}

func (q *Queries) CreatePaymentProvider(ctx context.Context, arg CreatePaymentProviderParams) (PaymentProvider, error) {
	row := q.db.QueryRowContext(ctx, createPaymentProvider, arg.ID, arg.Name)
	var i PaymentProvider
	err := row.Scan(&i.ID, &i.Name)
	return i, err
}

const getPaymentProvider = `-- name: GetPaymentProvider :one
SELECT id, name FROM payment_providers WHERE id = $1
`

func (q *Queries) GetPaymentProvider(ctx context.Context, id uuid.UUID) (PaymentProvider, error) {
	row := q.db.QueryRowContext(ctx, getPaymentProvider, id)
	var i PaymentProvider
	err := row.Scan(&i.ID, &i.Name)
	return i, err
}

const listPaymentProviders = `-- name: ListPaymentProviders :many
SELECT id, name FROM payment_providers ORDER BY id DESC
`

func (q *Queries) ListPaymentProviders(ctx context.Context) ([]PaymentProvider, error) {
	rows, err := q.db.QueryContext(ctx, listPaymentProviders)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []PaymentProvider
	for rows.Next() {
		var i PaymentProvider
		if err := rows.Scan(&i.ID, &i.Name); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const deletePaymentProvider = `-- name: DeletePaymentProvider :exec
DELETE FROM payment_providers WHERE id = $1
`

func (q *Queries) DeletePaymentProvider(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, deletePaymentProvider, id)
	return err
}

const createPaymentProviderAccount = `-- name: CreatePaymentProviderAccount :one
INSERT INTO payment_provider_accounts (id, payment_provider_id, member_id, external_account_id)
VALUES ($1, $2, $3, $4)
RETURNING id, payment_provider_id, member_id, external_account_id
`

type CreatePaymentProviderAccountParams struct {
	ID                 uuid.UUID
	PaymentProviderID  uuid.UUID
	MemberID           uuid.UUID
	ExternalAccountID  string
}

func (q *Queries) CreatePaymentProviderAccount(ctx context.Context, arg CreatePaymentProviderAccountParams) (PaymentProviderAccount, error) {
	row := q.db.QueryRowContext(ctx, createPaymentProviderAccount, arg.ID, arg.PaymentProviderID, arg.MemberID, arg.ExternalAccountID)
	var i PaymentProviderAccount
	err := row.Scan(&i.ID, &i.PaymentProviderID, &i.MemberID, &i.ExternalAccountID)
	return i, err
}

const getPaymentProviderAccount = `-- name: GetPaymentProviderAccount :one
SELECT id, payment_provider_id, member_id, external_account_id FROM payment_provider_accounts WHERE id = $1
`

func (q *Queries) GetPaymentProviderAccount(ctx context.Context, id uuid.UUID) (PaymentProviderAccount, error) {
	row := q.db.QueryRowContext(ctx, getPaymentProviderAccount, id)
	var i PaymentProviderAccount
	err := row.Scan(&i.ID, &i.PaymentProviderID, &i.MemberID, &i.ExternalAccountID)
	return i, err
}

const listPaymentProviderAccounts = `-- name: ListPaymentProviderAccounts :many
SELECT id, payment_provider_id, member_id, external_account_id FROM payment_provider_accounts ORDER BY id DESC
`

func (q *Queries) ListPaymentProviderAccounts(ctx context.Context) ([]PaymentProviderAccount, error) {
	rows, err := q.db.QueryContext(ctx, listPaymentProviderAccounts)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []PaymentProviderAccount
	for rows.Next() {
		var i PaymentProviderAccount
		if err := rows.Scan(&i.ID, &i.PaymentProviderID, &i.MemberID, &i.ExternalAccountID); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPaymentProviderAccountsByPaymentProviderID = `-- name: ListPaymentProviderAccountsByPaymentProviderID :many
SELECT id, payment_provider_id, member_id, external_account_id FROM payment_provider_accounts WHERE payment_provider_id = $1 ORDER BY id DESC
`

func (q *Queries) ListPaymentProviderAccountsByPaymentProviderID(ctx context.Context, paymentProviderID uuid.UUID) ([]PaymentProviderAccount, error) {
	rows, err := q.db.QueryContext(ctx, listPaymentProviderAccountsByPaymentProviderID, paymentProviderID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []PaymentProviderAccount
	for rows.Next() {
		var i PaymentProviderAccount
		if err := rows.Scan(&i.ID, &i.PaymentProviderID, &i.MemberID, &i.ExternalAccountID); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPaymentProviderAccountsByMemberID = `-- name: ListPaymentProviderAccountsByMemberID :many
SELECT id, payment_provider_id, member_id, external_account_id FROM payment_provider_accounts WHERE member_id = $1 ORDER BY id DESC
`

func (q *Queries) ListPaymentProviderAccountsByMemberID(ctx context.Context, memberID uuid.UUID) ([]PaymentProviderAccount, error) {
	rows, err := q.db.QueryContext(ctx, listPaymentProviderAccountsByMemberID, memberID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []PaymentProviderAccount
	for rows.Next() {
		var i PaymentProviderAccount
		if err := rows.Scan(&i.ID, &i.PaymentProviderID, &i.MemberID, &i.ExternalAccountID); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const deletePaymentProviderAccount = `-- name: DeletePaymentProviderAccount :exec
DELETE FROM payment_provider_accounts WHERE id = $1
`

func (q *Queries) DeletePaymentProviderAccount(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, deletePaymentProviderAccount, id)
	return err
}

const createInstallmentPlan = `-- name: CreateInstallmentPlan :one
INSERT INTO installment_plans (id, payment_id, number_of_installments)
VALUES ($1, $2, $3)
RETURNING id, payment_id, number_of_installments
`

type CreateInstallmentPlanParams struct {
	ID                   uuid.UUID
	PaymentID            uuid.UUID
	NumberOfInstallments int32
}

func (q *Queries) CreateInstallmentPlan(ctx context.Context, arg CreateInstallmentPlanParams) (InstallmentPlan, error) {
	row := q.db.QueryRowContext(ctx, createInstallmentPlan, arg.ID, arg.PaymentID, arg.NumberOfInstallments)
	var i InstallmentPlan
	err := row.Scan(&i.ID, &i.PaymentID, &i.NumberOfInstallments)
	return i, err
}

const getInstallmentPlan = `-- name: GetInstallmentPlan :one
SELECT id, payment_id, number_of_installments FROM installment_plans WHERE id = $1
`

func (q *Queries) GetInstallmentPlan(ctx context.Context, id uuid.UUID) (InstallmentPlan, error) {
	row := q.db.QueryRowContext(ctx, getInstallmentPlan, id)
	var i InstallmentPlan
	err := row.Scan(&i.ID, &i.PaymentID, &i.NumberOfInstallments)
	return i, err
}

const listInstallmentPlans = `-- name: ListInstallmentPlans :many
SELECT id, payment_id, number_of_installments FROM installment_plans ORDER BY id DESC
`

func (q *Queries) ListInstallmentPlans(ctx context.Context) ([]InstallmentPlan, error) {
	rows, err := q.db.QueryContext(ctx, listInstallmentPlans)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []InstallmentPlan
	for rows.Next() {
		var i InstallmentPlan
		if err := rows.Scan(&i.ID, &i.PaymentID, &i.NumberOfInstallments); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listInstallmentPlansByPaymentID = `-- name: ListInstallmentPlansByPaymentID :many
SELECT id, payment_id, number_of_installments FROM installment_plans WHERE payment_id = $1 ORDER BY id DESC
`

func (q *Queries) ListInstallmentPlansByPaymentID(ctx context.Context, paymentID uuid.UUID) ([]InstallmentPlan, error) {
	rows, err := q.db.QueryContext(ctx, listInstallmentPlansByPaymentID, paymentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []InstallmentPlan
	for rows.Next() {
		var i InstallmentPlan
		if err := rows.Scan(&i.ID, &i.PaymentID, &i.NumberOfInstallments); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const deleteInstallmentPlan = `-- name: DeleteInstallmentPlan :exec
DELETE FROM installment_plans WHERE id = $1
`

func (q *Queries) DeleteInstallmentPlan(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, deleteInstallmentPlan, id)
	return err
}

const createInstallmentPayment = `-- name: CreateInstallmentPayment :one
INSERT INTO installment_payments (id, installment_plan_id, amount_yen, due_at, paid_at)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, installment_plan_id, amount_yen, due_at, paid_at
`

type CreateInstallmentPaymentParams struct {
	ID                uuid.UUID
	InstallmentPlanID uuid.UUID
	AmountYen         int32
	DueAt             time.Time
	PaidAt            time.Time
}

func (q *Queries) CreateInstallmentPayment(ctx context.Context, arg CreateInstallmentPaymentParams) (InstallmentPayment, error) {
	row := q.db.QueryRowContext(ctx, createInstallmentPayment, arg.ID, arg.InstallmentPlanID, arg.AmountYen, arg.DueAt, arg.PaidAt)
	var i InstallmentPayment
	err := row.Scan(&i.ID, &i.InstallmentPlanID, &i.AmountYen, &i.DueAt, &i.PaidAt)
	return i, err
}

const getInstallmentPayment = `-- name: GetInstallmentPayment :one
SELECT id, installment_plan_id, amount_yen, due_at, paid_at FROM installment_payments WHERE id = $1
`

func (q *Queries) GetInstallmentPayment(ctx context.Context, id uuid.UUID) (InstallmentPayment, error) {
	row := q.db.QueryRowContext(ctx, getInstallmentPayment, id)
	var i InstallmentPayment
	err := row.Scan(&i.ID, &i.InstallmentPlanID, &i.AmountYen, &i.DueAt, &i.PaidAt)
	return i, err
}

const listInstallmentPayments = `-- name: ListInstallmentPayments :many
SELECT id, installment_plan_id, amount_yen, due_at, paid_at FROM installment_payments ORDER BY due_at DESC
`

func (q *Queries) ListInstallmentPayments(ctx context.Context) ([]InstallmentPayment, error) {
	rows, err := q.db.QueryContext(ctx, listInstallmentPayments)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []InstallmentPayment
	for rows.Next() {
		var i InstallmentPayment
		if err := rows.Scan(&i.ID, &i.InstallmentPlanID, &i.AmountYen, &i.DueAt, &i.PaidAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listInstallmentPaymentsByInstallmentPlanID = `-- name: ListInstallmentPaymentsByInstallmentPlanID :many
SELECT id, installment_plan_id, amount_yen, due_at, paid_at FROM installment_payments WHERE installment_plan_id = $1 ORDER BY due_at DESC
`

func (q *Queries) ListInstallmentPaymentsByInstallmentPlanID(ctx context.Context, installmentPlanID uuid.UUID) ([]InstallmentPayment, error) {
	rows, err := q.db.QueryContext(ctx, listInstallmentPaymentsByInstallmentPlanID, installmentPlanID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []InstallmentPayment
	for rows.Next() {
		var i InstallmentPayment
		if err := rows.Scan(&i.ID, &i.InstallmentPlanID, &i.AmountYen, &i.DueAt, &i.PaidAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const deleteInstallmentPayment = `-- name: DeleteInstallmentPayment :exec
DELETE FROM installment_payments WHERE id = $1
`

func (q *Queries) DeleteInstallmentPayment(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, deleteInstallmentPayment, id)
	return err
}

const createPaymentDispute = `-- name: CreatePaymentDispute :one
INSERT INTO payment_disputes (id, payment_id, reason, status, created_at)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, payment_id, reason, status, created_at
`

type CreatePaymentDisputeParams struct {
	ID        uuid.UUID
	PaymentID uuid.UUID
	Reason    string
	Status    string
	CreatedAt time.Time
}

func (q *Queries) CreatePaymentDispute(ctx context.Context, arg CreatePaymentDisputeParams) (PaymentDispute, error) {
	row := q.db.QueryRowContext(ctx, createPaymentDispute, arg.ID, arg.PaymentID, arg.Reason, arg.Status, arg.CreatedAt)
	var i PaymentDispute
	err := row.Scan(&i.ID, &i.PaymentID, &i.Reason, &i.Status, &i.CreatedAt)
	return i, err
}

const getPaymentDispute = `-- name: GetPaymentDispute :one
SELECT id, payment_id, reason, status, created_at FROM payment_disputes WHERE id = $1
`

func (q *Queries) GetPaymentDispute(ctx context.Context, id uuid.UUID) (PaymentDispute, error) {
	row := q.db.QueryRowContext(ctx, getPaymentDispute, id)
	var i PaymentDispute
	err := row.Scan(&i.ID, &i.PaymentID, &i.Reason, &i.Status, &i.CreatedAt)
	return i, err
}

const listPaymentDisputes = `-- name: ListPaymentDisputes :many
SELECT id, payment_id, reason, status, created_at FROM payment_disputes ORDER BY created_at DESC
`

func (q *Queries) ListPaymentDisputes(ctx context.Context) ([]PaymentDispute, error) {
	rows, err := q.db.QueryContext(ctx, listPaymentDisputes)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []PaymentDispute
	for rows.Next() {
		var i PaymentDispute
		if err := rows.Scan(&i.ID, &i.PaymentID, &i.Reason, &i.Status, &i.CreatedAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPaymentDisputesByPaymentID = `-- name: ListPaymentDisputesByPaymentID :many
SELECT id, payment_id, reason, status, created_at FROM payment_disputes WHERE payment_id = $1 ORDER BY created_at DESC
`

func (q *Queries) ListPaymentDisputesByPaymentID(ctx context.Context, paymentID uuid.UUID) ([]PaymentDispute, error) {
	rows, err := q.db.QueryContext(ctx, listPaymentDisputesByPaymentID, paymentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []PaymentDispute
	for rows.Next() {
		var i PaymentDispute
		if err := rows.Scan(&i.ID, &i.PaymentID, &i.Reason, &i.Status, &i.CreatedAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const deletePaymentDispute = `-- name: DeletePaymentDispute :exec
DELETE FROM payment_disputes WHERE id = $1
`

func (q *Queries) DeletePaymentDispute(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, deletePaymentDispute, id)
	return err
}
