// Code generated by sqlc. DO NOT EDIT.
package sqlc

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const createMember = `-- name: CreateMember :one
INSERT INTO members (id, name, email, created_at)
VALUES ($1, $2, $3, $4)
RETURNING id, name, email, created_at
`

type CreateMemberParams struct {
	ID        uuid.UUID
	Name      string
	Email     string
	CreatedAt time.Time
}

func (q *Queries) CreateMember(ctx context.Context, arg CreateMemberParams) (Member, error) {
	row := q.db.QueryRowContext(ctx, createMember, arg.ID, arg.Name, arg.Email, arg.CreatedAt)
	var i Member
	err := row.Scan(&i.ID, &i.Name, &i.Email, &i.CreatedAt)
	return i, err
}

const getMember = `-- name: GetMember :one
SELECT id, name, email, created_at FROM members WHERE id = $1
`

func (q *Queries) GetMember(ctx context.Context, id uuid.UUID) (Member, error) {
	row := q.db.QueryRowContext(ctx, getMember, id)
	var i Member
	err := row.Scan(&i.ID, &i.Name, &i.Email, &i.CreatedAt)
	return i, err
}

const listMembers = `-- name: ListMembers :many
SELECT id, name, email, created_at FROM members ORDER BY created_at DESC
`

func (q *Queries) ListMembers(ctx context.Context) ([]Member, error) {
	rows, err := q.db.QueryContext(ctx, listMembers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Member
	for rows.Next() {
		var i Member
		if err := rows.Scan(&i.ID, &i.Name, &i.Email, &i.CreatedAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const createMemberProfile = `-- name: CreateMemberProfile :one
INSERT INTO member_profiles (id, member_id, birth_date, gender, bio, avatar_url, updated_at)
VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id, member_id, birth_date, gender, bio, avatar_url, updated_at
`

type CreateMemberProfileParams struct {
	ID        uuid.UUID
	MemberID  uuid.UUID
	BirthDate time.Time
	Gender    string
	Bio       string
	AvatarURL string
	UpdatedAt time.Time
}

func (q *Queries) CreateMemberProfile(ctx context.Context, arg CreateMemberProfileParams) (MemberProfile, error) {
	row := q.db.QueryRowContext(ctx, createMemberProfile, arg.ID, arg.MemberID, arg.BirthDate, arg.Gender, arg.Bio, arg.AvatarURL, arg.UpdatedAt)
	var i MemberProfile
	err := row.Scan(&i.ID, &i.MemberID, &i.BirthDate, &i.Gender, &i.Bio, &i.AvatarURL, &i.UpdatedAt)
	return i, err
}

const getMemberProfile = `-- name: GetMemberProfile :one
SELECT id, member_id, birth_date, gender, bio, avatar_url, updated_at FROM member_profiles WHERE id = $1
`

func (q *Queries) GetMemberProfile(ctx context.Context, id uuid.UUID) (MemberProfile, error) {
	row := q.db.QueryRowContext(ctx, getMemberProfile, id)
	var i MemberProfile
	err := row.Scan(&i.ID, &i.MemberID, &i.BirthDate, &i.Gender, &i.Bio, &i.AvatarURL, &i.UpdatedAt)
	return i, err
}

const listMemberProfiles = `-- name: ListMemberProfiles :many
SELECT id, member_id, birth_date, gender, bio, avatar_url, updated_at FROM member_profiles ORDER BY updated_at DESC
`

func (q *Queries) ListMemberProfiles(ctx context.Context) ([]MemberProfile, error) {
	rows, err := q.db.QueryContext(ctx, listMemberProfiles)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []MemberProfile
	for rows.Next() {
		var i MemberProfile
		if err := rows.Scan(&i.ID, &i.MemberID, &i.BirthDate, &i.Gender, &i.Bio, &i.AvatarURL, &i.UpdatedAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMemberProfilesByMemberID = `-- name: ListMemberProfilesByMemberID :many
SELECT id, member_id, birth_date, gender, bio, avatar_url, updated_at FROM member_profiles WHERE member_id = $1 ORDER BY updated_at DESC
`

func (q *Queries) ListMemberProfilesByMemberID(ctx context.Context, memberID uuid.UUID) ([]MemberProfile, error) {
	rows, err := q.db.QueryContext(ctx, listMemberProfilesByMemberID, memberID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []MemberProfile
	for rows.Next() {
		var i MemberProfile
		if err := rows.Scan(&i.ID, &i.MemberID, &i.BirthDate, &i.Gender, &i.Bio, &i.AvatarURL, &i.UpdatedAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const deleteMemberProfile = `-- name: DeleteMemberProfile :exec
DELETE FROM member_profiles WHERE id = $1
`

func (q *Queries) DeleteMemberProfile(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, deleteMemberProfile, id)
	return err
}

const createMemberAddress = `-- name: CreateMemberAddress :one
INSERT INTO member_addresses (id, member_id, postal_code, prefecture, city, line1, line2, is_default, created_at)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9)
RETURNING id, member_id, postal_code, prefecture, city, line1, line2, is_default, created_at
`

type CreateMemberAddressParams struct {
	ID         uuid.UUID
	MemberID   uuid.UUID
	PostalCode string
	Prefecture string
	City       string
	Line1      string
	Line2      string
	IsDefault  bool
	CreatedAt  time.Time
}

func (q *Queries) CreateMemberAddress(ctx context.Context, arg CreateMemberAddressParams) (MemberAddress, error) {
	row := q.db.QueryRowContext(ctx, createMemberAddress, arg.ID, arg.MemberID, arg.PostalCode, arg.Prefecture, arg.City, arg.Line1, arg.Line2, arg.IsDefault, arg.CreatedAt)
	var i MemberAddress
	err := row.Scan(&i.ID, &i.MemberID, &i.PostalCode, &i.Prefecture, &i.City, &i.Line1, &i.Line2, &i.IsDefault, &i.CreatedAt)
	return i, err
}

const getMemberAddress = `-- name: GetMemberAddress :one
SELECT id, member_id, postal_code, prefecture, city, line1, line2, is_default, created_at FROM member_addresses WHERE id = $1
`

func (q *Queries) GetMemberAddress(ctx context.Context, id uuid.UUID) (MemberAddress, error) {
	row := q.db.QueryRowContext(ctx, getMemberAddress, id)
	var i MemberAddress
	err := row.Scan(&i.ID, &i.MemberID, &i.PostalCode, &i.Prefecture, &i.City, &i.Line1, &i.Line2, &i.IsDefault, &i.CreatedAt)
	return i, err
}

const listMemberAddresses = `-- name: ListMemberAddresses :many
SELECT id, member_id, postal_code, prefecture, city, line1, line2, is_default, created_at FROM member_addresses ORDER BY created_at DESC
`

func (q *Queries) ListMemberAddresses(ctx context.Context) ([]MemberAddress, error) {
	rows, err := q.db.QueryContext(ctx, listMemberAddresses)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []MemberAddress
	for rows.Next() {
		var i MemberAddress
		if err := rows.Scan(&i.ID, &i.MemberID, &i.PostalCode, &i.Prefecture, &i.City, &i.Line1, &i.Line2, &i.IsDefault, &i.CreatedAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMemberAddressesByMemberID = `-- name: ListMemberAddressesByMemberID :many
SELECT id, member_id, postal_code, prefecture, city, line1, line2, is_default, created_at FROM member_addresses WHERE member_id = $1 ORDER BY created_at DESC
`

func (q *Queries) ListMemberAddressesByMemberID(ctx context.Context, memberID uuid.UUID) ([]MemberAddress, error) {
	rows, err := q.db.QueryContext(ctx, listMemberAddressesByMemberID, memberID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []MemberAddress
	for rows.Next() {
		var i MemberAddress
		if err := rows.Scan(&i.ID, &i.MemberID, &i.PostalCode, &i.Prefecture, &i.City, &i.Line1, &i.Line2, &i.IsDefault, &i.CreatedAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const deleteMemberAddress = `-- name: DeleteMemberAddress :exec
DELETE FROM member_addresses WHERE id = $1
`

func (q *Queries) DeleteMemberAddress(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, deleteMemberAddress, id)
	return err
}

const createMemberCredential = `-- name: CreateMemberCredential :one
INSERT INTO member_credentials (id, member_id, password_hash, last_changed_at)
VALUES ($1, $2, $3, $4)
RETURNING id, member_id, password_hash, last_changed_at
`

type CreateMemberCredentialParams struct {
	ID            uuid.UUID
	MemberID      uuid.UUID
	PasswordHash  string
	LastChangedAt time.Time
}

func (q *Queries) CreateMemberCredential(ctx context.Context, arg CreateMemberCredentialParams) (MemberCredential, error) {
	row := q.db.QueryRowContext(ctx, createMemberCredential, arg.ID, arg.MemberID, arg.PasswordHash, arg.LastChangedAt)
	var i MemberCredential
	err := row.Scan(&i.ID, &i.MemberID, &i.PasswordHash, &i.LastChangedAt)
	return i, err
}

const getMemberCredential = `-- name: GetMemberCredential :one
SELECT id, member_id, password_hash, last_changed_at FROM member_credentials WHERE id = $1
`

func (q *Queries) GetMemberCredential(ctx context.Context, id uuid.UUID) (MemberCredential, error) {
	row := q.db.QueryRowContext(ctx, getMemberCredential, id)
	var i MemberCredential
	err := row.Scan(&i.ID, &i.MemberID, &i.PasswordHash, &i.LastChangedAt)
	return i, err
}

const listMemberCredentials = `-- name: ListMemberCredentials :many
SELECT id, member_id, password_hash, last_changed_at FROM member_credentials ORDER BY last_changed_at DESC
`

func (q *Queries) ListMemberCredentials(ctx context.Context) ([]MemberCredential, error) {
	rows, err := q.db.QueryContext(ctx, listMemberCredentials)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []MemberCredential
	for rows.Next() {
		var i MemberCredential
		if err := rows.Scan(&i.ID, &i.MemberID, &i.PasswordHash, &i.LastChangedAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMemberCredentialsByMemberID = `-- name: ListMemberCredentialsByMemberID :many
SELECT id, member_id, password_hash, last_changed_at FROM member_credentials WHERE member_id = $1 ORDER BY last_changed_at DESC
`

func (q *Queries) ListMemberCredentialsByMemberID(ctx context.Context, memberID uuid.UUID) ([]MemberCredential, error) {
	rows, err := q.db.QueryContext(ctx, listMemberCredentialsByMemberID, memberID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []MemberCredential
	for rows.Next() {
		var i MemberCredential
		if err := rows.Scan(&i.ID, &i.MemberID, &i.PasswordHash, &i.LastChangedAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const deleteMemberCredential = `-- name: DeleteMemberCredential :exec
DELETE FROM member_credentials WHERE id = $1
`

func (q *Queries) DeleteMemberCredential(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, deleteMemberCredential, id)
	return err
}

const createMemberSession = `-- name: CreateMemberSession :one
INSERT INTO member_sessions (id, member_id, session_token, expires_at, created_at)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, member_id, session_token, expires_at, created_at
`

type CreateMemberSessionParams struct {
	ID           uuid.UUID
	MemberID     uuid.UUID
	SessionToken string
	ExpiresAt    time.Time
	CreatedAt    time.Time
}

func (q *Queries) CreateMemberSession(ctx context.Context, arg CreateMemberSessionParams) (MemberSession, error) {
	row := q.db.QueryRowContext(ctx, createMemberSession, arg.ID, arg.MemberID, arg.SessionToken, arg.ExpiresAt, arg.CreatedAt)
	var i MemberSession
	err := row.Scan(&i.ID, &i.MemberID, &i.SessionToken, &i.ExpiresAt, &i.CreatedAt)
	return i, err
}

const getMemberSession = `-- name: GetMemberSession :one
SELECT id, member_id, session_token, expires_at, created_at FROM member_sessions WHERE id = $1
`

func (q *Queries) GetMemberSession(ctx context.Context, id uuid.UUID) (MemberSession, error) {
	row := q.db.QueryRowContext(ctx, getMemberSession, id)
	var i MemberSession
	err := row.Scan(&i.ID, &i.MemberID, &i.SessionToken, &i.ExpiresAt, &i.CreatedAt)
	return i, err
}

const listMemberSessions = `-- name: ListMemberSessions :many
SELECT id, member_id, session_token, expires_at, created_at FROM member_sessions ORDER BY created_at DESC
`

func (q *Queries) ListMemberSessions(ctx context.Context) ([]MemberSession, error) {
	rows, err := q.db.QueryContext(ctx, listMemberSessions)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []MemberSession
	for rows.Next() {
		var i MemberSession
		if err := rows.Scan(&i.ID, &i.MemberID, &i.SessionToken, &i.ExpiresAt, &i.CreatedAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMemberSessionsByMemberID = `-- name: ListMemberSessionsByMemberID :many
SELECT id, member_id, session_token, expires_at, created_at FROM member_sessions WHERE member_id = $1 ORDER BY created_at DESC
`

func (q *Queries) ListMemberSessionsByMemberID(ctx context.Context, memberID uuid.UUID) ([]MemberSession, error) {
	rows, err := q.db.QueryContext(ctx, listMemberSessionsByMemberID, memberID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []MemberSession
	for rows.Next() {
		var i MemberSession
		if err := rows.Scan(&i.ID, &i.MemberID, &i.SessionToken, &i.ExpiresAt, &i.CreatedAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const deleteMemberSession = `-- name: DeleteMemberSession :exec
DELETE FROM member_sessions WHERE id = $1
`

func (q *Queries) DeleteMemberSession(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, deleteMemberSession, id)
	return err
}

const createMemberPreference = `-- name: CreateMemberPreference :one
INSERT INTO member_preferences (id, member_id, language, newsletter_opt_in, updated_at)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, member_id, language, newsletter_opt_in, updated_at
`

type CreateMemberPreferenceParams struct {
	ID              uuid.UUID
	MemberID        uuid.UUID
	Language        string
	NewsletterOptIn bool
	UpdatedAt       time.Time
}

func (q *Queries) CreateMemberPreference(ctx context.Context, arg CreateMemberPreferenceParams) (MemberPreference, error) {
	row := q.db.QueryRowContext(ctx, createMemberPreference, arg.ID, arg.MemberID, arg.Language, arg.NewsletterOptIn, arg.UpdatedAt)
	var i MemberPreference
	err := row.Scan(&i.ID, &i.MemberID, &i.Language, &i.NewsletterOptIn, &i.UpdatedAt)
	return i, err
}

const getMemberPreference = `-- name: GetMemberPreference :one
SELECT id, member_id, language, newsletter_opt_in, updated_at FROM member_preferences WHERE id = $1
`

func (q *Queries) GetMemberPreference(ctx context.Context, id uuid.UUID) (MemberPreference, error) {
	row := q.db.QueryRowContext(ctx, getMemberPreference, id)
	var i MemberPreference
	err := row.Scan(&i.ID, &i.MemberID, &i.Language, &i.NewsletterOptIn, &i.UpdatedAt)
	return i, err
}

const listMemberPreferences = `-- name: ListMemberPreferences :many
SELECT id, member_id, language, newsletter_opt_in, updated_at FROM member_preferences ORDER BY updated_at DESC
`

func (q *Queries) ListMemberPreferences(ctx context.Context) ([]MemberPreference, error) {
	rows, err := q.db.QueryContext(ctx, listMemberPreferences)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []MemberPreference
	for rows.Next() {
		var i MemberPreference
		if err := rows.Scan(&i.ID, &i.MemberID, &i.Language, &i.NewsletterOptIn, &i.UpdatedAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMemberPreferencesByMemberID = `-- name: ListMemberPreferencesByMemberID :many
SELECT id, member_id, language, newsletter_opt_in, updated_at FROM member_preferences WHERE member_id = $1 ORDER BY updated_at DESC
`

func (q *Queries) ListMemberPreferencesByMemberID(ctx context.Context, memberID uuid.UUID) ([]MemberPreference, error) {
	rows, err := q.db.QueryContext(ctx, listMemberPreferencesByMemberID, memberID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []MemberPreference
	for rows.Next() {
		var i MemberPreference
		if err := rows.Scan(&i.ID, &i.MemberID, &i.Language, &i.NewsletterOptIn, &i.UpdatedAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const deleteMemberPreference = `-- name: DeleteMemberPreference :exec
DELETE FROM member_preferences WHERE id = $1
`

func (q *Queries) DeleteMemberPreference(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, deleteMemberPreference, id)
	return err
}

const createMemberTag = `-- name: CreateMemberTag :one
INSERT INTO member_tags (id, name, created_at)
VALUES ($1, $2, $3)
RETURNING id, name, created_at
`

type CreateMemberTagParams struct {
	ID        uuid.UUID
	Name      string
	CreatedAt time.Time
}

func (q *Queries) CreateMemberTag(ctx context.Context, arg CreateMemberTagParams) (MemberTag, error) {
	row := q.db.QueryRowContext(ctx, createMemberTag, arg.ID, arg.Name, arg.CreatedAt)
	var i MemberTag
	err := row.Scan(&i.ID, &i.Name, &i.CreatedAt)
	return i, err
}

const getMemberTag = `-- name: GetMemberTag :one
SELECT id, name, created_at FROM member_tags WHERE id = $1
`

func (q *Queries) GetMemberTag(ctx context.Context, id uuid.UUID) (MemberTag, error) {
	row := q.db.QueryRowContext(ctx, getMemberTag, id)
	var i MemberTag
	err := row.Scan(&i.ID, &i.Name, &i.CreatedAt)
	return i, err
}

const listMemberTags = `-- name: ListMemberTags :many
SELECT id, name, created_at FROM member_tags ORDER BY created_at DESC
`

func (q *Queries) ListMemberTags(ctx context.Context) ([]MemberTag, error) {
	rows, err := q.db.QueryContext(ctx, listMemberTags)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []MemberTag
	for rows.Next() {
		var i MemberTag
		if err := rows.Scan(&i.ID, &i.Name, &i.CreatedAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const deleteMemberTag = `-- name: DeleteMemberTag :exec
DELETE FROM member_tags WHERE id = $1
`

func (q *Queries) DeleteMemberTag(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, deleteMemberTag, id)
	return err
}

const createMemberTagAssignment = `-- name: CreateMemberTagAssignment :one
INSERT INTO member_tag_assignments (id, member_id, member_tag_id, assigned_at)
VALUES ($1, $2, $3, $4)
RETURNING id, member_id, member_tag_id, assigned_at
`

type CreateMemberTagAssignmentParams struct {
	ID          uuid.UUID
	MemberID    uuid.UUID
	MemberTagID uuid.UUID
	AssignedAt  time.Time
}

func (q *Queries) CreateMemberTagAssignment(ctx context.Context, arg CreateMemberTagAssignmentParams) (MemberTagAssignment, error) {
	row := q.db.QueryRowContext(ctx, createMemberTagAssignment, arg.ID, arg.MemberID, arg.MemberTagID, arg.AssignedAt)
	var i MemberTagAssignment
	err := row.Scan(&i.ID, &i.MemberID, &i.MemberTagID, &i.AssignedAt)
	return i, err
}

const getMemberTagAssignment = `-- name: GetMemberTagAssignment :one
SELECT id, member_id, member_tag_id, assigned_at FROM member_tag_assignments WHERE id = $1
`

func (q *Queries) GetMemberTagAssignment(ctx context.Context, id uuid.UUID) (MemberTagAssignment, error) {
	row := q.db.QueryRowContext(ctx, getMemberTagAssignment, id)
	var i MemberTagAssignment
	err := row.Scan(&i.ID, &i.MemberID, &i.MemberTagID, &i.AssignedAt)
	return i, err
}

const listMemberTagAssignments = `-- name: ListMemberTagAssignments :many
SELECT id, member_id, member_tag_id, assigned_at FROM member_tag_assignments ORDER BY assigned_at DESC
`

func (q *Queries) ListMemberTagAssignments(ctx context.Context) ([]MemberTagAssignment, error) {
	rows, err := q.db.QueryContext(ctx, listMemberTagAssignments)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []MemberTagAssignment
	for rows.Next() {
		var i MemberTagAssignment
		if err := rows.Scan(&i.ID, &i.MemberID, &i.MemberTagID, &i.AssignedAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMemberTagAssignmentsByMemberID = `-- name: ListMemberTagAssignmentsByMemberID :many
SELECT id, member_id, member_tag_id, assigned_at FROM member_tag_assignments WHERE member_id = $1 ORDER BY assigned_at DESC
`

func (q *Queries) ListMemberTagAssignmentsByMemberID(ctx context.Context, memberID uuid.UUID) ([]MemberTagAssignment, error) {
	rows, err := q.db.QueryContext(ctx, listMemberTagAssignmentsByMemberID, memberID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []MemberTagAssignment
	for rows.Next() {
		var i MemberTagAssignment
		if err := rows.Scan(&i.ID, &i.MemberID, &i.MemberTagID, &i.AssignedAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const deleteMemberTagAssignment = `-- name: DeleteMemberTagAssignment :exec
DELETE FROM member_tag_assignments WHERE id = $1
`

func (q *Queries) DeleteMemberTagAssignment(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, deleteMemberTagAssignment, id)
	return err
}

const createMemberReferral = `-- name: CreateMemberReferral :one
INSERT INTO member_referrals (id, referrer_member_id, referred_member_id, reward_yen, created_at)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, referrer_member_id, referred_member_id, reward_yen, created_at
`

type CreateMemberReferralParams struct {
	ID               uuid.UUID
	ReferrerMemberID uuid.UUID
	ReferredMemberID uuid.UUID
	RewardYen        int32
	CreatedAt        time.Time
}

func (q *Queries) CreateMemberReferral(ctx context.Context, arg CreateMemberReferralParams) (MemberReferral, error) {
	row := q.db.QueryRowContext(ctx, createMemberReferral, arg.ID, arg.ReferrerMemberID, arg.ReferredMemberID, arg.RewardYen, arg.CreatedAt)
	var i MemberReferral
	err := row.Scan(&i.ID, &i.ReferrerMemberID, &i.ReferredMemberID, &i.RewardYen, &i.CreatedAt)
	return i, err
}

const getMemberReferral = `-- name: GetMemberReferral :one
SELECT id, referrer_member_id, referred_member_id, reward_yen, created_at FROM member_referrals WHERE id = $1
`

func (q *Queries) GetMemberReferral(ctx context.Context, id uuid.UUID) (MemberReferral, error) {
	row := q.db.QueryRowContext(ctx, getMemberReferral, id)
	var i MemberReferral
	err := row.Scan(&i.ID, &i.ReferrerMemberID, &i.ReferredMemberID, &i.RewardYen, &i.CreatedAt)
	return i, err
}

const listMemberReferrals = `-- name: ListMemberReferrals :many
SELECT id, referrer_member_id, referred_member_id, reward_yen, created_at FROM member_referrals ORDER BY created_at DESC
`

func (q *Queries) ListMemberReferrals(ctx context.Context) ([]MemberReferral, error) {
	rows, err := q.db.QueryContext(ctx, listMemberReferrals)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []MemberReferral
	for rows.Next() {
		var i MemberReferral
		if err := rows.Scan(&i.ID, &i.ReferrerMemberID, &i.ReferredMemberID, &i.RewardYen, &i.CreatedAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMemberReferralsByReferrerMemberID = `-- name: ListMemberReferralsByReferrerMemberID :many
SELECT id, referrer_member_id, referred_member_id, reward_yen, created_at FROM member_referrals WHERE referrer_member_id = $1 ORDER BY created_at DESC
`

func (q *Queries) ListMemberReferralsByReferrerMemberID(ctx context.Context, referrerMemberID uuid.UUID) ([]MemberReferral, error) {
	rows, err := q.db.QueryContext(ctx, listMemberReferralsByReferrerMemberID, referrerMemberID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []MemberReferral
	for rows.Next() {
		var i MemberReferral
		if err := rows.Scan(&i.ID, &i.ReferrerMemberID, &i.ReferredMemberID, &i.RewardYen, &i.CreatedAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const deleteMemberReferral = `-- name: DeleteMemberReferral :exec
DELETE FROM member_referrals WHERE id = $1
`

func (q *Queries) DeleteMemberReferral(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, deleteMemberReferral, id)
	return err
}

const createMemberPointAccount = `-- name: CreateMemberPointAccount :one
INSERT INTO member_point_accounts (id, member_id, balance, updated_at)
VALUES ($1, $2, $3, $4)
RETURNING id, member_id, balance, updated_at
`

type CreateMemberPointAccountParams struct {
	ID        uuid.UUID
	MemberID  uuid.UUID
	Balance   int32
	UpdatedAt time.Time
}

func (q *Queries) CreateMemberPointAccount(ctx context.Context, arg CreateMemberPointAccountParams) (MemberPointAccount, error) {
	row := q.db.QueryRowContext(ctx, createMemberPointAccount, arg.ID, arg.MemberID, arg.Balance, arg.UpdatedAt)
	var i MemberPointAccount
	err := row.Scan(&i.ID, &i.MemberID, &i.Balance, &i.UpdatedAt)
	return i, err
}

const getMemberPointAccount = `-- name: GetMemberPointAccount :one
SELECT id, member_id, balance, updated_at FROM member_point_accounts WHERE id = $1
`

func (q *Queries) GetMemberPointAccount(ctx context.Context, id uuid.UUID) (MemberPointAccount, error) {
	row := q.db.QueryRowContext(ctx, getMemberPointAccount, id)
	var i MemberPointAccount
	err := row.Scan(&i.ID, &i.MemberID, &i.Balance, &i.UpdatedAt)
	return i, err
}

const listMemberPointAccounts = `-- name: ListMemberPointAccounts :many
SELECT id, member_id, balance, updated_at FROM member_point_accounts ORDER BY updated_at DESC
`

func (q *Queries) ListMemberPointAccounts(ctx context.Context) ([]MemberPointAccount, error) {
	rows, err := q.db.QueryContext(ctx, listMemberPointAccounts)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []MemberPointAccount
	for rows.Next() {
		var i MemberPointAccount
		if err := rows.Scan(&i.ID, &i.MemberID, &i.Balance, &i.UpdatedAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMemberPointAccountsByMemberID = `-- name: ListMemberPointAccountsByMemberID :many
SELECT id, member_id, balance, updated_at FROM member_point_accounts WHERE member_id = $1 ORDER BY updated_at DESC
`

func (q *Queries) ListMemberPointAccountsByMemberID(ctx context.Context, memberID uuid.UUID) ([]MemberPointAccount, error) {
	rows, err := q.db.QueryContext(ctx, listMemberPointAccountsByMemberID, memberID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []MemberPointAccount
	for rows.Next() {
		var i MemberPointAccount
		if err := rows.Scan(&i.ID, &i.MemberID, &i.Balance, &i.UpdatedAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const deleteMemberPointAccount = `-- name: DeleteMemberPointAccount :exec
DELETE FROM member_point_accounts WHERE id = $1
`

func (q *Queries) DeleteMemberPointAccount(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, deleteMemberPointAccount, id)
	return err
}

const listMemberCountAndAvgPointBalanceByTag = `-- name: ListMemberCountAndAvgPointBalanceByTag :many
SELECT
    mt.id AS member_tag_id,
    mt.name AS tag_name,
    COUNT(DISTINCT mta.member_id) AS member_count,
    COALESCE(AVG(mpa.balance), 0)::float8 AS avg_point_balance
FROM member_tags mt
JOIN member_tag_assignments mta ON mta.member_tag_id = mt.id
LEFT JOIN member_point_accounts mpa ON mpa.member_id = mta.member_id
GROUP BY mt.id, mt.name
ORDER BY member_count DESC, mt.name
`

type ListMemberCountAndAvgPointBalanceByTagRow struct {
	MemberTagID     uuid.UUID
	TagName         string
	MemberCount     int64
	AvgPointBalance float64
}

func (q *Queries) ListMemberCountAndAvgPointBalanceByTag(ctx context.Context) ([]ListMemberCountAndAvgPointBalanceByTagRow, error) {
	rows, err := q.db.QueryContext(ctx, listMemberCountAndAvgPointBalanceByTag)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListMemberCountAndAvgPointBalanceByTagRow
	for rows.Next() {
		var i ListMemberCountAndAvgPointBalanceByTagRow
		if err := rows.Scan(&i.MemberTagID, &i.TagName, &i.MemberCount, &i.AvgPointBalance); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTopMembersByAddressCountAndPointBalance = `-- name: ListTopMembersByAddressCountAndPointBalance :many
SELECT
    m.id AS member_id,
    m.name AS member_name,
    COUNT(ma.id) AS address_count,
    COALESCE(mpa.balance, 0) AS point_balance
FROM members m
LEFT JOIN member_addresses ma ON ma.member_id = m.id
LEFT JOIN member_point_accounts mpa ON mpa.member_id = m.id
GROUP BY m.id, m.name, mpa.balance
ORDER BY point_balance DESC, address_count DESC, m.name
LIMIT $1
`

type ListTopMembersByAddressCountAndPointBalanceRow struct {
	MemberID     uuid.UUID
	MemberName   string
	AddressCount int64
	PointBalance int32
}

func (q *Queries) ListTopMembersByAddressCountAndPointBalance(ctx context.Context, limit int32) ([]ListTopMembersByAddressCountAndPointBalanceRow, error) {
	rows, err := q.db.QueryContext(ctx, listTopMembersByAddressCountAndPointBalance, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListTopMembersByAddressCountAndPointBalanceRow
	for rows.Next() {
		var i ListTopMembersByAddressCountAndPointBalanceRow
		if err := rows.Scan(&i.MemberID, &i.MemberName, &i.AddressCount, &i.PointBalance); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listReferralRewardSummaryByReferrer = `-- name: ListReferralRewardSummaryByReferrer :many
SELECT
    m.id AS referrer_member_id,
    m.name AS referrer_name,
    COUNT(mr.id) AS referral_count,
    COALESCE(SUM(mr.reward_yen), 0)::bigint AS total_reward_yen
FROM members m
JOIN member_referrals mr ON mr.referrer_member_id = m.id
GROUP BY m.id, m.name
ORDER BY total_reward_yen DESC, m.name
`

type ListReferralRewardSummaryByReferrerRow struct {
	ReferrerMemberID uuid.UUID
	ReferrerName     string
	ReferralCount    int64
	TotalRewardYen   int64
}

func (q *Queries) ListReferralRewardSummaryByReferrer(ctx context.Context) ([]ListReferralRewardSummaryByReferrerRow, error) {
	rows, err := q.db.QueryContext(ctx, listReferralRewardSummaryByReferrer)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListReferralRewardSummaryByReferrerRow
	for rows.Next() {
		var i ListReferralRewardSummaryByReferrerRow
		if err := rows.Scan(&i.ReferrerMemberID, &i.ReferrerName, &i.ReferralCount, &i.TotalRewardYen); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
