// Code generated by sqlc. DO NOT EDIT.
package sqlc

import (
	"time"

	"github.com/google/uuid"
)

type Member struct {
	ID        uuid.UUID
	Name      string
	Email     string
	CreatedAt time.Time
}

type MemberProfile struct {
	ID        uuid.UUID
	MemberID  uuid.UUID
	BirthDate time.Time
	Gender    string
	Bio       string
	AvatarURL string
	UpdatedAt time.Time
}

type MemberAddress struct {
	ID         uuid.UUID
	MemberID   uuid.UUID
	PostalCode string
	Prefecture string
	City       string
	Line1      string
	Line2      string
	IsDefault  bool
	CreatedAt  time.Time
}

type MemberCredential struct {
	ID            uuid.UUID
	MemberID      uuid.UUID
	PasswordHash  string
	LastChangedAt time.Time
}

type MemberSession struct {
	ID           uuid.UUID
	MemberID     uuid.UUID
	SessionToken string
	ExpiresAt    time.Time
	CreatedAt    time.Time
}

type MemberPreference struct {
	ID              uuid.UUID
	MemberID        uuid.UUID
	Language        string
	NewsletterOptIn bool
	UpdatedAt       time.Time
}

type MemberTag struct {
	ID        uuid.UUID
	Name      string
	CreatedAt time.Time
}

type MemberTagAssignment struct {
	ID          uuid.UUID
	MemberID    uuid.UUID
	MemberTagID uuid.UUID
	AssignedAt  time.Time
}

type MemberReferral struct {
	ID               uuid.UUID
	ReferrerMemberID uuid.UUID
	ReferredMemberID uuid.UUID
	RewardYen        int32
	CreatedAt        time.Time
}

type MemberPointAccount struct {
	ID        uuid.UUID
	MemberID  uuid.UUID
	Balance   int32
	UpdatedAt time.Time
}
