// Code generated by sqlc. DO NOT EDIT.
package sqlc

import (
	"database/sql"
	"time"

	"github.com/google/uuid"
)

type Shipment struct {
	ID        uuid.UUID
	OrderID   uuid.UUID
	Address   string
	Status    string
	ShippedAt sql.NullTime
}

type ShipmentItem struct {
	ID          uuid.UUID
	ShipmentID  uuid.UUID
	OrderItemID uuid.UUID
	Quantity    int32
}

type Carrier struct {
	ID   uuid.UUID
	Name string
}

type TrackingEvent struct {
	ID         uuid.UUID
	ShipmentID uuid.UUID
	Status     string
	OccurredAt time.Time
}

type ShippingAddress struct {
	ID         uuid.UUID
	ShipmentID uuid.UUID
	PostalCode string
	Address    string
}

type ShippingRate struct {
	ID        uuid.UUID
	CarrierID uuid.UUID
	ZoneName  string
	PriceYen  int32
}

type ShippingZone struct {
	ID   uuid.UUID
	Name string
}

type DeliveryAttempt struct {
	ID          uuid.UUID
	ShipmentID  uuid.UUID
	AttemptedAt time.Time
	Succeeded   bool
}

type ReturnRequest struct {
	ID        uuid.UUID
	OrderID   uuid.UUID
	Reason    string
	Status    string
	CreatedAt time.Time
}

type ReturnItem struct {
	ID              uuid.UUID
	ReturnRequestID uuid.UUID
	OrderItemID     uuid.UUID
	Quantity        int32
}
