// Code generated by sqlc. DO NOT EDIT.
package sqlc

import (
	"context"
	"database/sql"
	"time"

	"github.com/google/uuid"
)

const createShipment = `-- name: CreateShipment :one
INSERT INTO shipments (id, order_id, address, status, shipped_at)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, order_id, address, status, shipped_at
`

type CreateShipmentParams struct {
	ID        uuid.UUID
	OrderID   uuid.UUID
	Address   string
	Status    string
	ShippedAt sql.NullTime
}

func (q *Queries) CreateShipment(ctx context.Context, arg CreateShipmentParams) (Shipment, error) {
	row := q.db.QueryRowContext(ctx, createShipment, arg.ID, arg.OrderID, arg.Address, arg.Status, arg.ShippedAt)
	var i Shipment
	err := row.Scan(&i.ID, &i.OrderID, &i.Address, &i.Status, &i.ShippedAt)
	return i, err
}

const getShipment = `-- name: GetShipment :one
SELECT id, order_id, address, status, shipped_at FROM shipments WHERE id = $1
`

func (q *Queries) GetShipment(ctx context.Context, id uuid.UUID) (Shipment, error) {
	row := q.db.QueryRowContext(ctx, getShipment, id)
	var i Shipment
	err := row.Scan(&i.ID, &i.OrderID, &i.Address, &i.Status, &i.ShippedAt)
	return i, err
}

const listShipments = `-- name: ListShipments :many
SELECT id, order_id, address, status, shipped_at FROM shipments ORDER BY id
`

func (q *Queries) ListShipments(ctx context.Context) ([]Shipment, error) {
	rows, err := q.db.QueryContext(ctx, listShipments)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Shipment
	for rows.Next() {
		var i Shipment
		if err := rows.Scan(&i.ID, &i.OrderID, &i.Address, &i.Status, &i.ShippedAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const createShipmentItem = `-- name: CreateShipmentItem :one
INSERT INTO shipment_items (id, shipment_id, order_item_id, quantity)
VALUES ($1, $2, $3, $4)
RETURNING id, shipment_id, order_item_id, quantity
`

type CreateShipmentItemParams struct {
	ID          uuid.UUID
	ShipmentID  uuid.UUID
	OrderItemID uuid.UUID
	Quantity    int32
}

func (q *Queries) CreateShipmentItem(ctx context.Context, arg CreateShipmentItemParams) (ShipmentItem, error) {
	row := q.db.QueryRowContext(ctx, createShipmentItem, arg.ID, arg.ShipmentID, arg.OrderItemID, arg.Quantity)
	var i ShipmentItem
	err := row.Scan(&i.ID, &i.ShipmentID, &i.OrderItemID, &i.Quantity)
	return i, err
}

const getShipmentItem = `-- name: GetShipmentItem :one
SELECT id, shipment_id, order_item_id, quantity FROM shipment_items WHERE id = $1
`

func (q *Queries) GetShipmentItem(ctx context.Context, id uuid.UUID) (ShipmentItem, error) {
	row := q.db.QueryRowContext(ctx, getShipmentItem, id)
	var i ShipmentItem
	err := row.Scan(&i.ID, &i.ShipmentID, &i.OrderItemID, &i.Quantity)
	return i, err
}

const listShipmentItems = `-- name: ListShipmentItems :many
SELECT id, shipment_id, order_item_id, quantity FROM shipment_items ORDER BY id
`

func (q *Queries) ListShipmentItems(ctx context.Context) ([]ShipmentItem, error) {
	rows, err := q.db.QueryContext(ctx, listShipmentItems)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ShipmentItem
	for rows.Next() {
		var i ShipmentItem
		if err := rows.Scan(&i.ID, &i.ShipmentID, &i.OrderItemID, &i.Quantity); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listShipmentItemsByShipmentID = `-- name: ListShipmentItemsByShipmentID :many
SELECT id, shipment_id, order_item_id, quantity FROM shipment_items WHERE shipment_id = $1 ORDER BY id
`

func (q *Queries) ListShipmentItemsByShipmentID(ctx context.Context, shipmentID uuid.UUID) ([]ShipmentItem, error) {
	rows, err := q.db.QueryContext(ctx, listShipmentItemsByShipmentID, shipmentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ShipmentItem
	for rows.Next() {
		var i ShipmentItem
		if err := rows.Scan(&i.ID, &i.ShipmentID, &i.OrderItemID, &i.Quantity); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const deleteShipmentItem = `-- name: DeleteShipmentItem :exec
DELETE FROM shipment_items WHERE id = $1
`

func (q *Queries) DeleteShipmentItem(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, deleteShipmentItem, id)
	return err
}

const createCarrier = `-- name: CreateCarrier :one
INSERT INTO carriers (id, name)
VALUES ($1, $2)
RETURNING id, name
`

type CreateCarrierParams struct {
	ID   uuid.UUID
	Name string
}

func (q *Queries) CreateCarrier(ctx context.Context, arg CreateCarrierParams) (Carrier, error) {
	row := q.db.QueryRowContext(ctx, createCarrier, arg.ID, arg.Name)
	var i Carrier
	err := row.Scan(&i.ID, &i.Name)
	return i, err
}

const getCarrier = `-- name: GetCarrier :one
SELECT id, name FROM carriers WHERE id = $1
`

func (q *Queries) GetCarrier(ctx context.Context, id uuid.UUID) (Carrier, error) {
	row := q.db.QueryRowContext(ctx, getCarrier, id)
	var i Carrier
	err := row.Scan(&i.ID, &i.Name)
	return i, err
}

const listCarriers = `-- name: ListCarriers :many
SELECT id, name FROM carriers ORDER BY id
`

func (q *Queries) ListCarriers(ctx context.Context) ([]Carrier, error) {
	rows, err := q.db.QueryContext(ctx, listCarriers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Carrier
	for rows.Next() {
		var i Carrier
		if err := rows.Scan(&i.ID, &i.Name); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const deleteCarrier = `-- name: DeleteCarrier :exec
DELETE FROM carriers WHERE id = $1
`

func (q *Queries) DeleteCarrier(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, deleteCarrier, id)
	return err
}

const createTrackingEvent = `-- name: CreateTrackingEvent :one
INSERT INTO tracking_events (id, shipment_id, status, occurred_at)
VALUES ($1, $2, $3, $4)
RETURNING id, shipment_id, status, occurred_at
`

type CreateTrackingEventParams struct {
	ID         uuid.UUID
	ShipmentID uuid.UUID
	Status     string
	OccurredAt time.Time
}

func (q *Queries) CreateTrackingEvent(ctx context.Context, arg CreateTrackingEventParams) (TrackingEvent, error) {
	row := q.db.QueryRowContext(ctx, createTrackingEvent, arg.ID, arg.ShipmentID, arg.Status, arg.OccurredAt)
	var i TrackingEvent
	err := row.Scan(&i.ID, &i.ShipmentID, &i.Status, &i.OccurredAt)
	return i, err
}

const getTrackingEvent = `-- name: GetTrackingEvent :one
SELECT id, shipment_id, status, occurred_at FROM tracking_events WHERE id = $1
`

func (q *Queries) GetTrackingEvent(ctx context.Context, id uuid.UUID) (TrackingEvent, error) {
	row := q.db.QueryRowContext(ctx, getTrackingEvent, id)
	var i TrackingEvent
	err := row.Scan(&i.ID, &i.ShipmentID, &i.Status, &i.OccurredAt)
	return i, err
}

const listTrackingEvents = `-- name: ListTrackingEvents :many
SELECT id, shipment_id, status, occurred_at FROM tracking_events ORDER BY occurred_at DESC
`

func (q *Queries) ListTrackingEvents(ctx context.Context) ([]TrackingEvent, error) {
	rows, err := q.db.QueryContext(ctx, listTrackingEvents)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []TrackingEvent
	for rows.Next() {
		var i TrackingEvent
		if err := rows.Scan(&i.ID, &i.ShipmentID, &i.Status, &i.OccurredAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTrackingEventsByShipmentID = `-- name: ListTrackingEventsByShipmentID :many
SELECT id, shipment_id, status, occurred_at FROM tracking_events WHERE shipment_id = $1 ORDER BY occurred_at DESC
`

func (q *Queries) ListTrackingEventsByShipmentID(ctx context.Context, shipmentID uuid.UUID) ([]TrackingEvent, error) {
	rows, err := q.db.QueryContext(ctx, listTrackingEventsByShipmentID, shipmentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []TrackingEvent
	for rows.Next() {
		var i TrackingEvent
		if err := rows.Scan(&i.ID, &i.ShipmentID, &i.Status, &i.OccurredAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const deleteTrackingEvent = `-- name: DeleteTrackingEvent :exec
DELETE FROM tracking_events WHERE id = $1
`

func (q *Queries) DeleteTrackingEvent(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, deleteTrackingEvent, id)
	return err
}

const createShippingAddress = `-- name: CreateShippingAddress :one
INSERT INTO shipping_addresses (id, shipment_id, postal_code, address)
VALUES ($1, $2, $3, $4)
RETURNING id, shipment_id, postal_code, address
`

type CreateShippingAddressParams struct {
	ID         uuid.UUID
	ShipmentID uuid.UUID
	PostalCode string
	Address    string
}

func (q *Queries) CreateShippingAddress(ctx context.Context, arg CreateShippingAddressParams) (ShippingAddress, error) {
	row := q.db.QueryRowContext(ctx, createShippingAddress, arg.ID, arg.ShipmentID, arg.PostalCode, arg.Address)
	var i ShippingAddress
	err := row.Scan(&i.ID, &i.ShipmentID, &i.PostalCode, &i.Address)
	return i, err
}

const getShippingAddress = `-- name: GetShippingAddress :one
SELECT id, shipment_id, postal_code, address FROM shipping_addresses WHERE id = $1
`

func (q *Queries) GetShippingAddress(ctx context.Context, id uuid.UUID) (ShippingAddress, error) {
	row := q.db.QueryRowContext(ctx, getShippingAddress, id)
	var i ShippingAddress
	err := row.Scan(&i.ID, &i.ShipmentID, &i.PostalCode, &i.Address)
	return i, err
}

const listShippingAddresses = `-- name: ListShippingAddresses :many
SELECT id, shipment_id, postal_code, address FROM shipping_addresses ORDER BY id
`

func (q *Queries) ListShippingAddresses(ctx context.Context) ([]ShippingAddress, error) {
	rows, err := q.db.QueryContext(ctx, listShippingAddresses)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ShippingAddress
	for rows.Next() {
		var i ShippingAddress
		if err := rows.Scan(&i.ID, &i.ShipmentID, &i.PostalCode, &i.Address); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listShippingAddressesByShipmentID = `-- name: ListShippingAddressesByShipmentID :many
SELECT id, shipment_id, postal_code, address FROM shipping_addresses WHERE shipment_id = $1 ORDER BY id
`

func (q *Queries) ListShippingAddressesByShipmentID(ctx context.Context, shipmentID uuid.UUID) ([]ShippingAddress, error) {
	rows, err := q.db.QueryContext(ctx, listShippingAddressesByShipmentID, shipmentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ShippingAddress
	for rows.Next() {
		var i ShippingAddress
		if err := rows.Scan(&i.ID, &i.ShipmentID, &i.PostalCode, &i.Address); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const deleteShippingAddress = `-- name: DeleteShippingAddress :exec
DELETE FROM shipping_addresses WHERE id = $1
`

func (q *Queries) DeleteShippingAddress(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, deleteShippingAddress, id)
	return err
}

const createShippingRate = `-- name: CreateShippingRate :one
INSERT INTO shipping_rates (id, carrier_id, zone_name, price_yen)
VALUES ($1, $2, $3, $4)
RETURNING id, carrier_id, zone_name, price_yen
`

type CreateShippingRateParams struct {
	ID        uuid.UUID
	CarrierID uuid.UUID
	ZoneName  string
	PriceYen  int32
}

func (q *Queries) CreateShippingRate(ctx context.Context, arg CreateShippingRateParams) (ShippingRate, error) {
	row := q.db.QueryRowContext(ctx, createShippingRate, arg.ID, arg.CarrierID, arg.ZoneName, arg.PriceYen)
	var i ShippingRate
	err := row.Scan(&i.ID, &i.CarrierID, &i.ZoneName, &i.PriceYen)
	return i, err
}

const getShippingRate = `-- name: GetShippingRate :one
SELECT id, carrier_id, zone_name, price_yen FROM shipping_rates WHERE id = $1
`

func (q *Queries) GetShippingRate(ctx context.Context, id uuid.UUID) (ShippingRate, error) {
	row := q.db.QueryRowContext(ctx, getShippingRate, id)
	var i ShippingRate
	err := row.Scan(&i.ID, &i.CarrierID, &i.ZoneName, &i.PriceYen)
	return i, err
}

const listShippingRates = `-- name: ListShippingRates :many
SELECT id, carrier_id, zone_name, price_yen FROM shipping_rates ORDER BY id
`

func (q *Queries) ListShippingRates(ctx context.Context) ([]ShippingRate, error) {
	rows, err := q.db.QueryContext(ctx, listShippingRates)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ShippingRate
	for rows.Next() {
		var i ShippingRate
		if err := rows.Scan(&i.ID, &i.CarrierID, &i.ZoneName, &i.PriceYen); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listShippingRatesByCarrierID = `-- name: ListShippingRatesByCarrierID :many
SELECT id, carrier_id, zone_name, price_yen FROM shipping_rates WHERE carrier_id = $1 ORDER BY id
`

func (q *Queries) ListShippingRatesByCarrierID(ctx context.Context, carrierID uuid.UUID) ([]ShippingRate, error) {
	rows, err := q.db.QueryContext(ctx, listShippingRatesByCarrierID, carrierID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ShippingRate
	for rows.Next() {
		var i ShippingRate
		if err := rows.Scan(&i.ID, &i.CarrierID, &i.ZoneName, &i.PriceYen); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const deleteShippingRate = `-- name: DeleteShippingRate :exec
DELETE FROM shipping_rates WHERE id = $1
`

func (q *Queries) DeleteShippingRate(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, deleteShippingRate, id)
	return err
}

const createShippingZone = `-- name: CreateShippingZone :one
INSERT INTO shipping_zones (id, name)
VALUES ($1, $2)
RETURNING id, name
`

type CreateShippingZoneParams struct {
	ID   uuid.UUID
	Name string
}

func (q *Queries) CreateShippingZone(ctx context.Context, arg CreateShippingZoneParams) (ShippingZone, error) {
	row := q.db.QueryRowContext(ctx, createShippingZone, arg.ID, arg.Name)
	var i ShippingZone
	err := row.Scan(&i.ID, &i.Name)
	return i, err
}

const getShippingZone = `-- name: GetShippingZone :one
SELECT id, name FROM shipping_zones WHERE id = $1
`

func (q *Queries) GetShippingZone(ctx context.Context, id uuid.UUID) (ShippingZone, error) {
	row := q.db.QueryRowContext(ctx, getShippingZone, id)
	var i ShippingZone
	err := row.Scan(&i.ID, &i.Name)
	return i, err
}

const listShippingZones = `-- name: ListShippingZones :many
SELECT id, name FROM shipping_zones ORDER BY id
`

func (q *Queries) ListShippingZones(ctx context.Context) ([]ShippingZone, error) {
	rows, err := q.db.QueryContext(ctx, listShippingZones)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ShippingZone
	for rows.Next() {
		var i ShippingZone
		if err := rows.Scan(&i.ID, &i.Name); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const deleteShippingZone = `-- name: DeleteShippingZone :exec
DELETE FROM shipping_zones WHERE id = $1
`

func (q *Queries) DeleteShippingZone(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, deleteShippingZone, id)
	return err
}

const createDeliveryAttempt = `-- name: CreateDeliveryAttempt :one
INSERT INTO delivery_attempts (id, shipment_id, attempted_at, succeeded)
VALUES ($1, $2, $3, $4)
RETURNING id, shipment_id, attempted_at, succeeded
`

type CreateDeliveryAttemptParams struct {
	ID          uuid.UUID
	ShipmentID  uuid.UUID
	AttemptedAt time.Time
	Succeeded   bool
}

func (q *Queries) CreateDeliveryAttempt(ctx context.Context, arg CreateDeliveryAttemptParams) (DeliveryAttempt, error) {
	row := q.db.QueryRowContext(ctx, createDeliveryAttempt, arg.ID, arg.ShipmentID, arg.AttemptedAt, arg.Succeeded)
	var i DeliveryAttempt
	err := row.Scan(&i.ID, &i.ShipmentID, &i.AttemptedAt, &i.Succeeded)
	return i, err
}

const getDeliveryAttempt = `-- name: GetDeliveryAttempt :one
SELECT id, shipment_id, attempted_at, succeeded FROM delivery_attempts WHERE id = $1
`

func (q *Queries) GetDeliveryAttempt(ctx context.Context, id uuid.UUID) (DeliveryAttempt, error) {
	row := q.db.QueryRowContext(ctx, getDeliveryAttempt, id)
	var i DeliveryAttempt
	err := row.Scan(&i.ID, &i.ShipmentID, &i.AttemptedAt, &i.Succeeded)
	return i, err
}

const listDeliveryAttempts = `-- name: ListDeliveryAttempts :many
SELECT id, shipment_id, attempted_at, succeeded FROM delivery_attempts ORDER BY attempted_at DESC
`

func (q *Queries) ListDeliveryAttempts(ctx context.Context) ([]DeliveryAttempt, error) {
	rows, err := q.db.QueryContext(ctx, listDeliveryAttempts)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []DeliveryAttempt
	for rows.Next() {
		var i DeliveryAttempt
		if err := rows.Scan(&i.ID, &i.ShipmentID, &i.AttemptedAt, &i.Succeeded); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDeliveryAttemptsByShipmentID = `-- name: ListDeliveryAttemptsByShipmentID :many
SELECT id, shipment_id, attempted_at, succeeded FROM delivery_attempts WHERE shipment_id = $1 ORDER BY attempted_at DESC
`

func (q *Queries) ListDeliveryAttemptsByShipmentID(ctx context.Context, shipmentID uuid.UUID) ([]DeliveryAttempt, error) {
	rows, err := q.db.QueryContext(ctx, listDeliveryAttemptsByShipmentID, shipmentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []DeliveryAttempt
	for rows.Next() {
		var i DeliveryAttempt
		if err := rows.Scan(&i.ID, &i.ShipmentID, &i.AttemptedAt, &i.Succeeded); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const deleteDeliveryAttempt = `-- name: DeleteDeliveryAttempt :exec
DELETE FROM delivery_attempts WHERE id = $1
`

func (q *Queries) DeleteDeliveryAttempt(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, deleteDeliveryAttempt, id)
	return err
}

const createReturnRequest = `-- name: CreateReturnRequest :one
INSERT INTO return_requests (id, order_id, reason, status, created_at)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, order_id, reason, status, created_at
`

type CreateReturnRequestParams struct {
	ID        uuid.UUID
	OrderID   uuid.UUID
	Reason    string
	Status    string
	CreatedAt time.Time
}

func (q *Queries) CreateReturnRequest(ctx context.Context, arg CreateReturnRequestParams) (ReturnRequest, error) {
	row := q.db.QueryRowContext(ctx, createReturnRequest, arg.ID, arg.OrderID, arg.Reason, arg.Status, arg.CreatedAt)
	var i ReturnRequest
	err := row.Scan(&i.ID, &i.OrderID, &i.Reason, &i.Status, &i.CreatedAt)
	return i, err
}

const getReturnRequest = `-- name: GetReturnRequest :one
SELECT id, order_id, reason, status, created_at FROM return_requests WHERE id = $1
`

func (q *Queries) GetReturnRequest(ctx context.Context, id uuid.UUID) (ReturnRequest, error) {
	row := q.db.QueryRowContext(ctx, getReturnRequest, id)
	var i ReturnRequest
	err := row.Scan(&i.ID, &i.OrderID, &i.Reason, &i.Status, &i.CreatedAt)
	return i, err
}

const listReturnRequests = `-- name: ListReturnRequests :many
SELECT id, order_id, reason, status, created_at FROM return_requests ORDER BY created_at DESC
`

func (q *Queries) ListReturnRequests(ctx context.Context) ([]ReturnRequest, error) {
	rows, err := q.db.QueryContext(ctx, listReturnRequests)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ReturnRequest
	for rows.Next() {
		var i ReturnRequest
		if err := rows.Scan(&i.ID, &i.OrderID, &i.Reason, &i.Status, &i.CreatedAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listReturnRequestsByOrderID = `-- name: ListReturnRequestsByOrderID :many
SELECT id, order_id, reason, status, created_at FROM return_requests WHERE order_id = $1 ORDER BY created_at DESC
`

func (q *Queries) ListReturnRequestsByOrderID(ctx context.Context, orderID uuid.UUID) ([]ReturnRequest, error) {
	rows, err := q.db.QueryContext(ctx, listReturnRequestsByOrderID, orderID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ReturnRequest
	for rows.Next() {
		var i ReturnRequest
		if err := rows.Scan(&i.ID, &i.OrderID, &i.Reason, &i.Status, &i.CreatedAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const deleteReturnRequest = `-- name: DeleteReturnRequest :exec
DELETE FROM return_requests WHERE id = $1
`

func (q *Queries) DeleteReturnRequest(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, deleteReturnRequest, id)
	return err
}

const createReturnItem = `-- name: CreateReturnItem :one
INSERT INTO return_items (id, return_request_id, order_item_id, quantity)
VALUES ($1, $2, $3, $4)
RETURNING id, return_request_id, order_item_id, quantity
`

type CreateReturnItemParams struct {
	ID              uuid.UUID
	ReturnRequestID uuid.UUID
	OrderItemID     uuid.UUID
	Quantity        int32
}

func (q *Queries) CreateReturnItem(ctx context.Context, arg CreateReturnItemParams) (ReturnItem, error) {
	row := q.db.QueryRowContext(ctx, createReturnItem, arg.ID, arg.ReturnRequestID, arg.OrderItemID, arg.Quantity)
	var i ReturnItem
	err := row.Scan(&i.ID, &i.ReturnRequestID, &i.OrderItemID, &i.Quantity)
	return i, err
}

const getReturnItem = `-- name: GetReturnItem :one
SELECT id, return_request_id, order_item_id, quantity FROM return_items WHERE id = $1
`

func (q *Queries) GetReturnItem(ctx context.Context, id uuid.UUID) (ReturnItem, error) {
	row := q.db.QueryRowContext(ctx, getReturnItem, id)
	var i ReturnItem
	err := row.Scan(&i.ID, &i.ReturnRequestID, &i.OrderItemID, &i.Quantity)
	return i, err
}

const listReturnItems = `-- name: ListReturnItems :many
SELECT id, return_request_id, order_item_id, quantity FROM return_items ORDER BY id
`

func (q *Queries) ListReturnItems(ctx context.Context) ([]ReturnItem, error) {
	rows, err := q.db.QueryContext(ctx, listReturnItems)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ReturnItem
	for rows.Next() {
		var i ReturnItem
		if err := rows.Scan(&i.ID, &i.ReturnRequestID, &i.OrderItemID, &i.Quantity); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listReturnItemsByReturnRequestID = `-- name: ListReturnItemsByReturnRequestID :many
SELECT id, return_request_id, order_item_id, quantity FROM return_items WHERE return_request_id = $1 ORDER BY id
`

func (q *Queries) ListReturnItemsByReturnRequestID(ctx context.Context, returnRequestID uuid.UUID) ([]ReturnItem, error) {
	rows, err := q.db.QueryContext(ctx, listReturnItemsByReturnRequestID, returnRequestID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ReturnItem
	for rows.Next() {
		var i ReturnItem
		if err := rows.Scan(&i.ID, &i.ReturnRequestID, &i.OrderItemID, &i.Quantity); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const deleteReturnItem = `-- name: DeleteReturnItem :exec
DELETE FROM return_items WHERE id = $1
`

func (q *Queries) DeleteReturnItem(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, deleteReturnItem, id)
	return err
}
