// Code generated by sqlc. DO NOT EDIT.
package sqlc

import (
	"time"

	"github.com/google/uuid"
)

type Notification struct {
	ID        uuid.UUID
	MemberID  uuid.UUID
	Message   string
	IsRead    bool
	CreatedAt time.Time
}

type NotificationTemplate struct {
	ID   uuid.UUID
	Name string
	Body string
}

type NotificationChannel struct {
	ID   uuid.UUID
	Name string
}

type NotificationPreference struct {
	ID        uuid.UUID
	MemberID  uuid.UUID
	ChannelID uuid.UUID
	Enabled   bool
}

type NotificationLog struct {
	ID             uuid.UUID
	NotificationID uuid.UUID
	Status         string
	SentAt         time.Time
}

type NotificationSubscription struct {
	ID           uuid.UUID
	MemberID     uuid.UUID
	Topic        string
	SubscribedAt time.Time
}

type PushDevice struct {
	ID           uuid.UUID
	MemberID     uuid.UUID
	DeviceToken  string
	RegisteredAt time.Time
}

type EmailLog struct {
	ID       uuid.UUID
	MemberID uuid.UUID
	Subject  string
	SentAt   time.Time
}

type SMSLog struct {
	ID       uuid.UUID
	MemberID uuid.UUID
	Body     string
	SentAt   time.Time
}

type NotificationBatch struct {
	ID         uuid.UUID
	TemplateID uuid.UUID
	Status     string
	CreatedAt  time.Time
}
