// Code generated by sqlc. DO NOT EDIT.
package sqlc

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const createNotification = `-- name: CreateNotification :one
INSERT INTO notifications (id, member_id, message, is_read, created_at)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, member_id, message, is_read, created_at
`

type CreateNotificationParams struct {
	ID        uuid.UUID
	MemberID  uuid.UUID
	Message   string
	IsRead    bool
	CreatedAt time.Time
}

func (q *Queries) CreateNotification(ctx context.Context, arg CreateNotificationParams) (Notification, error) {
	row := q.db.QueryRowContext(ctx, createNotification, arg.ID, arg.MemberID, arg.Message, arg.IsRead, arg.CreatedAt)
	var i Notification
	err := row.Scan(&i.ID, &i.MemberID, &i.Message, &i.IsRead, &i.CreatedAt)
	return i, err
}

const getNotification = `-- name: GetNotification :one
SELECT id, member_id, message, is_read, created_at FROM notifications WHERE id = $1
`

func (q *Queries) GetNotification(ctx context.Context, id uuid.UUID) (Notification, error) {
	row := q.db.QueryRowContext(ctx, getNotification, id)
	var i Notification
	err := row.Scan(&i.ID, &i.MemberID, &i.Message, &i.IsRead, &i.CreatedAt)
	return i, err
}

const listNotifications = `-- name: ListNotifications :many
SELECT id, member_id, message, is_read, created_at FROM notifications ORDER BY created_at DESC
`

func (q *Queries) ListNotifications(ctx context.Context) ([]Notification, error) {
	rows, err := q.db.QueryContext(ctx, listNotifications)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Notification
	for rows.Next() {
		var i Notification
		if err := rows.Scan(&i.ID, &i.MemberID, &i.Message, &i.IsRead, &i.CreatedAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const createNotificationTemplate = `-- name: CreateNotificationTemplate :one
INSERT INTO notification_templates (id, name, body)
VALUES ($1, $2, $3)
RETURNING id, name, body
`

type CreateNotificationTemplateParams struct {
	ID   uuid.UUID
	Name string
	Body string
}

func (q *Queries) CreateNotificationTemplate(ctx context.Context, arg CreateNotificationTemplateParams) (NotificationTemplate, error) {
	row := q.db.QueryRowContext(ctx, createNotificationTemplate, arg.ID, arg.Name, arg.Body)
	var i NotificationTemplate
	err := row.Scan(&i.ID, &i.Name, &i.Body)
	return i, err
}

const getNotificationTemplate = `-- name: GetNotificationTemplate :one
SELECT id, name, body FROM notification_templates WHERE id = $1
`

func (q *Queries) GetNotificationTemplate(ctx context.Context, id uuid.UUID) (NotificationTemplate, error) {
	row := q.db.QueryRowContext(ctx, getNotificationTemplate, id)
	var i NotificationTemplate
	err := row.Scan(&i.ID, &i.Name, &i.Body)
	return i, err
}

const listNotificationTemplates = `-- name: ListNotificationTemplates :many
SELECT id, name, body FROM notification_templates ORDER BY id DESC
`

func (q *Queries) ListNotificationTemplates(ctx context.Context) ([]NotificationTemplate, error) {
	rows, err := q.db.QueryContext(ctx, listNotificationTemplates)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []NotificationTemplate
	for rows.Next() {
		var i NotificationTemplate
		if err := rows.Scan(&i.ID, &i.Name, &i.Body); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const deleteNotificationTemplate = `-- name: DeleteNotificationTemplate :exec
DELETE FROM notification_templates WHERE id = $1
`

func (q *Queries) DeleteNotificationTemplate(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, deleteNotificationTemplate, id)
	return err
}

const createNotificationChannel = `-- name: CreateNotificationChannel :one
INSERT INTO notification_channels (id, name)
VALUES ($1, $2)
RETURNING id, name
`

type CreateNotificationChannelParams struct {
	ID   uuid.UUID
	Name string
}

func (q *Queries) CreateNotificationChannel(ctx context.Context, arg CreateNotificationChannelParams) (NotificationChannel, error) {
	row := q.db.QueryRowContext(ctx, createNotificationChannel, arg.ID, arg.Name)
	var i NotificationChannel
	err := row.Scan(&i.ID, &i.Name)
	return i, err
}

const getNotificationChannel = `-- name: GetNotificationChannel :one
SELECT id, name FROM notification_channels WHERE id = $1
`

func (q *Queries) GetNotificationChannel(ctx context.Context, id uuid.UUID) (NotificationChannel, error) {
	row := q.db.QueryRowContext(ctx, getNotificationChannel, id)
	var i NotificationChannel
	err := row.Scan(&i.ID, &i.Name)
	return i, err
}

const listNotificationChannels = `-- name: ListNotificationChannels :many
SELECT id, name FROM notification_channels ORDER BY id DESC
`

func (q *Queries) ListNotificationChannels(ctx context.Context) ([]NotificationChannel, error) {
	rows, err := q.db.QueryContext(ctx, listNotificationChannels)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []NotificationChannel
	for rows.Next() {
		var i NotificationChannel
		if err := rows.Scan(&i.ID, &i.Name); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const deleteNotificationChannel = `-- name: DeleteNotificationChannel :exec
DELETE FROM notification_channels WHERE id = $1
`

func (q *Queries) DeleteNotificationChannel(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, deleteNotificationChannel, id)
	return err
}

const createNotificationPreference = `-- name: CreateNotificationPreference :one
INSERT INTO notification_preferences (id, member_id, channel_id, enabled)
VALUES ($1, $2, $3, $4)
RETURNING id, member_id, channel_id, enabled
`

type CreateNotificationPreferenceParams struct {
	ID        uuid.UUID
	MemberID  uuid.UUID
	ChannelID uuid.UUID
	Enabled   bool
}

func (q *Queries) CreateNotificationPreference(ctx context.Context, arg CreateNotificationPreferenceParams) (NotificationPreference, error) {
	row := q.db.QueryRowContext(ctx, createNotificationPreference, arg.ID, arg.MemberID, arg.ChannelID, arg.Enabled)
	var i NotificationPreference
	err := row.Scan(&i.ID, &i.MemberID, &i.ChannelID, &i.Enabled)
	return i, err
}

const getNotificationPreference = `-- name: GetNotificationPreference :one
SELECT id, member_id, channel_id, enabled FROM notification_preferences WHERE id = $1
`

func (q *Queries) GetNotificationPreference(ctx context.Context, id uuid.UUID) (NotificationPreference, error) {
	row := q.db.QueryRowContext(ctx, getNotificationPreference, id)
	var i NotificationPreference
	err := row.Scan(&i.ID, &i.MemberID, &i.ChannelID, &i.Enabled)
	return i, err
}

const listNotificationPreferences = `-- name: ListNotificationPreferences :many
SELECT id, member_id, channel_id, enabled FROM notification_preferences ORDER BY id DESC
`

func (q *Queries) ListNotificationPreferences(ctx context.Context) ([]NotificationPreference, error) {
	rows, err := q.db.QueryContext(ctx, listNotificationPreferences)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []NotificationPreference
	for rows.Next() {
		var i NotificationPreference
		if err := rows.Scan(&i.ID, &i.MemberID, &i.ChannelID, &i.Enabled); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listNotificationPreferencesByMemberID = `-- name: ListNotificationPreferencesByMemberID :many
SELECT id, member_id, channel_id, enabled FROM notification_preferences WHERE member_id = $1 ORDER BY id DESC
`

func (q *Queries) ListNotificationPreferencesByMemberID(ctx context.Context, memberID uuid.UUID) ([]NotificationPreference, error) {
	rows, err := q.db.QueryContext(ctx, listNotificationPreferencesByMemberID, memberID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []NotificationPreference
	for rows.Next() {
		var i NotificationPreference
		if err := rows.Scan(&i.ID, &i.MemberID, &i.ChannelID, &i.Enabled); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listNotificationPreferencesByChannelID = `-- name: ListNotificationPreferencesByChannelID :many
SELECT id, member_id, channel_id, enabled FROM notification_preferences WHERE channel_id = $1 ORDER BY id DESC
`

func (q *Queries) ListNotificationPreferencesByChannelID(ctx context.Context, channelID uuid.UUID) ([]NotificationPreference, error) {
	rows, err := q.db.QueryContext(ctx, listNotificationPreferencesByChannelID, channelID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []NotificationPreference
	for rows.Next() {
		var i NotificationPreference
		if err := rows.Scan(&i.ID, &i.MemberID, &i.ChannelID, &i.Enabled); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const deleteNotificationPreference = `-- name: DeleteNotificationPreference :exec
DELETE FROM notification_preferences WHERE id = $1
`

func (q *Queries) DeleteNotificationPreference(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, deleteNotificationPreference, id)
	return err
}

const createNotificationLog = `-- name: CreateNotificationLog :one
INSERT INTO notification_logs (id, notification_id, status, sent_at)
VALUES ($1, $2, $3, $4)
RETURNING id, notification_id, status, sent_at
`

type CreateNotificationLogParams struct {
	ID             uuid.UUID
	NotificationID uuid.UUID
	Status         string
	SentAt         time.Time
}

func (q *Queries) CreateNotificationLog(ctx context.Context, arg CreateNotificationLogParams) (NotificationLog, error) {
	row := q.db.QueryRowContext(ctx, createNotificationLog, arg.ID, arg.NotificationID, arg.Status, arg.SentAt)
	var i NotificationLog
	err := row.Scan(&i.ID, &i.NotificationID, &i.Status, &i.SentAt)
	return i, err
}

const getNotificationLog = `-- name: GetNotificationLog :one
SELECT id, notification_id, status, sent_at FROM notification_logs WHERE id = $1
`

func (q *Queries) GetNotificationLog(ctx context.Context, id uuid.UUID) (NotificationLog, error) {
	row := q.db.QueryRowContext(ctx, getNotificationLog, id)
	var i NotificationLog
	err := row.Scan(&i.ID, &i.NotificationID, &i.Status, &i.SentAt)
	return i, err
}

const listNotificationLogs = `-- name: ListNotificationLogs :many
SELECT id, notification_id, status, sent_at FROM notification_logs ORDER BY sent_at DESC
`

func (q *Queries) ListNotificationLogs(ctx context.Context) ([]NotificationLog, error) {
	rows, err := q.db.QueryContext(ctx, listNotificationLogs)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []NotificationLog
	for rows.Next() {
		var i NotificationLog
		if err := rows.Scan(&i.ID, &i.NotificationID, &i.Status, &i.SentAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listNotificationLogsByNotificationID = `-- name: ListNotificationLogsByNotificationID :many
SELECT id, notification_id, status, sent_at FROM notification_logs WHERE notification_id = $1 ORDER BY sent_at DESC
`

func (q *Queries) ListNotificationLogsByNotificationID(ctx context.Context, notificationID uuid.UUID) ([]NotificationLog, error) {
	rows, err := q.db.QueryContext(ctx, listNotificationLogsByNotificationID, notificationID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []NotificationLog
	for rows.Next() {
		var i NotificationLog
		if err := rows.Scan(&i.ID, &i.NotificationID, &i.Status, &i.SentAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const deleteNotificationLog = `-- name: DeleteNotificationLog :exec
DELETE FROM notification_logs WHERE id = $1
`

func (q *Queries) DeleteNotificationLog(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, deleteNotificationLog, id)
	return err
}

const createNotificationSubscription = `-- name: CreateNotificationSubscription :one
INSERT INTO notification_subscriptions (id, member_id, topic, subscribed_at)
VALUES ($1, $2, $3, $4)
RETURNING id, member_id, topic, subscribed_at
`

type CreateNotificationSubscriptionParams struct {
	ID           uuid.UUID
	MemberID     uuid.UUID
	Topic        string
	SubscribedAt time.Time
}

func (q *Queries) CreateNotificationSubscription(ctx context.Context, arg CreateNotificationSubscriptionParams) (NotificationSubscription, error) {
	row := q.db.QueryRowContext(ctx, createNotificationSubscription, arg.ID, arg.MemberID, arg.Topic, arg.SubscribedAt)
	var i NotificationSubscription
	err := row.Scan(&i.ID, &i.MemberID, &i.Topic, &i.SubscribedAt)
	return i, err
}

const getNotificationSubscription = `-- name: GetNotificationSubscription :one
SELECT id, member_id, topic, subscribed_at FROM notification_subscriptions WHERE id = $1
`

func (q *Queries) GetNotificationSubscription(ctx context.Context, id uuid.UUID) (NotificationSubscription, error) {
	row := q.db.QueryRowContext(ctx, getNotificationSubscription, id)
	var i NotificationSubscription
	err := row.Scan(&i.ID, &i.MemberID, &i.Topic, &i.SubscribedAt)
	return i, err
}

const listNotificationSubscriptions = `-- name: ListNotificationSubscriptions :many
SELECT id, member_id, topic, subscribed_at FROM notification_subscriptions ORDER BY subscribed_at DESC
`

func (q *Queries) ListNotificationSubscriptions(ctx context.Context) ([]NotificationSubscription, error) {
	rows, err := q.db.QueryContext(ctx, listNotificationSubscriptions)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []NotificationSubscription
	for rows.Next() {
		var i NotificationSubscription
		if err := rows.Scan(&i.ID, &i.MemberID, &i.Topic, &i.SubscribedAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listNotificationSubscriptionsByMemberID = `-- name: ListNotificationSubscriptionsByMemberID :many
SELECT id, member_id, topic, subscribed_at FROM notification_subscriptions WHERE member_id = $1 ORDER BY subscribed_at DESC
`

func (q *Queries) ListNotificationSubscriptionsByMemberID(ctx context.Context, memberID uuid.UUID) ([]NotificationSubscription, error) {
	rows, err := q.db.QueryContext(ctx, listNotificationSubscriptionsByMemberID, memberID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []NotificationSubscription
	for rows.Next() {
		var i NotificationSubscription
		if err := rows.Scan(&i.ID, &i.MemberID, &i.Topic, &i.SubscribedAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const deleteNotificationSubscription = `-- name: DeleteNotificationSubscription :exec
DELETE FROM notification_subscriptions WHERE id = $1
`

func (q *Queries) DeleteNotificationSubscription(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, deleteNotificationSubscription, id)
	return err
}

const createPushDevice = `-- name: CreatePushDevice :one
INSERT INTO push_devices (id, member_id, device_token, registered_at)
VALUES ($1, $2, $3, $4)
RETURNING id, member_id, device_token, registered_at
`

type CreatePushDeviceParams struct {
	ID           uuid.UUID
	MemberID     uuid.UUID
	DeviceToken  string
	RegisteredAt time.Time
}

func (q *Queries) CreatePushDevice(ctx context.Context, arg CreatePushDeviceParams) (PushDevice, error) {
	row := q.db.QueryRowContext(ctx, createPushDevice, arg.ID, arg.MemberID, arg.DeviceToken, arg.RegisteredAt)
	var i PushDevice
	err := row.Scan(&i.ID, &i.MemberID, &i.DeviceToken, &i.RegisteredAt)
	return i, err
}

const getPushDevice = `-- name: GetPushDevice :one
SELECT id, member_id, device_token, registered_at FROM push_devices WHERE id = $1
`

func (q *Queries) GetPushDevice(ctx context.Context, id uuid.UUID) (PushDevice, error) {
	row := q.db.QueryRowContext(ctx, getPushDevice, id)
	var i PushDevice
	err := row.Scan(&i.ID, &i.MemberID, &i.DeviceToken, &i.RegisteredAt)
	return i, err
}

const listPushDevices = `-- name: ListPushDevices :many
SELECT id, member_id, device_token, registered_at FROM push_devices ORDER BY registered_at DESC
`

func (q *Queries) ListPushDevices(ctx context.Context) ([]PushDevice, error) {
	rows, err := q.db.QueryContext(ctx, listPushDevices)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []PushDevice
	for rows.Next() {
		var i PushDevice
		if err := rows.Scan(&i.ID, &i.MemberID, &i.DeviceToken, &i.RegisteredAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPushDevicesByMemberID = `-- name: ListPushDevicesByMemberID :many
SELECT id, member_id, device_token, registered_at FROM push_devices WHERE member_id = $1 ORDER BY registered_at DESC
`

func (q *Queries) ListPushDevicesByMemberID(ctx context.Context, memberID uuid.UUID) ([]PushDevice, error) {
	rows, err := q.db.QueryContext(ctx, listPushDevicesByMemberID, memberID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []PushDevice
	for rows.Next() {
		var i PushDevice
		if err := rows.Scan(&i.ID, &i.MemberID, &i.DeviceToken, &i.RegisteredAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const deletePushDevice = `-- name: DeletePushDevice :exec
DELETE FROM push_devices WHERE id = $1
`

func (q *Queries) DeletePushDevice(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, deletePushDevice, id)
	return err
}

const createEmailLog = `-- name: CreateEmailLog :one
INSERT INTO email_logs (id, member_id, subject, sent_at)
VALUES ($1, $2, $3, $4)
RETURNING id, member_id, subject, sent_at
`

type CreateEmailLogParams struct {
	ID       uuid.UUID
	MemberID uuid.UUID
	Subject  string
	SentAt   time.Time
}

func (q *Queries) CreateEmailLog(ctx context.Context, arg CreateEmailLogParams) (EmailLog, error) {
	row := q.db.QueryRowContext(ctx, createEmailLog, arg.ID, arg.MemberID, arg.Subject, arg.SentAt)
	var i EmailLog
	err := row.Scan(&i.ID, &i.MemberID, &i.Subject, &i.SentAt)
	return i, err
}

const getEmailLog = `-- name: GetEmailLog :one
SELECT id, member_id, subject, sent_at FROM email_logs WHERE id = $1
`

func (q *Queries) GetEmailLog(ctx context.Context, id uuid.UUID) (EmailLog, error) {
	row := q.db.QueryRowContext(ctx, getEmailLog, id)
	var i EmailLog
	err := row.Scan(&i.ID, &i.MemberID, &i.Subject, &i.SentAt)
	return i, err
}

const listEmailLogs = `-- name: ListEmailLogs :many
SELECT id, member_id, subject, sent_at FROM email_logs ORDER BY sent_at DESC
`

func (q *Queries) ListEmailLogs(ctx context.Context) ([]EmailLog, error) {
	rows, err := q.db.QueryContext(ctx, listEmailLogs)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []EmailLog
	for rows.Next() {
		var i EmailLog
		if err := rows.Scan(&i.ID, &i.MemberID, &i.Subject, &i.SentAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listEmailLogsByMemberID = `-- name: ListEmailLogsByMemberID :many
SELECT id, member_id, subject, sent_at FROM email_logs WHERE member_id = $1 ORDER BY sent_at DESC
`

func (q *Queries) ListEmailLogsByMemberID(ctx context.Context, memberID uuid.UUID) ([]EmailLog, error) {
	rows, err := q.db.QueryContext(ctx, listEmailLogsByMemberID, memberID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []EmailLog
	for rows.Next() {
		var i EmailLog
		if err := rows.Scan(&i.ID, &i.MemberID, &i.Subject, &i.SentAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const deleteEmailLog = `-- name: DeleteEmailLog :exec
DELETE FROM email_logs WHERE id = $1
`

func (q *Queries) DeleteEmailLog(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, deleteEmailLog, id)
	return err
}

const createSMSLog = `-- name: CreateSMSLog :one
INSERT INTO sms_logs (id, member_id, body, sent_at)
VALUES ($1, $2, $3, $4)
RETURNING id, member_id, body, sent_at
`

type CreateSMSLogParams struct {
	ID       uuid.UUID
	MemberID uuid.UUID
	Body     string
	SentAt   time.Time
}

func (q *Queries) CreateSMSLog(ctx context.Context, arg CreateSMSLogParams) (SMSLog, error) {
	row := q.db.QueryRowContext(ctx, createSMSLog, arg.ID, arg.MemberID, arg.Body, arg.SentAt)
	var i SMSLog
	err := row.Scan(&i.ID, &i.MemberID, &i.Body, &i.SentAt)
	return i, err
}

const getSMSLog = `-- name: GetSMSLog :one
SELECT id, member_id, body, sent_at FROM sms_logs WHERE id = $1
`

func (q *Queries) GetSMSLog(ctx context.Context, id uuid.UUID) (SMSLog, error) {
	row := q.db.QueryRowContext(ctx, getSMSLog, id)
	var i SMSLog
	err := row.Scan(&i.ID, &i.MemberID, &i.Body, &i.SentAt)
	return i, err
}

const listSMSLogs = `-- name: ListSMSLogs :many
SELECT id, member_id, body, sent_at FROM sms_logs ORDER BY sent_at DESC
`

func (q *Queries) ListSMSLogs(ctx context.Context) ([]SMSLog, error) {
	rows, err := q.db.QueryContext(ctx, listSMSLogs)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SMSLog
	for rows.Next() {
		var i SMSLog
		if err := rows.Scan(&i.ID, &i.MemberID, &i.Body, &i.SentAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSMSLogsByMemberID = `-- name: ListSMSLogsByMemberID :many
SELECT id, member_id, body, sent_at FROM sms_logs WHERE member_id = $1 ORDER BY sent_at DESC
`

func (q *Queries) ListSMSLogsByMemberID(ctx context.Context, memberID uuid.UUID) ([]SMSLog, error) {
	rows, err := q.db.QueryContext(ctx, listSMSLogsByMemberID, memberID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SMSLog
	for rows.Next() {
		var i SMSLog
		if err := rows.Scan(&i.ID, &i.MemberID, &i.Body, &i.SentAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const deleteSMSLog = `-- name: DeleteSMSLog :exec
DELETE FROM sms_logs WHERE id = $1
`

func (q *Queries) DeleteSMSLog(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, deleteSMSLog, id)
	return err
}

const createNotificationBatch = `-- name: CreateNotificationBatch :one
INSERT INTO notification_batches (id, template_id, status, created_at)
VALUES ($1, $2, $3, $4)
RETURNING id, template_id, status, created_at
`

type CreateNotificationBatchParams struct {
	ID         uuid.UUID
	TemplateID uuid.UUID
	Status     string
	CreatedAt  time.Time
}

func (q *Queries) CreateNotificationBatch(ctx context.Context, arg CreateNotificationBatchParams) (NotificationBatch, error) {
	row := q.db.QueryRowContext(ctx, createNotificationBatch, arg.ID, arg.TemplateID, arg.Status, arg.CreatedAt)
	var i NotificationBatch
	err := row.Scan(&i.ID, &i.TemplateID, &i.Status, &i.CreatedAt)
	return i, err
}

const getNotificationBatch = `-- name: GetNotificationBatch :one
SELECT id, template_id, status, created_at FROM notification_batches WHERE id = $1
`

func (q *Queries) GetNotificationBatch(ctx context.Context, id uuid.UUID) (NotificationBatch, error) {
	row := q.db.QueryRowContext(ctx, getNotificationBatch, id)
	var i NotificationBatch
	err := row.Scan(&i.ID, &i.TemplateID, &i.Status, &i.CreatedAt)
	return i, err
}

const listNotificationBatches = `-- name: ListNotificationBatches :many
SELECT id, template_id, status, created_at FROM notification_batches ORDER BY created_at DESC
`

func (q *Queries) ListNotificationBatches(ctx context.Context) ([]NotificationBatch, error) {
	rows, err := q.db.QueryContext(ctx, listNotificationBatches)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []NotificationBatch
	for rows.Next() {
		var i NotificationBatch
		if err := rows.Scan(&i.ID, &i.TemplateID, &i.Status, &i.CreatedAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listNotificationBatchesByTemplateID = `-- name: ListNotificationBatchesByTemplateID :many
SELECT id, template_id, status, created_at FROM notification_batches WHERE template_id = $1 ORDER BY created_at DESC
`

func (q *Queries) ListNotificationBatchesByTemplateID(ctx context.Context, templateID uuid.UUID) ([]NotificationBatch, error) {
	rows, err := q.db.QueryContext(ctx, listNotificationBatchesByTemplateID, templateID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []NotificationBatch
	for rows.Next() {
		var i NotificationBatch
		if err := rows.Scan(&i.ID, &i.TemplateID, &i.Status, &i.CreatedAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const deleteNotificationBatch = `-- name: DeleteNotificationBatch :exec
DELETE FROM notification_batches WHERE id = $1
`

func (q *Queries) DeleteNotificationBatch(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, deleteNotificationBatch, id)
	return err
}
