// Code generated by sqlc. DO NOT EDIT.
package sqlc

import (
	"time"

	"github.com/google/uuid"
)

type Order struct {
	ID             uuid.UUID
	MemberID       uuid.UUID
	TotalAmountYen int32
	Status         string
	CreatedAt      time.Time
}

type OrderItem struct {
	ID           uuid.UUID
	OrderID      uuid.UUID
	ProductID    uuid.UUID
	Quantity     int32
	UnitPriceYen int32
}

type OrderStatusHistory struct {
	ID        uuid.UUID
	OrderID   uuid.UUID
	Status    string
	ChangedAt time.Time
}

type OrderNote struct {
	ID        uuid.UUID
	OrderID   uuid.UUID
	Note      string
	CreatedAt time.Time
}

type OrderDiscount struct {
	ID                uuid.UUID
	OrderID           uuid.UUID
	CouponID          uuid.UUID
	DiscountAmountYen int32
}

type Cart struct {
	ID        uuid.UUID
	MemberID  uuid.UUID
	CreatedAt time.Time
}

type CartItem struct {
	ID        uuid.UUID
	CartID    uuid.UUID
	ProductID uuid.UUID
	Quantity  int32
}

type OrderAddress struct {
	ID         uuid.UUID
	OrderID    uuid.UUID
	PostalCode string
	Address    string
}

type OrderTax struct {
	ID           uuid.UUID
	OrderID      uuid.UUID
	TaxAmountYen int32
	TaxRate      int32
}

type OrderCancellation struct {
	ID          uuid.UUID
	OrderID     uuid.UUID
	Reason      string
	CancelledAt time.Time
}
