// Code generated by sqlc. DO NOT EDIT.
package sqlc

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const createOrder = `-- name: CreateOrder :one
INSERT INTO orders (id, member_id, total_amount_yen, status, created_at)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, member_id, total_amount_yen, status, created_at
`

type CreateOrderParams struct {
	ID             uuid.UUID
	MemberID       uuid.UUID
	TotalAmountYen int32
	Status         string
	CreatedAt      time.Time
}

func (q *Queries) CreateOrder(ctx context.Context, arg CreateOrderParams) (Order, error) {
	row := q.db.QueryRowContext(ctx, createOrder, arg.ID, arg.MemberID, arg.TotalAmountYen, arg.Status, arg.CreatedAt)
	var i Order
	err := row.Scan(&i.ID, &i.MemberID, &i.TotalAmountYen, &i.Status, &i.CreatedAt)
	return i, err
}

const getOrder = `-- name: GetOrder :one
SELECT id, member_id, total_amount_yen, status, created_at FROM orders WHERE id = $1
`

func (q *Queries) GetOrder(ctx context.Context, id uuid.UUID) (Order, error) {
	row := q.db.QueryRowContext(ctx, getOrder, id)
	var i Order
	err := row.Scan(&i.ID, &i.MemberID, &i.TotalAmountYen, &i.Status, &i.CreatedAt)
	return i, err
}

const listOrders = `-- name: ListOrders :many
SELECT id, member_id, total_amount_yen, status, created_at FROM orders ORDER BY created_at DESC
`

func (q *Queries) ListOrders(ctx context.Context) ([]Order, error) {
	rows, err := q.db.QueryContext(ctx, listOrders)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Order
	for rows.Next() {
		var i Order
		if err := rows.Scan(&i.ID, &i.MemberID, &i.TotalAmountYen, &i.Status, &i.CreatedAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const createOrderItem = `-- name: CreateOrderItem :one
INSERT INTO order_items (id, order_id, product_id, quantity, unit_price_yen)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, order_id, product_id, quantity, unit_price_yen
`

type CreateOrderItemParams struct {
	ID           uuid.UUID
	OrderID      uuid.UUID
	ProductID    uuid.UUID
	Quantity     int32
	UnitPriceYen int32
}

func (q *Queries) CreateOrderItem(ctx context.Context, arg CreateOrderItemParams) (OrderItem, error) {
	row := q.db.QueryRowContext(ctx, createOrderItem, arg.ID, arg.OrderID, arg.ProductID, arg.Quantity, arg.UnitPriceYen)
	var i OrderItem
	err := row.Scan(&i.ID, &i.OrderID, &i.ProductID, &i.Quantity, &i.UnitPriceYen)
	return i, err
}

const getOrderItem = `-- name: GetOrderItem :one
SELECT id, order_id, product_id, quantity, unit_price_yen FROM order_items WHERE id = $1
`

func (q *Queries) GetOrderItem(ctx context.Context, id uuid.UUID) (OrderItem, error) {
	row := q.db.QueryRowContext(ctx, getOrderItem, id)
	var i OrderItem
	err := row.Scan(&i.ID, &i.OrderID, &i.ProductID, &i.Quantity, &i.UnitPriceYen)
	return i, err
}

const listOrderItems = `-- name: ListOrderItems :many
SELECT id, order_id, product_id, quantity, unit_price_yen FROM order_items ORDER BY id DESC
`

func (q *Queries) ListOrderItems(ctx context.Context) ([]OrderItem, error) {
	rows, err := q.db.QueryContext(ctx, listOrderItems)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []OrderItem
	for rows.Next() {
		var i OrderItem
		if err := rows.Scan(&i.ID, &i.OrderID, &i.ProductID, &i.Quantity, &i.UnitPriceYen); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listOrderItemsByOrderID = `-- name: ListOrderItemsByOrderID :many
SELECT id, order_id, product_id, quantity, unit_price_yen FROM order_items WHERE order_id = $1 ORDER BY id DESC
`

func (q *Queries) ListOrderItemsByOrderID(ctx context.Context, orderID uuid.UUID) ([]OrderItem, error) {
	rows, err := q.db.QueryContext(ctx, listOrderItemsByOrderID, orderID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []OrderItem
	for rows.Next() {
		var i OrderItem
		if err := rows.Scan(&i.ID, &i.OrderID, &i.ProductID, &i.Quantity, &i.UnitPriceYen); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const deleteOrderItem = `-- name: DeleteOrderItem :exec
DELETE FROM order_items WHERE id = $1
`

func (q *Queries) DeleteOrderItem(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, deleteOrderItem, id)
	return err
}

const createOrderStatusHistory = `-- name: CreateOrderStatusHistory :one
INSERT INTO order_status_histories (id, order_id, status, changed_at)
VALUES ($1, $2, $3, $4)
RETURNING id, order_id, status, changed_at
`

type CreateOrderStatusHistoryParams struct {
	ID        uuid.UUID
	OrderID   uuid.UUID
	Status    string
	ChangedAt time.Time
}

func (q *Queries) CreateOrderStatusHistory(ctx context.Context, arg CreateOrderStatusHistoryParams) (OrderStatusHistory, error) {
	row := q.db.QueryRowContext(ctx, createOrderStatusHistory, arg.ID, arg.OrderID, arg.Status, arg.ChangedAt)
	var i OrderStatusHistory
	err := row.Scan(&i.ID, &i.OrderID, &i.Status, &i.ChangedAt)
	return i, err
}

const getOrderStatusHistory = `-- name: GetOrderStatusHistory :one
SELECT id, order_id, status, changed_at FROM order_status_histories WHERE id = $1
`

func (q *Queries) GetOrderStatusHistory(ctx context.Context, id uuid.UUID) (OrderStatusHistory, error) {
	row := q.db.QueryRowContext(ctx, getOrderStatusHistory, id)
	var i OrderStatusHistory
	err := row.Scan(&i.ID, &i.OrderID, &i.Status, &i.ChangedAt)
	return i, err
}

const listOrderStatusHistories = `-- name: ListOrderStatusHistories :many
SELECT id, order_id, status, changed_at FROM order_status_histories ORDER BY changed_at DESC
`

func (q *Queries) ListOrderStatusHistories(ctx context.Context) ([]OrderStatusHistory, error) {
	rows, err := q.db.QueryContext(ctx, listOrderStatusHistories)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []OrderStatusHistory
	for rows.Next() {
		var i OrderStatusHistory
		if err := rows.Scan(&i.ID, &i.OrderID, &i.Status, &i.ChangedAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listOrderStatusHistoriesByOrderID = `-- name: ListOrderStatusHistoriesByOrderID :many
SELECT id, order_id, status, changed_at FROM order_status_histories WHERE order_id = $1 ORDER BY changed_at DESC
`

func (q *Queries) ListOrderStatusHistoriesByOrderID(ctx context.Context, orderID uuid.UUID) ([]OrderStatusHistory, error) {
	rows, err := q.db.QueryContext(ctx, listOrderStatusHistoriesByOrderID, orderID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []OrderStatusHistory
	for rows.Next() {
		var i OrderStatusHistory
		if err := rows.Scan(&i.ID, &i.OrderID, &i.Status, &i.ChangedAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const deleteOrderStatusHistory = `-- name: DeleteOrderStatusHistory :exec
DELETE FROM order_status_histories WHERE id = $1
`

func (q *Queries) DeleteOrderStatusHistory(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, deleteOrderStatusHistory, id)
	return err
}

const createOrderNote = `-- name: CreateOrderNote :one
INSERT INTO order_notes (id, order_id, note, created_at)
VALUES ($1, $2, $3, $4)
RETURNING id, order_id, note, created_at
`

type CreateOrderNoteParams struct {
	ID        uuid.UUID
	OrderID   uuid.UUID
	Note      string
	CreatedAt time.Time
}

func (q *Queries) CreateOrderNote(ctx context.Context, arg CreateOrderNoteParams) (OrderNote, error) {
	row := q.db.QueryRowContext(ctx, createOrderNote, arg.ID, arg.OrderID, arg.Note, arg.CreatedAt)
	var i OrderNote
	err := row.Scan(&i.ID, &i.OrderID, &i.Note, &i.CreatedAt)
	return i, err
}

const getOrderNote = `-- name: GetOrderNote :one
SELECT id, order_id, note, created_at FROM order_notes WHERE id = $1
`

func (q *Queries) GetOrderNote(ctx context.Context, id uuid.UUID) (OrderNote, error) {
	row := q.db.QueryRowContext(ctx, getOrderNote, id)
	var i OrderNote
	err := row.Scan(&i.ID, &i.OrderID, &i.Note, &i.CreatedAt)
	return i, err
}

const listOrderNotes = `-- name: ListOrderNotes :many
SELECT id, order_id, note, created_at FROM order_notes ORDER BY created_at DESC
`

func (q *Queries) ListOrderNotes(ctx context.Context) ([]OrderNote, error) {
	rows, err := q.db.QueryContext(ctx, listOrderNotes)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []OrderNote
	for rows.Next() {
		var i OrderNote
		if err := rows.Scan(&i.ID, &i.OrderID, &i.Note, &i.CreatedAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listOrderNotesByOrderID = `-- name: ListOrderNotesByOrderID :many
SELECT id, order_id, note, created_at FROM order_notes WHERE order_id = $1 ORDER BY created_at DESC
`

func (q *Queries) ListOrderNotesByOrderID(ctx context.Context, orderID uuid.UUID) ([]OrderNote, error) {
	rows, err := q.db.QueryContext(ctx, listOrderNotesByOrderID, orderID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []OrderNote
	for rows.Next() {
		var i OrderNote
		if err := rows.Scan(&i.ID, &i.OrderID, &i.Note, &i.CreatedAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const deleteOrderNote = `-- name: DeleteOrderNote :exec
DELETE FROM order_notes WHERE id = $1
`

func (q *Queries) DeleteOrderNote(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, deleteOrderNote, id)
	return err
}

const createOrderDiscount = `-- name: CreateOrderDiscount :one
INSERT INTO order_discounts (id, order_id, coupon_id, discount_amount_yen)
VALUES ($1, $2, $3, $4)
RETURNING id, order_id, coupon_id, discount_amount_yen
`

type CreateOrderDiscountParams struct {
	ID                uuid.UUID
	OrderID           uuid.UUID
	CouponID          uuid.UUID
	DiscountAmountYen int32
}

func (q *Queries) CreateOrderDiscount(ctx context.Context, arg CreateOrderDiscountParams) (OrderDiscount, error) {
	row := q.db.QueryRowContext(ctx, createOrderDiscount, arg.ID, arg.OrderID, arg.CouponID, arg.DiscountAmountYen)
	var i OrderDiscount
	err := row.Scan(&i.ID, &i.OrderID, &i.CouponID, &i.DiscountAmountYen)
	return i, err
}

const getOrderDiscount = `-- name: GetOrderDiscount :one
SELECT id, order_id, coupon_id, discount_amount_yen FROM order_discounts WHERE id = $1
`

func (q *Queries) GetOrderDiscount(ctx context.Context, id uuid.UUID) (OrderDiscount, error) {
	row := q.db.QueryRowContext(ctx, getOrderDiscount, id)
	var i OrderDiscount
	err := row.Scan(&i.ID, &i.OrderID, &i.CouponID, &i.DiscountAmountYen)
	return i, err
}

const listOrderDiscounts = `-- name: ListOrderDiscounts :many
SELECT id, order_id, coupon_id, discount_amount_yen FROM order_discounts ORDER BY id DESC
`

func (q *Queries) ListOrderDiscounts(ctx context.Context) ([]OrderDiscount, error) {
	rows, err := q.db.QueryContext(ctx, listOrderDiscounts)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []OrderDiscount
	for rows.Next() {
		var i OrderDiscount
		if err := rows.Scan(&i.ID, &i.OrderID, &i.CouponID, &i.DiscountAmountYen); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listOrderDiscountsByOrderID = `-- name: ListOrderDiscountsByOrderID :many
SELECT id, order_id, coupon_id, discount_amount_yen FROM order_discounts WHERE order_id = $1 ORDER BY id DESC
`

func (q *Queries) ListOrderDiscountsByOrderID(ctx context.Context, orderID uuid.UUID) ([]OrderDiscount, error) {
	rows, err := q.db.QueryContext(ctx, listOrderDiscountsByOrderID, orderID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []OrderDiscount
	for rows.Next() {
		var i OrderDiscount
		if err := rows.Scan(&i.ID, &i.OrderID, &i.CouponID, &i.DiscountAmountYen); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const deleteOrderDiscount = `-- name: DeleteOrderDiscount :exec
DELETE FROM order_discounts WHERE id = $1
`

func (q *Queries) DeleteOrderDiscount(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, deleteOrderDiscount, id)
	return err
}

const createCart = `-- name: CreateCart :one
INSERT INTO carts (id, member_id, created_at)
VALUES ($1, $2, $3)
RETURNING id, member_id, created_at
`

type CreateCartParams struct {
	ID        uuid.UUID
	MemberID  uuid.UUID
	CreatedAt time.Time
}

func (q *Queries) CreateCart(ctx context.Context, arg CreateCartParams) (Cart, error) {
	row := q.db.QueryRowContext(ctx, createCart, arg.ID, arg.MemberID, arg.CreatedAt)
	var i Cart
	err := row.Scan(&i.ID, &i.MemberID, &i.CreatedAt)
	return i, err
}

const getCart = `-- name: GetCart :one
SELECT id, member_id, created_at FROM carts WHERE id = $1
`

func (q *Queries) GetCart(ctx context.Context, id uuid.UUID) (Cart, error) {
	row := q.db.QueryRowContext(ctx, getCart, id)
	var i Cart
	err := row.Scan(&i.ID, &i.MemberID, &i.CreatedAt)
	return i, err
}

const listCarts = `-- name: ListCarts :many
SELECT id, member_id, created_at FROM carts ORDER BY created_at DESC
`

func (q *Queries) ListCarts(ctx context.Context) ([]Cart, error) {
	rows, err := q.db.QueryContext(ctx, listCarts)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Cart
	for rows.Next() {
		var i Cart
		if err := rows.Scan(&i.ID, &i.MemberID, &i.CreatedAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCartsByMemberID = `-- name: ListCartsByMemberID :many
SELECT id, member_id, created_at FROM carts WHERE member_id = $1 ORDER BY created_at DESC
`

func (q *Queries) ListCartsByMemberID(ctx context.Context, memberID uuid.UUID) ([]Cart, error) {
	rows, err := q.db.QueryContext(ctx, listCartsByMemberID, memberID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Cart
	for rows.Next() {
		var i Cart
		if err := rows.Scan(&i.ID, &i.MemberID, &i.CreatedAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const deleteCart = `-- name: DeleteCart :exec
DELETE FROM carts WHERE id = $1
`

func (q *Queries) DeleteCart(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, deleteCart, id)
	return err
}

const createCartItem = `-- name: CreateCartItem :one
INSERT INTO cart_items (id, cart_id, product_id, quantity)
VALUES ($1, $2, $3, $4)
RETURNING id, cart_id, product_id, quantity
`

type CreateCartItemParams struct {
	ID        uuid.UUID
	CartID    uuid.UUID
	ProductID uuid.UUID
	Quantity  int32
}

func (q *Queries) CreateCartItem(ctx context.Context, arg CreateCartItemParams) (CartItem, error) {
	row := q.db.QueryRowContext(ctx, createCartItem, arg.ID, arg.CartID, arg.ProductID, arg.Quantity)
	var i CartItem
	err := row.Scan(&i.ID, &i.CartID, &i.ProductID, &i.Quantity)
	return i, err
}

const getCartItem = `-- name: GetCartItem :one
SELECT id, cart_id, product_id, quantity FROM cart_items WHERE id = $1
`

func (q *Queries) GetCartItem(ctx context.Context, id uuid.UUID) (CartItem, error) {
	row := q.db.QueryRowContext(ctx, getCartItem, id)
	var i CartItem
	err := row.Scan(&i.ID, &i.CartID, &i.ProductID, &i.Quantity)
	return i, err
}

const listCartItems = `-- name: ListCartItems :many
SELECT id, cart_id, product_id, quantity FROM cart_items ORDER BY id DESC
`

func (q *Queries) ListCartItems(ctx context.Context) ([]CartItem, error) {
	rows, err := q.db.QueryContext(ctx, listCartItems)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []CartItem
	for rows.Next() {
		var i CartItem
		if err := rows.Scan(&i.ID, &i.CartID, &i.ProductID, &i.Quantity); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCartItemsByCartID = `-- name: ListCartItemsByCartID :many
SELECT id, cart_id, product_id, quantity FROM cart_items WHERE cart_id = $1 ORDER BY id DESC
`

func (q *Queries) ListCartItemsByCartID(ctx context.Context, cartID uuid.UUID) ([]CartItem, error) {
	rows, err := q.db.QueryContext(ctx, listCartItemsByCartID, cartID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []CartItem
	for rows.Next() {
		var i CartItem
		if err := rows.Scan(&i.ID, &i.CartID, &i.ProductID, &i.Quantity); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const deleteCartItem = `-- name: DeleteCartItem :exec
DELETE FROM cart_items WHERE id = $1
`

func (q *Queries) DeleteCartItem(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, deleteCartItem, id)
	return err
}

const createOrderAddress = `-- name: CreateOrderAddress :one
INSERT INTO order_addresses (id, order_id, postal_code, address)
VALUES ($1, $2, $3, $4)
RETURNING id, order_id, postal_code, address
`

type CreateOrderAddressParams struct {
	ID         uuid.UUID
	OrderID    uuid.UUID
	PostalCode string
	Address    string
}

func (q *Queries) CreateOrderAddress(ctx context.Context, arg CreateOrderAddressParams) (OrderAddress, error) {
	row := q.db.QueryRowContext(ctx, createOrderAddress, arg.ID, arg.OrderID, arg.PostalCode, arg.Address)
	var i OrderAddress
	err := row.Scan(&i.ID, &i.OrderID, &i.PostalCode, &i.Address)
	return i, err
}

const getOrderAddress = `-- name: GetOrderAddress :one
SELECT id, order_id, postal_code, address FROM order_addresses WHERE id = $1
`

func (q *Queries) GetOrderAddress(ctx context.Context, id uuid.UUID) (OrderAddress, error) {
	row := q.db.QueryRowContext(ctx, getOrderAddress, id)
	var i OrderAddress
	err := row.Scan(&i.ID, &i.OrderID, &i.PostalCode, &i.Address)
	return i, err
}

const listOrderAddresses = `-- name: ListOrderAddresses :many
SELECT id, order_id, postal_code, address FROM order_addresses ORDER BY id DESC
`

func (q *Queries) ListOrderAddresses(ctx context.Context) ([]OrderAddress, error) {
	rows, err := q.db.QueryContext(ctx, listOrderAddresses)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []OrderAddress
	for rows.Next() {
		var i OrderAddress
		if err := rows.Scan(&i.ID, &i.OrderID, &i.PostalCode, &i.Address); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listOrderAddressesByOrderID = `-- name: ListOrderAddressesByOrderID :many
SELECT id, order_id, postal_code, address FROM order_addresses WHERE order_id = $1 ORDER BY id DESC
`

func (q *Queries) ListOrderAddressesByOrderID(ctx context.Context, orderID uuid.UUID) ([]OrderAddress, error) {
	rows, err := q.db.QueryContext(ctx, listOrderAddressesByOrderID, orderID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []OrderAddress
	for rows.Next() {
		var i OrderAddress
		if err := rows.Scan(&i.ID, &i.OrderID, &i.PostalCode, &i.Address); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const deleteOrderAddress = `-- name: DeleteOrderAddress :exec
DELETE FROM order_addresses WHERE id = $1
`

func (q *Queries) DeleteOrderAddress(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, deleteOrderAddress, id)
	return err
}

const createOrderTax = `-- name: CreateOrderTax :one
INSERT INTO order_taxes (id, order_id, tax_amount_yen, tax_rate)
VALUES ($1, $2, $3, $4)
RETURNING id, order_id, tax_amount_yen, tax_rate
`

type CreateOrderTaxParams struct {
	ID           uuid.UUID
	OrderID      uuid.UUID
	TaxAmountYen int32
	TaxRate      int32
}

func (q *Queries) CreateOrderTax(ctx context.Context, arg CreateOrderTaxParams) (OrderTax, error) {
	row := q.db.QueryRowContext(ctx, createOrderTax, arg.ID, arg.OrderID, arg.TaxAmountYen, arg.TaxRate)
	var i OrderTax
	err := row.Scan(&i.ID, &i.OrderID, &i.TaxAmountYen, &i.TaxRate)
	return i, err
}

const getOrderTax = `-- name: GetOrderTax :one
SELECT id, order_id, tax_amount_yen, tax_rate FROM order_taxes WHERE id = $1
`

func (q *Queries) GetOrderTax(ctx context.Context, id uuid.UUID) (OrderTax, error) {
	row := q.db.QueryRowContext(ctx, getOrderTax, id)
	var i OrderTax
	err := row.Scan(&i.ID, &i.OrderID, &i.TaxAmountYen, &i.TaxRate)
	return i, err
}

const listOrderTaxes = `-- name: ListOrderTaxes :many
SELECT id, order_id, tax_amount_yen, tax_rate FROM order_taxes ORDER BY id DESC
`

func (q *Queries) ListOrderTaxes(ctx context.Context) ([]OrderTax, error) {
	rows, err := q.db.QueryContext(ctx, listOrderTaxes)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []OrderTax
	for rows.Next() {
		var i OrderTax
		if err := rows.Scan(&i.ID, &i.OrderID, &i.TaxAmountYen, &i.TaxRate); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listOrderTaxesByOrderID = `-- name: ListOrderTaxesByOrderID :many
SELECT id, order_id, tax_amount_yen, tax_rate FROM order_taxes WHERE order_id = $1 ORDER BY id DESC
`

func (q *Queries) ListOrderTaxesByOrderID(ctx context.Context, orderID uuid.UUID) ([]OrderTax, error) {
	rows, err := q.db.QueryContext(ctx, listOrderTaxesByOrderID, orderID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []OrderTax
	for rows.Next() {
		var i OrderTax
		if err := rows.Scan(&i.ID, &i.OrderID, &i.TaxAmountYen, &i.TaxRate); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const deleteOrderTax = `-- name: DeleteOrderTax :exec
DELETE FROM order_taxes WHERE id = $1
`

func (q *Queries) DeleteOrderTax(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, deleteOrderTax, id)
	return err
}

const createOrderCancellation = `-- name: CreateOrderCancellation :one
INSERT INTO order_cancellations (id, order_id, reason, cancelled_at)
VALUES ($1, $2, $3, $4)
RETURNING id, order_id, reason, cancelled_at
`

type CreateOrderCancellationParams struct {
	ID          uuid.UUID
	OrderID     uuid.UUID
	Reason      string
	CancelledAt time.Time
}

func (q *Queries) CreateOrderCancellation(ctx context.Context, arg CreateOrderCancellationParams) (OrderCancellation, error) {
	row := q.db.QueryRowContext(ctx, createOrderCancellation, arg.ID, arg.OrderID, arg.Reason, arg.CancelledAt)
	var i OrderCancellation
	err := row.Scan(&i.ID, &i.OrderID, &i.Reason, &i.CancelledAt)
	return i, err
}

const getOrderCancellation = `-- name: GetOrderCancellation :one
SELECT id, order_id, reason, cancelled_at FROM order_cancellations WHERE id = $1
`

func (q *Queries) GetOrderCancellation(ctx context.Context, id uuid.UUID) (OrderCancellation, error) {
	row := q.db.QueryRowContext(ctx, getOrderCancellation, id)
	var i OrderCancellation
	err := row.Scan(&i.ID, &i.OrderID, &i.Reason, &i.CancelledAt)
	return i, err
}

const listOrderCancellations = `-- name: ListOrderCancellations :many
SELECT id, order_id, reason, cancelled_at FROM order_cancellations ORDER BY cancelled_at DESC
`

func (q *Queries) ListOrderCancellations(ctx context.Context) ([]OrderCancellation, error) {
	rows, err := q.db.QueryContext(ctx, listOrderCancellations)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []OrderCancellation
	for rows.Next() {
		var i OrderCancellation
		if err := rows.Scan(&i.ID, &i.OrderID, &i.Reason, &i.CancelledAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listOrderCancellationsByOrderID = `-- name: ListOrderCancellationsByOrderID :many
SELECT id, order_id, reason, cancelled_at FROM order_cancellations WHERE order_id = $1 ORDER BY cancelled_at DESC
`

func (q *Queries) ListOrderCancellationsByOrderID(ctx context.Context, orderID uuid.UUID) ([]OrderCancellation, error) {
	rows, err := q.db.QueryContext(ctx, listOrderCancellationsByOrderID, orderID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []OrderCancellation
	for rows.Next() {
		var i OrderCancellation
		if err := rows.Scan(&i.ID, &i.OrderID, &i.Reason, &i.CancelledAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const deleteOrderCancellation = `-- name: DeleteOrderCancellation :exec
DELETE FROM order_cancellations WHERE id = $1
`

func (q *Queries) DeleteOrderCancellation(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, deleteOrderCancellation, id)
	return err
}
