// Code generated by sqlc. DO NOT EDIT.
package sqlc

import (
	"time"

	"github.com/google/uuid"
)

type StaffMember struct {
	ID        uuid.UUID
	Name      string
	Email     string
	CreatedAt time.Time
}

type Role struct {
	ID   uuid.UUID
	Name string
}

type Permission struct {
	ID   uuid.UUID
	Name string
}

type RolePermission struct {
	ID           uuid.UUID
	RoleID       uuid.UUID
	PermissionID uuid.UUID
}

type StaffRole struct {
	ID            uuid.UUID
	StaffMemberID uuid.UUID
	RoleID        uuid.UUID
}

type StaffActivityLog struct {
	ID            uuid.UUID
	StaffMemberID uuid.UUID
	Action        string
	OccurredAt    time.Time
}

type Department struct {
	ID   uuid.UUID
	Name string
}

type StaffDepartment struct {
	ID            uuid.UUID
	StaffMemberID uuid.UUID
	DepartmentID  uuid.UUID
}

type StaffSchedule struct {
	ID            uuid.UUID
	StaffMemberID uuid.UUID
	WorkDate      time.Time
	Shift         string
}

type StaffPerformanceReview struct {
	ID            uuid.UUID
	StaffMemberID uuid.UUID
	Score         int32
	ReviewedAt    time.Time
}
