// Code generated by sqlc. DO NOT EDIT.
package sqlc

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const createStaffMember = `-- name: CreateStaffMember :one
INSERT INTO staff_members (id, name, email, created_at)
VALUES ($1, $2, $3, $4)
RETURNING id, name, email, created_at
`

type CreateStaffMemberParams struct {
	ID        uuid.UUID
	Name      string
	Email     string
	CreatedAt time.Time
}

func (q *Queries) CreateStaffMember(ctx context.Context, arg CreateStaffMemberParams) (StaffMember, error) {
	row := q.db.QueryRowContext(ctx, createStaffMember, arg.ID, arg.Name, arg.Email, arg.CreatedAt)
	var i StaffMember
	err := row.Scan(&i.ID, &i.Name, &i.Email, &i.CreatedAt)
	return i, err
}

const getStaffMember = `-- name: GetStaffMember :one
SELECT id, name, email, created_at FROM staff_members WHERE id = $1
`

func (q *Queries) GetStaffMember(ctx context.Context, id uuid.UUID) (StaffMember, error) {
	row := q.db.QueryRowContext(ctx, getStaffMember, id)
	var i StaffMember
	err := row.Scan(&i.ID, &i.Name, &i.Email, &i.CreatedAt)
	return i, err
}

const listStaffMembers = `-- name: ListStaffMembers :many
SELECT id, name, email, created_at FROM staff_members ORDER BY created_at DESC
`

func (q *Queries) ListStaffMembers(ctx context.Context) ([]StaffMember, error) {
	rows, err := q.db.QueryContext(ctx, listStaffMembers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []StaffMember
	for rows.Next() {
		var i StaffMember
		if err := rows.Scan(&i.ID, &i.Name, &i.Email, &i.CreatedAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const deleteStaffMember = `-- name: DeleteStaffMember :exec
DELETE FROM staff_members WHERE id = $1
`

func (q *Queries) DeleteStaffMember(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, deleteStaffMember, id)
	return err
}

const createRole = `-- name: CreateRole :one
INSERT INTO roles (id, name)
VALUES ($1, $2)
RETURNING id, name
`

type CreateRoleParams struct {
	ID   uuid.UUID
	Name string
}

func (q *Queries) CreateRole(ctx context.Context, arg CreateRoleParams) (Role, error) {
	row := q.db.QueryRowContext(ctx, createRole, arg.ID, arg.Name)
	var i Role
	err := row.Scan(&i.ID, &i.Name)
	return i, err
}

const getRole = `-- name: GetRole :one
SELECT id, name FROM roles WHERE id = $1
`

func (q *Queries) GetRole(ctx context.Context, id uuid.UUID) (Role, error) {
	row := q.db.QueryRowContext(ctx, getRole, id)
	var i Role
	err := row.Scan(&i.ID, &i.Name)
	return i, err
}

const listRoles = `-- name: ListRoles :many
SELECT id, name FROM roles ORDER BY id DESC
`

func (q *Queries) ListRoles(ctx context.Context) ([]Role, error) {
	rows, err := q.db.QueryContext(ctx, listRoles)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Role
	for rows.Next() {
		var i Role
		if err := rows.Scan(&i.ID, &i.Name); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const deleteRole = `-- name: DeleteRole :exec
DELETE FROM roles WHERE id = $1
`

func (q *Queries) DeleteRole(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, deleteRole, id)
	return err
}

const createPermission = `-- name: CreatePermission :one
INSERT INTO permissions (id, name)
VALUES ($1, $2)
RETURNING id, name
`

type CreatePermissionParams struct {
	ID   uuid.UUID
	Name string
}

func (q *Queries) CreatePermission(ctx context.Context, arg CreatePermissionParams) (Permission, error) {
	row := q.db.QueryRowContext(ctx, createPermission, arg.ID, arg.Name)
	var i Permission
	err := row.Scan(&i.ID, &i.Name)
	return i, err
}

const getPermission = `-- name: GetPermission :one
SELECT id, name FROM permissions WHERE id = $1
`

func (q *Queries) GetPermission(ctx context.Context, id uuid.UUID) (Permission, error) {
	row := q.db.QueryRowContext(ctx, getPermission, id)
	var i Permission
	err := row.Scan(&i.ID, &i.Name)
	return i, err
}

const listPermissions = `-- name: ListPermissions :many
SELECT id, name FROM permissions ORDER BY id DESC
`

func (q *Queries) ListPermissions(ctx context.Context) ([]Permission, error) {
	rows, err := q.db.QueryContext(ctx, listPermissions)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Permission
	for rows.Next() {
		var i Permission
		if err := rows.Scan(&i.ID, &i.Name); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const deletePermission = `-- name: DeletePermission :exec
DELETE FROM permissions WHERE id = $1
`

func (q *Queries) DeletePermission(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, deletePermission, id)
	return err
}

const createRolePermission = `-- name: CreateRolePermission :one
INSERT INTO role_permissions (id, role_id, permission_id)
VALUES ($1, $2, $3)
RETURNING id, role_id, permission_id
`

type CreateRolePermissionParams struct {
	ID           uuid.UUID
	RoleID       uuid.UUID
	PermissionID uuid.UUID
}

func (q *Queries) CreateRolePermission(ctx context.Context, arg CreateRolePermissionParams) (RolePermission, error) {
	row := q.db.QueryRowContext(ctx, createRolePermission, arg.ID, arg.RoleID, arg.PermissionID)
	var i RolePermission
	err := row.Scan(&i.ID, &i.RoleID, &i.PermissionID)
	return i, err
}

const getRolePermission = `-- name: GetRolePermission :one
SELECT id, role_id, permission_id FROM role_permissions WHERE id = $1
`

func (q *Queries) GetRolePermission(ctx context.Context, id uuid.UUID) (RolePermission, error) {
	row := q.db.QueryRowContext(ctx, getRolePermission, id)
	var i RolePermission
	err := row.Scan(&i.ID, &i.RoleID, &i.PermissionID)
	return i, err
}

const listRolePermissions = `-- name: ListRolePermissions :many
SELECT id, role_id, permission_id FROM role_permissions ORDER BY id DESC
`

func (q *Queries) ListRolePermissions(ctx context.Context) ([]RolePermission, error) {
	rows, err := q.db.QueryContext(ctx, listRolePermissions)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []RolePermission
	for rows.Next() {
		var i RolePermission
		if err := rows.Scan(&i.ID, &i.RoleID, &i.PermissionID); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRolePermissionsByRoleID = `-- name: ListRolePermissionsByRoleID :many
SELECT id, role_id, permission_id FROM role_permissions WHERE role_id = $1 ORDER BY id DESC
`

func (q *Queries) ListRolePermissionsByRoleID(ctx context.Context, roleID uuid.UUID) ([]RolePermission, error) {
	rows, err := q.db.QueryContext(ctx, listRolePermissionsByRoleID, roleID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []RolePermission
	for rows.Next() {
		var i RolePermission
		if err := rows.Scan(&i.ID, &i.RoleID, &i.PermissionID); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const deleteRolePermission = `-- name: DeleteRolePermission :exec
DELETE FROM role_permissions WHERE id = $1
`

func (q *Queries) DeleteRolePermission(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, deleteRolePermission, id)
	return err
}

const createStaffRole = `-- name: CreateStaffRole :one
INSERT INTO staff_roles (id, staff_member_id, role_id)
VALUES ($1, $2, $3)
RETURNING id, staff_member_id, role_id
`

type CreateStaffRoleParams struct {
	ID            uuid.UUID
	StaffMemberID uuid.UUID
	RoleID        uuid.UUID
}

func (q *Queries) CreateStaffRole(ctx context.Context, arg CreateStaffRoleParams) (StaffRole, error) {
	row := q.db.QueryRowContext(ctx, createStaffRole, arg.ID, arg.StaffMemberID, arg.RoleID)
	var i StaffRole
	err := row.Scan(&i.ID, &i.StaffMemberID, &i.RoleID)
	return i, err
}

const getStaffRole = `-- name: GetStaffRole :one
SELECT id, staff_member_id, role_id FROM staff_roles WHERE id = $1
`

func (q *Queries) GetStaffRole(ctx context.Context, id uuid.UUID) (StaffRole, error) {
	row := q.db.QueryRowContext(ctx, getStaffRole, id)
	var i StaffRole
	err := row.Scan(&i.ID, &i.StaffMemberID, &i.RoleID)
	return i, err
}

const listStaffRoles = `-- name: ListStaffRoles :many
SELECT id, staff_member_id, role_id FROM staff_roles ORDER BY id DESC
`

func (q *Queries) ListStaffRoles(ctx context.Context) ([]StaffRole, error) {
	rows, err := q.db.QueryContext(ctx, listStaffRoles)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []StaffRole
	for rows.Next() {
		var i StaffRole
		if err := rows.Scan(&i.ID, &i.StaffMemberID, &i.RoleID); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listStaffRolesByStaffMemberID = `-- name: ListStaffRolesByStaffMemberID :many
SELECT id, staff_member_id, role_id FROM staff_roles WHERE staff_member_id = $1 ORDER BY id DESC
`

func (q *Queries) ListStaffRolesByStaffMemberID(ctx context.Context, staffMemberID uuid.UUID) ([]StaffRole, error) {
	rows, err := q.db.QueryContext(ctx, listStaffRolesByStaffMemberID, staffMemberID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []StaffRole
	for rows.Next() {
		var i StaffRole
		if err := rows.Scan(&i.ID, &i.StaffMemberID, &i.RoleID); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const deleteStaffRole = `-- name: DeleteStaffRole :exec
DELETE FROM staff_roles WHERE id = $1
`

func (q *Queries) DeleteStaffRole(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, deleteStaffRole, id)
	return err
}

const createStaffActivityLog = `-- name: CreateStaffActivityLog :one
INSERT INTO staff_activity_logs (id, staff_member_id, action, occurred_at)
VALUES ($1, $2, $3, $4)
RETURNING id, staff_member_id, action, occurred_at
`

type CreateStaffActivityLogParams struct {
	ID            uuid.UUID
	StaffMemberID uuid.UUID
	Action        string
	OccurredAt    time.Time
}

func (q *Queries) CreateStaffActivityLog(ctx context.Context, arg CreateStaffActivityLogParams) (StaffActivityLog, error) {
	row := q.db.QueryRowContext(ctx, createStaffActivityLog, arg.ID, arg.StaffMemberID, arg.Action, arg.OccurredAt)
	var i StaffActivityLog
	err := row.Scan(&i.ID, &i.StaffMemberID, &i.Action, &i.OccurredAt)
	return i, err
}

const getStaffActivityLog = `-- name: GetStaffActivityLog :one
SELECT id, staff_member_id, action, occurred_at FROM staff_activity_logs WHERE id = $1
`

func (q *Queries) GetStaffActivityLog(ctx context.Context, id uuid.UUID) (StaffActivityLog, error) {
	row := q.db.QueryRowContext(ctx, getStaffActivityLog, id)
	var i StaffActivityLog
	err := row.Scan(&i.ID, &i.StaffMemberID, &i.Action, &i.OccurredAt)
	return i, err
}

const listStaffActivityLogs = `-- name: ListStaffActivityLogs :many
SELECT id, staff_member_id, action, occurred_at FROM staff_activity_logs ORDER BY occurred_at DESC
`

func (q *Queries) ListStaffActivityLogs(ctx context.Context) ([]StaffActivityLog, error) {
	rows, err := q.db.QueryContext(ctx, listStaffActivityLogs)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []StaffActivityLog
	for rows.Next() {
		var i StaffActivityLog
		if err := rows.Scan(&i.ID, &i.StaffMemberID, &i.Action, &i.OccurredAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listStaffActivityLogsByStaffMemberID = `-- name: ListStaffActivityLogsByStaffMemberID :many
SELECT id, staff_member_id, action, occurred_at FROM staff_activity_logs WHERE staff_member_id = $1 ORDER BY occurred_at DESC
`

func (q *Queries) ListStaffActivityLogsByStaffMemberID(ctx context.Context, staffMemberID uuid.UUID) ([]StaffActivityLog, error) {
	rows, err := q.db.QueryContext(ctx, listStaffActivityLogsByStaffMemberID, staffMemberID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []StaffActivityLog
	for rows.Next() {
		var i StaffActivityLog
		if err := rows.Scan(&i.ID, &i.StaffMemberID, &i.Action, &i.OccurredAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const deleteStaffActivityLog = `-- name: DeleteStaffActivityLog :exec
DELETE FROM staff_activity_logs WHERE id = $1
`

func (q *Queries) DeleteStaffActivityLog(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, deleteStaffActivityLog, id)
	return err
}

const createDepartment = `-- name: CreateDepartment :one
INSERT INTO departments (id, name)
VALUES ($1, $2)
RETURNING id, name
`

type CreateDepartmentParams struct {
	ID   uuid.UUID
	Name string
}

func (q *Queries) CreateDepartment(ctx context.Context, arg CreateDepartmentParams) (Department, error) {
	row := q.db.QueryRowContext(ctx, createDepartment, arg.ID, arg.Name)
	var i Department
	err := row.Scan(&i.ID, &i.Name)
	return i, err
}

const getDepartment = `-- name: GetDepartment :one
SELECT id, name FROM departments WHERE id = $1
`

func (q *Queries) GetDepartment(ctx context.Context, id uuid.UUID) (Department, error) {
	row := q.db.QueryRowContext(ctx, getDepartment, id)
	var i Department
	err := row.Scan(&i.ID, &i.Name)
	return i, err
}

const listDepartments = `-- name: ListDepartments :many
SELECT id, name FROM departments ORDER BY id DESC
`

func (q *Queries) ListDepartments(ctx context.Context) ([]Department, error) {
	rows, err := q.db.QueryContext(ctx, listDepartments)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Department
	for rows.Next() {
		var i Department
		if err := rows.Scan(&i.ID, &i.Name); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const deleteDepartment = `-- name: DeleteDepartment :exec
DELETE FROM departments WHERE id = $1
`

func (q *Queries) DeleteDepartment(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, deleteDepartment, id)
	return err
}

const createStaffDepartment = `-- name: CreateStaffDepartment :one
INSERT INTO staff_departments (id, staff_member_id, department_id)
VALUES ($1, $2, $3)
RETURNING id, staff_member_id, department_id
`

type CreateStaffDepartmentParams struct {
	ID            uuid.UUID
	StaffMemberID uuid.UUID
	DepartmentID  uuid.UUID
}

func (q *Queries) CreateStaffDepartment(ctx context.Context, arg CreateStaffDepartmentParams) (StaffDepartment, error) {
	row := q.db.QueryRowContext(ctx, createStaffDepartment, arg.ID, arg.StaffMemberID, arg.DepartmentID)
	var i StaffDepartment
	err := row.Scan(&i.ID, &i.StaffMemberID, &i.DepartmentID)
	return i, err
}

const getStaffDepartment = `-- name: GetStaffDepartment :one
SELECT id, staff_member_id, department_id FROM staff_departments WHERE id = $1
`

func (q *Queries) GetStaffDepartment(ctx context.Context, id uuid.UUID) (StaffDepartment, error) {
	row := q.db.QueryRowContext(ctx, getStaffDepartment, id)
	var i StaffDepartment
	err := row.Scan(&i.ID, &i.StaffMemberID, &i.DepartmentID)
	return i, err
}

const listStaffDepartments = `-- name: ListStaffDepartments :many
SELECT id, staff_member_id, department_id FROM staff_departments ORDER BY id DESC
`

func (q *Queries) ListStaffDepartments(ctx context.Context) ([]StaffDepartment, error) {
	rows, err := q.db.QueryContext(ctx, listStaffDepartments)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []StaffDepartment
	for rows.Next() {
		var i StaffDepartment
		if err := rows.Scan(&i.ID, &i.StaffMemberID, &i.DepartmentID); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listStaffDepartmentsByStaffMemberID = `-- name: ListStaffDepartmentsByStaffMemberID :many
SELECT id, staff_member_id, department_id FROM staff_departments WHERE staff_member_id = $1 ORDER BY id DESC
`

func (q *Queries) ListStaffDepartmentsByStaffMemberID(ctx context.Context, staffMemberID uuid.UUID) ([]StaffDepartment, error) {
	rows, err := q.db.QueryContext(ctx, listStaffDepartmentsByStaffMemberID, staffMemberID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []StaffDepartment
	for rows.Next() {
		var i StaffDepartment
		if err := rows.Scan(&i.ID, &i.StaffMemberID, &i.DepartmentID); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const deleteStaffDepartment = `-- name: DeleteStaffDepartment :exec
DELETE FROM staff_departments WHERE id = $1
`

func (q *Queries) DeleteStaffDepartment(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, deleteStaffDepartment, id)
	return err
}

const createStaffSchedule = `-- name: CreateStaffSchedule :one
INSERT INTO staff_schedules (id, staff_member_id, work_date, shift)
VALUES ($1, $2, $3, $4)
RETURNING id, staff_member_id, work_date, shift
`

type CreateStaffScheduleParams struct {
	ID            uuid.UUID
	StaffMemberID uuid.UUID
	WorkDate      time.Time
	Shift         string
}

func (q *Queries) CreateStaffSchedule(ctx context.Context, arg CreateStaffScheduleParams) (StaffSchedule, error) {
	row := q.db.QueryRowContext(ctx, createStaffSchedule, arg.ID, arg.StaffMemberID, arg.WorkDate, arg.Shift)
	var i StaffSchedule
	err := row.Scan(&i.ID, &i.StaffMemberID, &i.WorkDate, &i.Shift)
	return i, err
}

const getStaffSchedule = `-- name: GetStaffSchedule :one
SELECT id, staff_member_id, work_date, shift FROM staff_schedules WHERE id = $1
`

func (q *Queries) GetStaffSchedule(ctx context.Context, id uuid.UUID) (StaffSchedule, error) {
	row := q.db.QueryRowContext(ctx, getStaffSchedule, id)
	var i StaffSchedule
	err := row.Scan(&i.ID, &i.StaffMemberID, &i.WorkDate, &i.Shift)
	return i, err
}

const listStaffSchedules = `-- name: ListStaffSchedules :many
SELECT id, staff_member_id, work_date, shift FROM staff_schedules ORDER BY work_date DESC
`

func (q *Queries) ListStaffSchedules(ctx context.Context) ([]StaffSchedule, error) {
	rows, err := q.db.QueryContext(ctx, listStaffSchedules)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []StaffSchedule
	for rows.Next() {
		var i StaffSchedule
		if err := rows.Scan(&i.ID, &i.StaffMemberID, &i.WorkDate, &i.Shift); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listStaffSchedulesByStaffMemberID = `-- name: ListStaffSchedulesByStaffMemberID :many
SELECT id, staff_member_id, work_date, shift FROM staff_schedules WHERE staff_member_id = $1 ORDER BY work_date DESC
`

func (q *Queries) ListStaffSchedulesByStaffMemberID(ctx context.Context, staffMemberID uuid.UUID) ([]StaffSchedule, error) {
	rows, err := q.db.QueryContext(ctx, listStaffSchedulesByStaffMemberID, staffMemberID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []StaffSchedule
	for rows.Next() {
		var i StaffSchedule
		if err := rows.Scan(&i.ID, &i.StaffMemberID, &i.WorkDate, &i.Shift); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const deleteStaffSchedule = `-- name: DeleteStaffSchedule :exec
DELETE FROM staff_schedules WHERE id = $1
`

func (q *Queries) DeleteStaffSchedule(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, deleteStaffSchedule, id)
	return err
}

const createStaffPerformanceReview = `-- name: CreateStaffPerformanceReview :one
INSERT INTO staff_performance_reviews (id, staff_member_id, score, reviewed_at)
VALUES ($1, $2, $3, $4)
RETURNING id, staff_member_id, score, reviewed_at
`

type CreateStaffPerformanceReviewParams struct {
	ID            uuid.UUID
	StaffMemberID uuid.UUID
	Score         int32
	ReviewedAt    time.Time
}

func (q *Queries) CreateStaffPerformanceReview(ctx context.Context, arg CreateStaffPerformanceReviewParams) (StaffPerformanceReview, error) {
	row := q.db.QueryRowContext(ctx, createStaffPerformanceReview, arg.ID, arg.StaffMemberID, arg.Score, arg.ReviewedAt)
	var i StaffPerformanceReview
	err := row.Scan(&i.ID, &i.StaffMemberID, &i.Score, &i.ReviewedAt)
	return i, err
}

const getStaffPerformanceReview = `-- name: GetStaffPerformanceReview :one
SELECT id, staff_member_id, score, reviewed_at FROM staff_performance_reviews WHERE id = $1
`

func (q *Queries) GetStaffPerformanceReview(ctx context.Context, id uuid.UUID) (StaffPerformanceReview, error) {
	row := q.db.QueryRowContext(ctx, getStaffPerformanceReview, id)
	var i StaffPerformanceReview
	err := row.Scan(&i.ID, &i.StaffMemberID, &i.Score, &i.ReviewedAt)
	return i, err
}

const listStaffPerformanceReviews = `-- name: ListStaffPerformanceReviews :many
SELECT id, staff_member_id, score, reviewed_at FROM staff_performance_reviews ORDER BY reviewed_at DESC
`

func (q *Queries) ListStaffPerformanceReviews(ctx context.Context) ([]StaffPerformanceReview, error) {
	rows, err := q.db.QueryContext(ctx, listStaffPerformanceReviews)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []StaffPerformanceReview
	for rows.Next() {
		var i StaffPerformanceReview
		if err := rows.Scan(&i.ID, &i.StaffMemberID, &i.Score, &i.ReviewedAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listStaffPerformanceReviewsByStaffMemberID = `-- name: ListStaffPerformanceReviewsByStaffMemberID :many
SELECT id, staff_member_id, score, reviewed_at FROM staff_performance_reviews WHERE staff_member_id = $1 ORDER BY reviewed_at DESC
`

func (q *Queries) ListStaffPerformanceReviewsByStaffMemberID(ctx context.Context, staffMemberID uuid.UUID) ([]StaffPerformanceReview, error) {
	rows, err := q.db.QueryContext(ctx, listStaffPerformanceReviewsByStaffMemberID, staffMemberID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []StaffPerformanceReview
	for rows.Next() {
		var i StaffPerformanceReview
		if err := rows.Scan(&i.ID, &i.StaffMemberID, &i.Score, &i.ReviewedAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const deleteStaffPerformanceReview = `-- name: DeleteStaffPerformanceReview :exec
DELETE FROM staff_performance_reviews WHERE id = $1
`

func (q *Queries) DeleteStaffPerformanceReview(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, deleteStaffPerformanceReview, id)
	return err
}
