// Code generated by sqlc. DO NOT EDIT.
package sqlc

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const createCoupon = `-- name: CreateCoupon :one
INSERT INTO coupons (id, code, discount_rate, expires_at)
VALUES ($1, $2, $3, $4)
RETURNING id, code, discount_rate, expires_at
`

type CreateCouponParams struct {
	ID           uuid.UUID
	Code         string
	DiscountRate int32
	ExpiresAt    time.Time
}

func (q *Queries) CreateCoupon(ctx context.Context, arg CreateCouponParams) (Coupon, error) {
	row := q.db.QueryRowContext(ctx, createCoupon, arg.ID, arg.Code, arg.DiscountRate, arg.ExpiresAt)
	var i Coupon
	err := row.Scan(&i.ID, &i.Code, &i.DiscountRate, &i.ExpiresAt)
	return i, err
}

const getCoupon = `-- name: GetCoupon :one
SELECT id, code, discount_rate, expires_at FROM coupons WHERE id = $1
`

func (q *Queries) GetCoupon(ctx context.Context, id uuid.UUID) (Coupon, error) {
	row := q.db.QueryRowContext(ctx, getCoupon, id)
	var i Coupon
	err := row.Scan(&i.ID, &i.Code, &i.DiscountRate, &i.ExpiresAt)
	return i, err
}

const listCoupons = `-- name: ListCoupons :many
SELECT id, code, discount_rate, expires_at FROM coupons ORDER BY expires_at
`

func (q *Queries) ListCoupons(ctx context.Context) ([]Coupon, error) {
	rows, err := q.db.QueryContext(ctx, listCoupons)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Coupon
	for rows.Next() {
		var i Coupon
		if err := rows.Scan(&i.ID, &i.Code, &i.DiscountRate, &i.ExpiresAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const createCouponUsage = `-- name: CreateCouponUsage :one
INSERT INTO coupon_usages (id, coupon_id, order_id, used_at)
VALUES ($1, $2, $3, $4)
RETURNING id, coupon_id, order_id, used_at
`

type CreateCouponUsageParams struct {
	ID       uuid.UUID
	CouponID uuid.UUID
	OrderID  uuid.UUID
	UsedAt   time.Time
}

func (q *Queries) CreateCouponUsage(ctx context.Context, arg CreateCouponUsageParams) (CouponUsage, error) {
	row := q.db.QueryRowContext(ctx, createCouponUsage, arg.ID, arg.CouponID, arg.OrderID, arg.UsedAt)
	var i CouponUsage
	err := row.Scan(&i.ID, &i.CouponID, &i.OrderID, &i.UsedAt)
	return i, err
}

const getCouponUsage = `-- name: GetCouponUsage :one
SELECT id, coupon_id, order_id, used_at FROM coupon_usages WHERE id = $1
`

func (q *Queries) GetCouponUsage(ctx context.Context, id uuid.UUID) (CouponUsage, error) {
	row := q.db.QueryRowContext(ctx, getCouponUsage, id)
	var i CouponUsage
	err := row.Scan(&i.ID, &i.CouponID, &i.OrderID, &i.UsedAt)
	return i, err
}

const listCouponUsages = `-- name: ListCouponUsages :many
SELECT id, coupon_id, order_id, used_at FROM coupon_usages ORDER BY used_at DESC
`

func (q *Queries) ListCouponUsages(ctx context.Context) ([]CouponUsage, error) {
	rows, err := q.db.QueryContext(ctx, listCouponUsages)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []CouponUsage
	for rows.Next() {
		var i CouponUsage
		if err := rows.Scan(&i.ID, &i.CouponID, &i.OrderID, &i.UsedAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCouponUsagesByCouponID = `-- name: ListCouponUsagesByCouponID :many
SELECT id, coupon_id, order_id, used_at FROM coupon_usages WHERE coupon_id = $1 ORDER BY used_at DESC
`

func (q *Queries) ListCouponUsagesByCouponID(ctx context.Context, couponID uuid.UUID) ([]CouponUsage, error) {
	rows, err := q.db.QueryContext(ctx, listCouponUsagesByCouponID, couponID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []CouponUsage
	for rows.Next() {
		var i CouponUsage
		if err := rows.Scan(&i.ID, &i.CouponID, &i.OrderID, &i.UsedAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const deleteCouponUsage = `-- name: DeleteCouponUsage :exec
DELETE FROM coupon_usages WHERE id = $1
`

func (q *Queries) DeleteCouponUsage(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, deleteCouponUsage, id)
	return err
}

const createCampaign = `-- name: CreateCampaign :one
INSERT INTO campaigns (id, name, starts_at, ends_at)
VALUES ($1, $2, $3, $4)
RETURNING id, name, starts_at, ends_at
`

type CreateCampaignParams struct {
	ID       uuid.UUID
	Name     string
	StartsAt time.Time
	EndsAt   time.Time
}

func (q *Queries) CreateCampaign(ctx context.Context, arg CreateCampaignParams) (Campaign, error) {
	row := q.db.QueryRowContext(ctx, createCampaign, arg.ID, arg.Name, arg.StartsAt, arg.EndsAt)
	var i Campaign
	err := row.Scan(&i.ID, &i.Name, &i.StartsAt, &i.EndsAt)
	return i, err
}

const getCampaign = `-- name: GetCampaign :one
SELECT id, name, starts_at, ends_at FROM campaigns WHERE id = $1
`

func (q *Queries) GetCampaign(ctx context.Context, id uuid.UUID) (Campaign, error) {
	row := q.db.QueryRowContext(ctx, getCampaign, id)
	var i Campaign
	err := row.Scan(&i.ID, &i.Name, &i.StartsAt, &i.EndsAt)
	return i, err
}

const listCampaigns = `-- name: ListCampaigns :many
SELECT id, name, starts_at, ends_at FROM campaigns ORDER BY id DESC
`

func (q *Queries) ListCampaigns(ctx context.Context) ([]Campaign, error) {
	rows, err := q.db.QueryContext(ctx, listCampaigns)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Campaign
	for rows.Next() {
		var i Campaign
		if err := rows.Scan(&i.ID, &i.Name, &i.StartsAt, &i.EndsAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const deleteCampaign = `-- name: DeleteCampaign :exec
DELETE FROM campaigns WHERE id = $1
`

func (q *Queries) DeleteCampaign(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, deleteCampaign, id)
	return err
}

const createCampaignTarget = `-- name: CreateCampaignTarget :one
INSERT INTO campaign_targets (id, campaign_id, member_id)
VALUES ($1, $2, $3)
RETURNING id, campaign_id, member_id
`

type CreateCampaignTargetParams struct {
	ID         uuid.UUID
	CampaignID uuid.UUID
	MemberID   uuid.UUID
}

func (q *Queries) CreateCampaignTarget(ctx context.Context, arg CreateCampaignTargetParams) (CampaignTarget, error) {
	row := q.db.QueryRowContext(ctx, createCampaignTarget, arg.ID, arg.CampaignID, arg.MemberID)
	var i CampaignTarget
	err := row.Scan(&i.ID, &i.CampaignID, &i.MemberID)
	return i, err
}

const getCampaignTarget = `-- name: GetCampaignTarget :one
SELECT id, campaign_id, member_id FROM campaign_targets WHERE id = $1
`

func (q *Queries) GetCampaignTarget(ctx context.Context, id uuid.UUID) (CampaignTarget, error) {
	row := q.db.QueryRowContext(ctx, getCampaignTarget, id)
	var i CampaignTarget
	err := row.Scan(&i.ID, &i.CampaignID, &i.MemberID)
	return i, err
}

const listCampaignTargets = `-- name: ListCampaignTargets :many
SELECT id, campaign_id, member_id FROM campaign_targets ORDER BY id DESC
`

func (q *Queries) ListCampaignTargets(ctx context.Context) ([]CampaignTarget, error) {
	rows, err := q.db.QueryContext(ctx, listCampaignTargets)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []CampaignTarget
	for rows.Next() {
		var i CampaignTarget
		if err := rows.Scan(&i.ID, &i.CampaignID, &i.MemberID); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCampaignTargetsByCampaignID = `-- name: ListCampaignTargetsByCampaignID :many
SELECT id, campaign_id, member_id FROM campaign_targets WHERE campaign_id = $1 ORDER BY id DESC
`

func (q *Queries) ListCampaignTargetsByCampaignID(ctx context.Context, campaignID uuid.UUID) ([]CampaignTarget, error) {
	rows, err := q.db.QueryContext(ctx, listCampaignTargetsByCampaignID, campaignID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []CampaignTarget
	for rows.Next() {
		var i CampaignTarget
		if err := rows.Scan(&i.ID, &i.CampaignID, &i.MemberID); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const deleteCampaignTarget = `-- name: DeleteCampaignTarget :exec
DELETE FROM campaign_targets WHERE id = $1
`

func (q *Queries) DeleteCampaignTarget(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, deleteCampaignTarget, id)
	return err
}

const createDiscountRule = `-- name: CreateDiscountRule :one
INSERT INTO discount_rules (id, coupon_id, min_amount_yen)
VALUES ($1, $2, $3)
RETURNING id, coupon_id, min_amount_yen
`

type CreateDiscountRuleParams struct {
	ID           uuid.UUID
	CouponID     uuid.UUID
	MinAmountYen int32
}

func (q *Queries) CreateDiscountRule(ctx context.Context, arg CreateDiscountRuleParams) (DiscountRule, error) {
	row := q.db.QueryRowContext(ctx, createDiscountRule, arg.ID, arg.CouponID, arg.MinAmountYen)
	var i DiscountRule
	err := row.Scan(&i.ID, &i.CouponID, &i.MinAmountYen)
	return i, err
}

const getDiscountRule = `-- name: GetDiscountRule :one
SELECT id, coupon_id, min_amount_yen FROM discount_rules WHERE id = $1
`

func (q *Queries) GetDiscountRule(ctx context.Context, id uuid.UUID) (DiscountRule, error) {
	row := q.db.QueryRowContext(ctx, getDiscountRule, id)
	var i DiscountRule
	err := row.Scan(&i.ID, &i.CouponID, &i.MinAmountYen)
	return i, err
}

const listDiscountRules = `-- name: ListDiscountRules :many
SELECT id, coupon_id, min_amount_yen FROM discount_rules ORDER BY id DESC
`

func (q *Queries) ListDiscountRules(ctx context.Context) ([]DiscountRule, error) {
	rows, err := q.db.QueryContext(ctx, listDiscountRules)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []DiscountRule
	for rows.Next() {
		var i DiscountRule
		if err := rows.Scan(&i.ID, &i.CouponID, &i.MinAmountYen); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDiscountRulesByCouponID = `-- name: ListDiscountRulesByCouponID :many
SELECT id, coupon_id, min_amount_yen FROM discount_rules WHERE coupon_id = $1 ORDER BY id DESC
`

func (q *Queries) ListDiscountRulesByCouponID(ctx context.Context, couponID uuid.UUID) ([]DiscountRule, error) {
	rows, err := q.db.QueryContext(ctx, listDiscountRulesByCouponID, couponID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []DiscountRule
	for rows.Next() {
		var i DiscountRule
		if err := rows.Scan(&i.ID, &i.CouponID, &i.MinAmountYen); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const deleteDiscountRule = `-- name: DeleteDiscountRule :exec
DELETE FROM discount_rules WHERE id = $1
`

func (q *Queries) DeleteDiscountRule(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, deleteDiscountRule, id)
	return err
}

const createCouponCategory = `-- name: CreateCouponCategory :one
INSERT INTO coupon_categories (id, coupon_id, category_id)
VALUES ($1, $2, $3)
RETURNING id, coupon_id, category_id
`

type CreateCouponCategoryParams struct {
	ID         uuid.UUID
	CouponID   uuid.UUID
	CategoryID uuid.UUID
}

func (q *Queries) CreateCouponCategory(ctx context.Context, arg CreateCouponCategoryParams) (CouponCategory, error) {
	row := q.db.QueryRowContext(ctx, createCouponCategory, arg.ID, arg.CouponID, arg.CategoryID)
	var i CouponCategory
	err := row.Scan(&i.ID, &i.CouponID, &i.CategoryID)
	return i, err
}

const getCouponCategory = `-- name: GetCouponCategory :one
SELECT id, coupon_id, category_id FROM coupon_categories WHERE id = $1
`

func (q *Queries) GetCouponCategory(ctx context.Context, id uuid.UUID) (CouponCategory, error) {
	row := q.db.QueryRowContext(ctx, getCouponCategory, id)
	var i CouponCategory
	err := row.Scan(&i.ID, &i.CouponID, &i.CategoryID)
	return i, err
}

const listCouponCategories = `-- name: ListCouponCategories :many
SELECT id, coupon_id, category_id FROM coupon_categories ORDER BY id DESC
`

func (q *Queries) ListCouponCategories(ctx context.Context) ([]CouponCategory, error) {
	rows, err := q.db.QueryContext(ctx, listCouponCategories)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []CouponCategory
	for rows.Next() {
		var i CouponCategory
		if err := rows.Scan(&i.ID, &i.CouponID, &i.CategoryID); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCouponCategoriesByCouponID = `-- name: ListCouponCategoriesByCouponID :many
SELECT id, coupon_id, category_id FROM coupon_categories WHERE coupon_id = $1 ORDER BY id DESC
`

func (q *Queries) ListCouponCategoriesByCouponID(ctx context.Context, couponID uuid.UUID) ([]CouponCategory, error) {
	rows, err := q.db.QueryContext(ctx, listCouponCategoriesByCouponID, couponID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []CouponCategory
	for rows.Next() {
		var i CouponCategory
		if err := rows.Scan(&i.ID, &i.CouponID, &i.CategoryID); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const deleteCouponCategory = `-- name: DeleteCouponCategory :exec
DELETE FROM coupon_categories WHERE id = $1
`

func (q *Queries) DeleteCouponCategory(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, deleteCouponCategory, id)
	return err
}

const createCouponProduct = `-- name: CreateCouponProduct :one
INSERT INTO coupon_products (id, coupon_id, product_id)
VALUES ($1, $2, $3)
RETURNING id, coupon_id, product_id
`

type CreateCouponProductParams struct {
	ID        uuid.UUID
	CouponID  uuid.UUID
	ProductID uuid.UUID
}

func (q *Queries) CreateCouponProduct(ctx context.Context, arg CreateCouponProductParams) (CouponProduct, error) {
	row := q.db.QueryRowContext(ctx, createCouponProduct, arg.ID, arg.CouponID, arg.ProductID)
	var i CouponProduct
	err := row.Scan(&i.ID, &i.CouponID, &i.ProductID)
	return i, err
}

const getCouponProduct = `-- name: GetCouponProduct :one
SELECT id, coupon_id, product_id FROM coupon_products WHERE id = $1
`

func (q *Queries) GetCouponProduct(ctx context.Context, id uuid.UUID) (CouponProduct, error) {
	row := q.db.QueryRowContext(ctx, getCouponProduct, id)
	var i CouponProduct
	err := row.Scan(&i.ID, &i.CouponID, &i.ProductID)
	return i, err
}

const listCouponProducts = `-- name: ListCouponProducts :many
SELECT id, coupon_id, product_id FROM coupon_products ORDER BY id DESC
`

func (q *Queries) ListCouponProducts(ctx context.Context) ([]CouponProduct, error) {
	rows, err := q.db.QueryContext(ctx, listCouponProducts)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []CouponProduct
	for rows.Next() {
		var i CouponProduct
		if err := rows.Scan(&i.ID, &i.CouponID, &i.ProductID); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCouponProductsByCouponID = `-- name: ListCouponProductsByCouponID :many
SELECT id, coupon_id, product_id FROM coupon_products WHERE coupon_id = $1 ORDER BY id DESC
`

func (q *Queries) ListCouponProductsByCouponID(ctx context.Context, couponID uuid.UUID) ([]CouponProduct, error) {
	rows, err := q.db.QueryContext(ctx, listCouponProductsByCouponID, couponID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []CouponProduct
	for rows.Next() {
		var i CouponProduct
		if err := rows.Scan(&i.ID, &i.CouponID, &i.ProductID); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const deleteCouponProduct = `-- name: DeleteCouponProduct :exec
DELETE FROM coupon_products WHERE id = $1
`

func (q *Queries) DeleteCouponProduct(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, deleteCouponProduct, id)
	return err
}

const createPromoCode = `-- name: CreatePromoCode :one
INSERT INTO promo_codes (id, code, campaign_id)
VALUES ($1, $2, $3)
RETURNING id, code, campaign_id
`

type CreatePromoCodeParams struct {
	ID         uuid.UUID
	Code       string
	CampaignID uuid.UUID
}

func (q *Queries) CreatePromoCode(ctx context.Context, arg CreatePromoCodeParams) (PromoCode, error) {
	row := q.db.QueryRowContext(ctx, createPromoCode, arg.ID, arg.Code, arg.CampaignID)
	var i PromoCode
	err := row.Scan(&i.ID, &i.Code, &i.CampaignID)
	return i, err
}

const getPromoCode = `-- name: GetPromoCode :one
SELECT id, code, campaign_id FROM promo_codes WHERE id = $1
`

func (q *Queries) GetPromoCode(ctx context.Context, id uuid.UUID) (PromoCode, error) {
	row := q.db.QueryRowContext(ctx, getPromoCode, id)
	var i PromoCode
	err := row.Scan(&i.ID, &i.Code, &i.CampaignID)
	return i, err
}

const listPromoCodes = `-- name: ListPromoCodes :many
SELECT id, code, campaign_id FROM promo_codes ORDER BY id DESC
`

func (q *Queries) ListPromoCodes(ctx context.Context) ([]PromoCode, error) {
	rows, err := q.db.QueryContext(ctx, listPromoCodes)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []PromoCode
	for rows.Next() {
		var i PromoCode
		if err := rows.Scan(&i.ID, &i.Code, &i.CampaignID); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPromoCodesByCampaignID = `-- name: ListPromoCodesByCampaignID :many
SELECT id, code, campaign_id FROM promo_codes WHERE campaign_id = $1 ORDER BY id DESC
`

func (q *Queries) ListPromoCodesByCampaignID(ctx context.Context, campaignID uuid.UUID) ([]PromoCode, error) {
	rows, err := q.db.QueryContext(ctx, listPromoCodesByCampaignID, campaignID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []PromoCode
	for rows.Next() {
		var i PromoCode
		if err := rows.Scan(&i.ID, &i.Code, &i.CampaignID); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const deletePromoCode = `-- name: DeletePromoCode :exec
DELETE FROM promo_codes WHERE id = $1
`

func (q *Queries) DeletePromoCode(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, deletePromoCode, id)
	return err
}

const createCouponRedemptionLimit = `-- name: CreateCouponRedemptionLimit :one
INSERT INTO coupon_redemption_limits (id, coupon_id, max_redemptions)
VALUES ($1, $2, $3)
RETURNING id, coupon_id, max_redemptions
`

type CreateCouponRedemptionLimitParams struct {
	ID             uuid.UUID
	CouponID       uuid.UUID
	MaxRedemptions int32
}

func (q *Queries) CreateCouponRedemptionLimit(ctx context.Context, arg CreateCouponRedemptionLimitParams) (CouponRedemptionLimit, error) {
	row := q.db.QueryRowContext(ctx, createCouponRedemptionLimit, arg.ID, arg.CouponID, arg.MaxRedemptions)
	var i CouponRedemptionLimit
	err := row.Scan(&i.ID, &i.CouponID, &i.MaxRedemptions)
	return i, err
}

const getCouponRedemptionLimit = `-- name: GetCouponRedemptionLimit :one
SELECT id, coupon_id, max_redemptions FROM coupon_redemption_limits WHERE id = $1
`

func (q *Queries) GetCouponRedemptionLimit(ctx context.Context, id uuid.UUID) (CouponRedemptionLimit, error) {
	row := q.db.QueryRowContext(ctx, getCouponRedemptionLimit, id)
	var i CouponRedemptionLimit
	err := row.Scan(&i.ID, &i.CouponID, &i.MaxRedemptions)
	return i, err
}

const listCouponRedemptionLimits = `-- name: ListCouponRedemptionLimits :many
SELECT id, coupon_id, max_redemptions FROM coupon_redemption_limits ORDER BY id DESC
`

func (q *Queries) ListCouponRedemptionLimits(ctx context.Context) ([]CouponRedemptionLimit, error) {
	rows, err := q.db.QueryContext(ctx, listCouponRedemptionLimits)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []CouponRedemptionLimit
	for rows.Next() {
		var i CouponRedemptionLimit
		if err := rows.Scan(&i.ID, &i.CouponID, &i.MaxRedemptions); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCouponRedemptionLimitsByCouponID = `-- name: ListCouponRedemptionLimitsByCouponID :many
SELECT id, coupon_id, max_redemptions FROM coupon_redemption_limits WHERE coupon_id = $1 ORDER BY id DESC
`

func (q *Queries) ListCouponRedemptionLimitsByCouponID(ctx context.Context, couponID uuid.UUID) ([]CouponRedemptionLimit, error) {
	rows, err := q.db.QueryContext(ctx, listCouponRedemptionLimitsByCouponID, couponID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []CouponRedemptionLimit
	for rows.Next() {
		var i CouponRedemptionLimit
		if err := rows.Scan(&i.ID, &i.CouponID, &i.MaxRedemptions); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const deleteCouponRedemptionLimit = `-- name: DeleteCouponRedemptionLimit :exec
DELETE FROM coupon_redemption_limits WHERE id = $1
`

func (q *Queries) DeleteCouponRedemptionLimit(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, deleteCouponRedemptionLimit, id)
	return err
}

const createCouponStackingRule = `-- name: CreateCouponStackingRule :one
INSERT INTO coupon_stacking_rules (id, coupon_id, stackable_with_coupon_id)
VALUES ($1, $2, $3)
RETURNING id, coupon_id, stackable_with_coupon_id
`

type CreateCouponStackingRuleParams struct {
	ID                    uuid.UUID
	CouponID              uuid.UUID
	StackableWithCouponID uuid.UUID
}

func (q *Queries) CreateCouponStackingRule(ctx context.Context, arg CreateCouponStackingRuleParams) (CouponStackingRule, error) {
	row := q.db.QueryRowContext(ctx, createCouponStackingRule, arg.ID, arg.CouponID, arg.StackableWithCouponID)
	var i CouponStackingRule
	err := row.Scan(&i.ID, &i.CouponID, &i.StackableWithCouponID)
	return i, err
}

const getCouponStackingRule = `-- name: GetCouponStackingRule :one
SELECT id, coupon_id, stackable_with_coupon_id FROM coupon_stacking_rules WHERE id = $1
`

func (q *Queries) GetCouponStackingRule(ctx context.Context, id uuid.UUID) (CouponStackingRule, error) {
	row := q.db.QueryRowContext(ctx, getCouponStackingRule, id)
	var i CouponStackingRule
	err := row.Scan(&i.ID, &i.CouponID, &i.StackableWithCouponID)
	return i, err
}

const listCouponStackingRules = `-- name: ListCouponStackingRules :many
SELECT id, coupon_id, stackable_with_coupon_id FROM coupon_stacking_rules ORDER BY id DESC
`

func (q *Queries) ListCouponStackingRules(ctx context.Context) ([]CouponStackingRule, error) {
	rows, err := q.db.QueryContext(ctx, listCouponStackingRules)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []CouponStackingRule
	for rows.Next() {
		var i CouponStackingRule
		if err := rows.Scan(&i.ID, &i.CouponID, &i.StackableWithCouponID); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCouponStackingRulesByCouponID = `-- name: ListCouponStackingRulesByCouponID :many
SELECT id, coupon_id, stackable_with_coupon_id FROM coupon_stacking_rules WHERE coupon_id = $1 ORDER BY id DESC
`

func (q *Queries) ListCouponStackingRulesByCouponID(ctx context.Context, couponID uuid.UUID) ([]CouponStackingRule, error) {
	rows, err := q.db.QueryContext(ctx, listCouponStackingRulesByCouponID, couponID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []CouponStackingRule
	for rows.Next() {
		var i CouponStackingRule
		if err := rows.Scan(&i.ID, &i.CouponID, &i.StackableWithCouponID); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const deleteCouponStackingRule = `-- name: DeleteCouponStackingRule :exec
DELETE FROM coupon_stacking_rules WHERE id = $1
`

func (q *Queries) DeleteCouponStackingRule(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, deleteCouponStackingRule, id)
	return err
}
