// Code generated by sqlc. DO NOT EDIT.
package sqlc

import (
	"time"

	"github.com/google/uuid"
)

type Coupon struct {
	ID           uuid.UUID
	Code         string
	DiscountRate int32
	ExpiresAt    time.Time
}

type CouponUsage struct {
	ID       uuid.UUID
	CouponID uuid.UUID
	OrderID  uuid.UUID
	UsedAt   time.Time
}

type Campaign struct {
	ID       uuid.UUID
	Name     string
	StartsAt time.Time
	EndsAt   time.Time
}

type CampaignTarget struct {
	ID         uuid.UUID
	CampaignID uuid.UUID
	MemberID   uuid.UUID
}

type DiscountRule struct {
	ID           uuid.UUID
	CouponID     uuid.UUID
	MinAmountYen int32
}

type CouponCategory struct {
	ID         uuid.UUID
	CouponID   uuid.UUID
	CategoryID uuid.UUID
}

type CouponProduct struct {
	ID        uuid.UUID
	CouponID  uuid.UUID
	ProductID uuid.UUID
}

type PromoCode struct {
	ID         uuid.UUID
	Code       string
	CampaignID uuid.UUID
}

type CouponRedemptionLimit struct {
	ID             uuid.UUID
	CouponID       uuid.UUID
	MaxRedemptions int32
}

type CouponStackingRule struct {
	ID                    uuid.UUID
	CouponID              uuid.UUID
	StackableWithCouponID uuid.UUID
}
