// Code generated by sqlc. DO NOT EDIT.
package sqlc

import (
	"time"

	"github.com/google/uuid"
)

type Review struct {
	ID        uuid.UUID
	ProductID uuid.UUID
	MemberID  uuid.UUID
	Rating    int32
	Comment   string
	CreatedAt time.Time
}

type ReviewImage struct {
	ID       uuid.UUID
	ReviewID uuid.UUID
	Url      string
}

type ReviewVote struct {
	ID        uuid.UUID
	ReviewID  uuid.UUID
	MemberID  uuid.UUID
	IsHelpful bool
}

type ReviewReply struct {
	ID        uuid.UUID
	ReviewID  uuid.UUID
	MemberID  uuid.UUID
	Comment   string
	CreatedAt time.Time
}

type ReviewReport struct {
	ID               uuid.UUID
	ReviewID         uuid.UUID
	ReporterMemberID uuid.UUID
	Reason           string
	CreatedAt        time.Time
}

type ReviewTag struct {
	ID   uuid.UUID
	Name string
}

type ReviewTagAssignment struct {
	ID          uuid.UUID
	ReviewID    uuid.UUID
	ReviewTagID uuid.UUID
}

type ReviewSummary struct {
	ID            uuid.UUID
	ProductID     uuid.UUID
	AverageRating int32
	ReviewCount   int32
}

type ReviewInvitation struct {
	ID       uuid.UUID
	OrderID  uuid.UUID
	MemberID uuid.UUID
	SentAt   time.Time
}

type ReviewModerationLog struct {
	ID        uuid.UUID
	ReviewID  uuid.UUID
	Action    string
	CreatedAt time.Time
}
