// Code generated by sqlc. DO NOT EDIT.
package sqlc

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const createReview = `-- name: CreateReview :one
INSERT INTO reviews (id, product_id, member_id, rating, comment, created_at)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, product_id, member_id, rating, comment, created_at
`

type CreateReviewParams struct {
	ID        uuid.UUID
	ProductID uuid.UUID
	MemberID  uuid.UUID
	Rating    int32
	Comment   string
	CreatedAt time.Time
}

func (q *Queries) CreateReview(ctx context.Context, arg CreateReviewParams) (Review, error) {
	row := q.db.QueryRowContext(ctx, createReview, arg.ID, arg.ProductID, arg.MemberID, arg.Rating, arg.Comment, arg.CreatedAt)
	var i Review
	err := row.Scan(&i.ID, &i.ProductID, &i.MemberID, &i.Rating, &i.Comment, &i.CreatedAt)
	return i, err
}

const getReview = `-- name: GetReview :one
SELECT id, product_id, member_id, rating, comment, created_at FROM reviews WHERE id = $1
`

func (q *Queries) GetReview(ctx context.Context, id uuid.UUID) (Review, error) {
	row := q.db.QueryRowContext(ctx, getReview, id)
	var i Review
	err := row.Scan(&i.ID, &i.ProductID, &i.MemberID, &i.Rating, &i.Comment, &i.CreatedAt)
	return i, err
}

const listReviews = `-- name: ListReviews :many
SELECT id, product_id, member_id, rating, comment, created_at FROM reviews ORDER BY created_at DESC
`

func (q *Queries) ListReviews(ctx context.Context) ([]Review, error) {
	rows, err := q.db.QueryContext(ctx, listReviews)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Review
	for rows.Next() {
		var i Review
		if err := rows.Scan(&i.ID, &i.ProductID, &i.MemberID, &i.Rating, &i.Comment, &i.CreatedAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const createReviewImage = `-- name: CreateReviewImage :one
INSERT INTO review_images (id, review_id, url)
VALUES ($1, $2, $3)
RETURNING id, review_id, url
`

type CreateReviewImageParams struct {
	ID       uuid.UUID
	ReviewID uuid.UUID
	Url      string
}

func (q *Queries) CreateReviewImage(ctx context.Context, arg CreateReviewImageParams) (ReviewImage, error) {
	row := q.db.QueryRowContext(ctx, createReviewImage, arg.ID, arg.ReviewID, arg.Url)
	var i ReviewImage
	err := row.Scan(&i.ID, &i.ReviewID, &i.Url)
	return i, err
}

const getReviewImage = `-- name: GetReviewImage :one
SELECT id, review_id, url FROM review_images WHERE id = $1
`

func (q *Queries) GetReviewImage(ctx context.Context, id uuid.UUID) (ReviewImage, error) {
	row := q.db.QueryRowContext(ctx, getReviewImage, id)
	var i ReviewImage
	err := row.Scan(&i.ID, &i.ReviewID, &i.Url)
	return i, err
}

const listReviewImages = `-- name: ListReviewImages :many
SELECT id, review_id, url FROM review_images ORDER BY id DESC
`

func (q *Queries) ListReviewImages(ctx context.Context) ([]ReviewImage, error) {
	rows, err := q.db.QueryContext(ctx, listReviewImages)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ReviewImage
	for rows.Next() {
		var i ReviewImage
		if err := rows.Scan(&i.ID, &i.ReviewID, &i.Url); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listReviewImagesByReviewID = `-- name: ListReviewImagesByReviewID :many
SELECT id, review_id, url FROM review_images WHERE review_id = $1 ORDER BY id DESC
`

func (q *Queries) ListReviewImagesByReviewID(ctx context.Context, reviewID uuid.UUID) ([]ReviewImage, error) {
	rows, err := q.db.QueryContext(ctx, listReviewImagesByReviewID, reviewID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ReviewImage
	for rows.Next() {
		var i ReviewImage
		if err := rows.Scan(&i.ID, &i.ReviewID, &i.Url); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const deleteReviewImage = `-- name: DeleteReviewImage :exec
DELETE FROM review_images WHERE id = $1
`

func (q *Queries) DeleteReviewImage(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, deleteReviewImage, id)
	return err
}

const createReviewVote = `-- name: CreateReviewVote :one
INSERT INTO review_votes (id, review_id, member_id, is_helpful)
VALUES ($1, $2, $3, $4)
RETURNING id, review_id, member_id, is_helpful
`

type CreateReviewVoteParams struct {
	ID        uuid.UUID
	ReviewID  uuid.UUID
	MemberID  uuid.UUID
	IsHelpful bool
}

func (q *Queries) CreateReviewVote(ctx context.Context, arg CreateReviewVoteParams) (ReviewVote, error) {
	row := q.db.QueryRowContext(ctx, createReviewVote, arg.ID, arg.ReviewID, arg.MemberID, arg.IsHelpful)
	var i ReviewVote
	err := row.Scan(&i.ID, &i.ReviewID, &i.MemberID, &i.IsHelpful)
	return i, err
}

const getReviewVote = `-- name: GetReviewVote :one
SELECT id, review_id, member_id, is_helpful FROM review_votes WHERE id = $1
`

func (q *Queries) GetReviewVote(ctx context.Context, id uuid.UUID) (ReviewVote, error) {
	row := q.db.QueryRowContext(ctx, getReviewVote, id)
	var i ReviewVote
	err := row.Scan(&i.ID, &i.ReviewID, &i.MemberID, &i.IsHelpful)
	return i, err
}

const listReviewVotes = `-- name: ListReviewVotes :many
SELECT id, review_id, member_id, is_helpful FROM review_votes ORDER BY id DESC
`

func (q *Queries) ListReviewVotes(ctx context.Context) ([]ReviewVote, error) {
	rows, err := q.db.QueryContext(ctx, listReviewVotes)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ReviewVote
	for rows.Next() {
		var i ReviewVote
		if err := rows.Scan(&i.ID, &i.ReviewID, &i.MemberID, &i.IsHelpful); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listReviewVotesByReviewID = `-- name: ListReviewVotesByReviewID :many
SELECT id, review_id, member_id, is_helpful FROM review_votes WHERE review_id = $1 ORDER BY id DESC
`

func (q *Queries) ListReviewVotesByReviewID(ctx context.Context, reviewID uuid.UUID) ([]ReviewVote, error) {
	rows, err := q.db.QueryContext(ctx, listReviewVotesByReviewID, reviewID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ReviewVote
	for rows.Next() {
		var i ReviewVote
		if err := rows.Scan(&i.ID, &i.ReviewID, &i.MemberID, &i.IsHelpful); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const deleteReviewVote = `-- name: DeleteReviewVote :exec
DELETE FROM review_votes WHERE id = $1
`

func (q *Queries) DeleteReviewVote(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, deleteReviewVote, id)
	return err
}

const createReviewReply = `-- name: CreateReviewReply :one
INSERT INTO review_replies (id, review_id, member_id, comment, created_at)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, review_id, member_id, comment, created_at
`

type CreateReviewReplyParams struct {
	ID        uuid.UUID
	ReviewID  uuid.UUID
	MemberID  uuid.UUID
	Comment   string
	CreatedAt time.Time
}

func (q *Queries) CreateReviewReply(ctx context.Context, arg CreateReviewReplyParams) (ReviewReply, error) {
	row := q.db.QueryRowContext(ctx, createReviewReply, arg.ID, arg.ReviewID, arg.MemberID, arg.Comment, arg.CreatedAt)
	var i ReviewReply
	err := row.Scan(&i.ID, &i.ReviewID, &i.MemberID, &i.Comment, &i.CreatedAt)
	return i, err
}

const getReviewReply = `-- name: GetReviewReply :one
SELECT id, review_id, member_id, comment, created_at FROM review_replies WHERE id = $1
`

func (q *Queries) GetReviewReply(ctx context.Context, id uuid.UUID) (ReviewReply, error) {
	row := q.db.QueryRowContext(ctx, getReviewReply, id)
	var i ReviewReply
	err := row.Scan(&i.ID, &i.ReviewID, &i.MemberID, &i.Comment, &i.CreatedAt)
	return i, err
}

const listReviewReplies = `-- name: ListReviewReplies :many
SELECT id, review_id, member_id, comment, created_at FROM review_replies ORDER BY created_at DESC
`

func (q *Queries) ListReviewReplies(ctx context.Context) ([]ReviewReply, error) {
	rows, err := q.db.QueryContext(ctx, listReviewReplies)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ReviewReply
	for rows.Next() {
		var i ReviewReply
		if err := rows.Scan(&i.ID, &i.ReviewID, &i.MemberID, &i.Comment, &i.CreatedAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listReviewRepliesByReviewID = `-- name: ListReviewRepliesByReviewID :many
SELECT id, review_id, member_id, comment, created_at FROM review_replies WHERE review_id = $1 ORDER BY created_at DESC
`

func (q *Queries) ListReviewRepliesByReviewID(ctx context.Context, reviewID uuid.UUID) ([]ReviewReply, error) {
	rows, err := q.db.QueryContext(ctx, listReviewRepliesByReviewID, reviewID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ReviewReply
	for rows.Next() {
		var i ReviewReply
		if err := rows.Scan(&i.ID, &i.ReviewID, &i.MemberID, &i.Comment, &i.CreatedAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const deleteReviewReply = `-- name: DeleteReviewReply :exec
DELETE FROM review_replies WHERE id = $1
`

func (q *Queries) DeleteReviewReply(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, deleteReviewReply, id)
	return err
}

const createReviewReport = `-- name: CreateReviewReport :one
INSERT INTO review_reports (id, review_id, reporter_member_id, reason, created_at)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, review_id, reporter_member_id, reason, created_at
`

type CreateReviewReportParams struct {
	ID               uuid.UUID
	ReviewID         uuid.UUID
	ReporterMemberID uuid.UUID
	Reason           string
	CreatedAt        time.Time
}

func (q *Queries) CreateReviewReport(ctx context.Context, arg CreateReviewReportParams) (ReviewReport, error) {
	row := q.db.QueryRowContext(ctx, createReviewReport, arg.ID, arg.ReviewID, arg.ReporterMemberID, arg.Reason, arg.CreatedAt)
	var i ReviewReport
	err := row.Scan(&i.ID, &i.ReviewID, &i.ReporterMemberID, &i.Reason, &i.CreatedAt)
	return i, err
}

const getReviewReport = `-- name: GetReviewReport :one
SELECT id, review_id, reporter_member_id, reason, created_at FROM review_reports WHERE id = $1
`

func (q *Queries) GetReviewReport(ctx context.Context, id uuid.UUID) (ReviewReport, error) {
	row := q.db.QueryRowContext(ctx, getReviewReport, id)
	var i ReviewReport
	err := row.Scan(&i.ID, &i.ReviewID, &i.ReporterMemberID, &i.Reason, &i.CreatedAt)
	return i, err
}

const listReviewReports = `-- name: ListReviewReports :many
SELECT id, review_id, reporter_member_id, reason, created_at FROM review_reports ORDER BY created_at DESC
`

func (q *Queries) ListReviewReports(ctx context.Context) ([]ReviewReport, error) {
	rows, err := q.db.QueryContext(ctx, listReviewReports)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ReviewReport
	for rows.Next() {
		var i ReviewReport
		if err := rows.Scan(&i.ID, &i.ReviewID, &i.ReporterMemberID, &i.Reason, &i.CreatedAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listReviewReportsByReviewID = `-- name: ListReviewReportsByReviewID :many
SELECT id, review_id, reporter_member_id, reason, created_at FROM review_reports WHERE review_id = $1 ORDER BY created_at DESC
`

func (q *Queries) ListReviewReportsByReviewID(ctx context.Context, reviewID uuid.UUID) ([]ReviewReport, error) {
	rows, err := q.db.QueryContext(ctx, listReviewReportsByReviewID, reviewID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ReviewReport
	for rows.Next() {
		var i ReviewReport
		if err := rows.Scan(&i.ID, &i.ReviewID, &i.ReporterMemberID, &i.Reason, &i.CreatedAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const deleteReviewReport = `-- name: DeleteReviewReport :exec
DELETE FROM review_reports WHERE id = $1
`

func (q *Queries) DeleteReviewReport(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, deleteReviewReport, id)
	return err
}

const createReviewTag = `-- name: CreateReviewTag :one
INSERT INTO review_tags (id, name)
VALUES ($1, $2)
RETURNING id, name
`

type CreateReviewTagParams struct {
	ID   uuid.UUID
	Name string
}

func (q *Queries) CreateReviewTag(ctx context.Context, arg CreateReviewTagParams) (ReviewTag, error) {
	row := q.db.QueryRowContext(ctx, createReviewTag, arg.ID, arg.Name)
	var i ReviewTag
	err := row.Scan(&i.ID, &i.Name)
	return i, err
}

const getReviewTag = `-- name: GetReviewTag :one
SELECT id, name FROM review_tags WHERE id = $1
`

func (q *Queries) GetReviewTag(ctx context.Context, id uuid.UUID) (ReviewTag, error) {
	row := q.db.QueryRowContext(ctx, getReviewTag, id)
	var i ReviewTag
	err := row.Scan(&i.ID, &i.Name)
	return i, err
}

const listReviewTags = `-- name: ListReviewTags :many
SELECT id, name FROM review_tags ORDER BY id DESC
`

func (q *Queries) ListReviewTags(ctx context.Context) ([]ReviewTag, error) {
	rows, err := q.db.QueryContext(ctx, listReviewTags)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ReviewTag
	for rows.Next() {
		var i ReviewTag
		if err := rows.Scan(&i.ID, &i.Name); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const deleteReviewTag = `-- name: DeleteReviewTag :exec
DELETE FROM review_tags WHERE id = $1
`

func (q *Queries) DeleteReviewTag(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, deleteReviewTag, id)
	return err
}

const createReviewTagAssignment = `-- name: CreateReviewTagAssignment :one
INSERT INTO review_tag_assignments (id, review_id, review_tag_id)
VALUES ($1, $2, $3)
RETURNING id, review_id, review_tag_id
`

type CreateReviewTagAssignmentParams struct {
	ID          uuid.UUID
	ReviewID    uuid.UUID
	ReviewTagID uuid.UUID
}

func (q *Queries) CreateReviewTagAssignment(ctx context.Context, arg CreateReviewTagAssignmentParams) (ReviewTagAssignment, error) {
	row := q.db.QueryRowContext(ctx, createReviewTagAssignment, arg.ID, arg.ReviewID, arg.ReviewTagID)
	var i ReviewTagAssignment
	err := row.Scan(&i.ID, &i.ReviewID, &i.ReviewTagID)
	return i, err
}

const getReviewTagAssignment = `-- name: GetReviewTagAssignment :one
SELECT id, review_id, review_tag_id FROM review_tag_assignments WHERE id = $1
`

func (q *Queries) GetReviewTagAssignment(ctx context.Context, id uuid.UUID) (ReviewTagAssignment, error) {
	row := q.db.QueryRowContext(ctx, getReviewTagAssignment, id)
	var i ReviewTagAssignment
	err := row.Scan(&i.ID, &i.ReviewID, &i.ReviewTagID)
	return i, err
}

const listReviewTagAssignments = `-- name: ListReviewTagAssignments :many
SELECT id, review_id, review_tag_id FROM review_tag_assignments ORDER BY id DESC
`

func (q *Queries) ListReviewTagAssignments(ctx context.Context) ([]ReviewTagAssignment, error) {
	rows, err := q.db.QueryContext(ctx, listReviewTagAssignments)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ReviewTagAssignment
	for rows.Next() {
		var i ReviewTagAssignment
		if err := rows.Scan(&i.ID, &i.ReviewID, &i.ReviewTagID); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listReviewTagAssignmentsByReviewID = `-- name: ListReviewTagAssignmentsByReviewID :many
SELECT id, review_id, review_tag_id FROM review_tag_assignments WHERE review_id = $1 ORDER BY id DESC
`

func (q *Queries) ListReviewTagAssignmentsByReviewID(ctx context.Context, reviewID uuid.UUID) ([]ReviewTagAssignment, error) {
	rows, err := q.db.QueryContext(ctx, listReviewTagAssignmentsByReviewID, reviewID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ReviewTagAssignment
	for rows.Next() {
		var i ReviewTagAssignment
		if err := rows.Scan(&i.ID, &i.ReviewID, &i.ReviewTagID); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const deleteReviewTagAssignment = `-- name: DeleteReviewTagAssignment :exec
DELETE FROM review_tag_assignments WHERE id = $1
`

func (q *Queries) DeleteReviewTagAssignment(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, deleteReviewTagAssignment, id)
	return err
}

const createReviewSummary = `-- name: CreateReviewSummary :one
INSERT INTO review_summaries (id, product_id, average_rating, review_count)
VALUES ($1, $2, $3, $4)
RETURNING id, product_id, average_rating, review_count
`

type CreateReviewSummaryParams struct {
	ID            uuid.UUID
	ProductID     uuid.UUID
	AverageRating int32
	ReviewCount   int32
}

func (q *Queries) CreateReviewSummary(ctx context.Context, arg CreateReviewSummaryParams) (ReviewSummary, error) {
	row := q.db.QueryRowContext(ctx, createReviewSummary, arg.ID, arg.ProductID, arg.AverageRating, arg.ReviewCount)
	var i ReviewSummary
	err := row.Scan(&i.ID, &i.ProductID, &i.AverageRating, &i.ReviewCount)
	return i, err
}

const getReviewSummary = `-- name: GetReviewSummary :one
SELECT id, product_id, average_rating, review_count FROM review_summaries WHERE id = $1
`

func (q *Queries) GetReviewSummary(ctx context.Context, id uuid.UUID) (ReviewSummary, error) {
	row := q.db.QueryRowContext(ctx, getReviewSummary, id)
	var i ReviewSummary
	err := row.Scan(&i.ID, &i.ProductID, &i.AverageRating, &i.ReviewCount)
	return i, err
}

const listReviewSummaries = `-- name: ListReviewSummaries :many
SELECT id, product_id, average_rating, review_count FROM review_summaries ORDER BY id DESC
`

func (q *Queries) ListReviewSummaries(ctx context.Context) ([]ReviewSummary, error) {
	rows, err := q.db.QueryContext(ctx, listReviewSummaries)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ReviewSummary
	for rows.Next() {
		var i ReviewSummary
		if err := rows.Scan(&i.ID, &i.ProductID, &i.AverageRating, &i.ReviewCount); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listReviewSummariesByProductID = `-- name: ListReviewSummariesByProductID :many
SELECT id, product_id, average_rating, review_count FROM review_summaries WHERE product_id = $1 ORDER BY id DESC
`

func (q *Queries) ListReviewSummariesByProductID(ctx context.Context, productID uuid.UUID) ([]ReviewSummary, error) {
	rows, err := q.db.QueryContext(ctx, listReviewSummariesByProductID, productID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ReviewSummary
	for rows.Next() {
		var i ReviewSummary
		if err := rows.Scan(&i.ID, &i.ProductID, &i.AverageRating, &i.ReviewCount); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const deleteReviewSummary = `-- name: DeleteReviewSummary :exec
DELETE FROM review_summaries WHERE id = $1
`

func (q *Queries) DeleteReviewSummary(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, deleteReviewSummary, id)
	return err
}

const createReviewInvitation = `-- name: CreateReviewInvitation :one
INSERT INTO review_invitations (id, order_id, member_id, sent_at)
VALUES ($1, $2, $3, $4)
RETURNING id, order_id, member_id, sent_at
`

type CreateReviewInvitationParams struct {
	ID       uuid.UUID
	OrderID  uuid.UUID
	MemberID uuid.UUID
	SentAt   time.Time
}

func (q *Queries) CreateReviewInvitation(ctx context.Context, arg CreateReviewInvitationParams) (ReviewInvitation, error) {
	row := q.db.QueryRowContext(ctx, createReviewInvitation, arg.ID, arg.OrderID, arg.MemberID, arg.SentAt)
	var i ReviewInvitation
	err := row.Scan(&i.ID, &i.OrderID, &i.MemberID, &i.SentAt)
	return i, err
}

const getReviewInvitation = `-- name: GetReviewInvitation :one
SELECT id, order_id, member_id, sent_at FROM review_invitations WHERE id = $1
`

func (q *Queries) GetReviewInvitation(ctx context.Context, id uuid.UUID) (ReviewInvitation, error) {
	row := q.db.QueryRowContext(ctx, getReviewInvitation, id)
	var i ReviewInvitation
	err := row.Scan(&i.ID, &i.OrderID, &i.MemberID, &i.SentAt)
	return i, err
}

const listReviewInvitations = `-- name: ListReviewInvitations :many
SELECT id, order_id, member_id, sent_at FROM review_invitations ORDER BY sent_at DESC
`

func (q *Queries) ListReviewInvitations(ctx context.Context) ([]ReviewInvitation, error) {
	rows, err := q.db.QueryContext(ctx, listReviewInvitations)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ReviewInvitation
	for rows.Next() {
		var i ReviewInvitation
		if err := rows.Scan(&i.ID, &i.OrderID, &i.MemberID, &i.SentAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listReviewInvitationsByOrderID = `-- name: ListReviewInvitationsByOrderID :many
SELECT id, order_id, member_id, sent_at FROM review_invitations WHERE order_id = $1 ORDER BY sent_at DESC
`

func (q *Queries) ListReviewInvitationsByOrderID(ctx context.Context, orderID uuid.UUID) ([]ReviewInvitation, error) {
	rows, err := q.db.QueryContext(ctx, listReviewInvitationsByOrderID, orderID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ReviewInvitation
	for rows.Next() {
		var i ReviewInvitation
		if err := rows.Scan(&i.ID, &i.OrderID, &i.MemberID, &i.SentAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const deleteReviewInvitation = `-- name: DeleteReviewInvitation :exec
DELETE FROM review_invitations WHERE id = $1
`

func (q *Queries) DeleteReviewInvitation(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, deleteReviewInvitation, id)
	return err
}

const createReviewModerationLog = `-- name: CreateReviewModerationLog :one
INSERT INTO review_moderation_logs (id, review_id, action, created_at)
VALUES ($1, $2, $3, $4)
RETURNING id, review_id, action, created_at
`

type CreateReviewModerationLogParams struct {
	ID        uuid.UUID
	ReviewID  uuid.UUID
	Action    string
	CreatedAt time.Time
}

func (q *Queries) CreateReviewModerationLog(ctx context.Context, arg CreateReviewModerationLogParams) (ReviewModerationLog, error) {
	row := q.db.QueryRowContext(ctx, createReviewModerationLog, arg.ID, arg.ReviewID, arg.Action, arg.CreatedAt)
	var i ReviewModerationLog
	err := row.Scan(&i.ID, &i.ReviewID, &i.Action, &i.CreatedAt)
	return i, err
}

const getReviewModerationLog = `-- name: GetReviewModerationLog :one
SELECT id, review_id, action, created_at FROM review_moderation_logs WHERE id = $1
`

func (q *Queries) GetReviewModerationLog(ctx context.Context, id uuid.UUID) (ReviewModerationLog, error) {
	row := q.db.QueryRowContext(ctx, getReviewModerationLog, id)
	var i ReviewModerationLog
	err := row.Scan(&i.ID, &i.ReviewID, &i.Action, &i.CreatedAt)
	return i, err
}

const listReviewModerationLogs = `-- name: ListReviewModerationLogs :many
SELECT id, review_id, action, created_at FROM review_moderation_logs ORDER BY created_at DESC
`

func (q *Queries) ListReviewModerationLogs(ctx context.Context) ([]ReviewModerationLog, error) {
	rows, err := q.db.QueryContext(ctx, listReviewModerationLogs)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ReviewModerationLog
	for rows.Next() {
		var i ReviewModerationLog
		if err := rows.Scan(&i.ID, &i.ReviewID, &i.Action, &i.CreatedAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listReviewModerationLogsByReviewID = `-- name: ListReviewModerationLogsByReviewID :many
SELECT id, review_id, action, created_at FROM review_moderation_logs WHERE review_id = $1 ORDER BY created_at DESC
`

func (q *Queries) ListReviewModerationLogsByReviewID(ctx context.Context, reviewID uuid.UUID) ([]ReviewModerationLog, error) {
	rows, err := q.db.QueryContext(ctx, listReviewModerationLogsByReviewID, reviewID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ReviewModerationLog
	for rows.Next() {
		var i ReviewModerationLog
		if err := rows.Scan(&i.ID, &i.ReviewID, &i.Action, &i.CreatedAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const deleteReviewModerationLog = `-- name: DeleteReviewModerationLog :exec
DELETE FROM review_moderation_logs WHERE id = $1
`

func (q *Queries) DeleteReviewModerationLog(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, deleteReviewModerationLog, id)
	return err
}
